"""
AI Radar 2.0 Config - Data Sources and Category Definitions
"""

# 分栏定义 (中英双语)
CATEGORIES = {
    "news": {
        "zh": "⚡ 突发·行业快讯",
        "en": "⚡ Breaking News"
    },
    "celebrity": {
        "zh": "🐦 领袖观点·社交热议",
        "en": "🐦 Voices & Social X"
    },
    "tools": {
        "zh": "🛠️ 场景落地·实用神器",
        "en": "🛠️ Applied AI Tools"
    },
    "videos": {
        "zh": "🎬 实战视频·演示",
        "en": "🎬 Hands-on Videos"
    },
    "prompts": {
        "zh": "💡 提示词库·咒语",
        "en": "💡 Prompt Bank"
    }
}

# 场景分类标签
SCENARIO_TAGS = {
    "image": "🎨 图像修图/设计",
    "video": "🎬 视频创作合成",
    "code": "💻 编程开发提效",
    "agent": "🤖 智能体/工作流",
    "office": "✍️ 写作办公知识库",
    "audio": "🎙️ 声音克隆音频",
    "chatbot": "💬 AI 客户端应用"
}

# 体验门槛标签
PRICING_TAGS = {
    "free_open": "🟢 开源免费",
    "freemium": "🟡 免费试玩",
    "paid": "🔴 商业软件"
}

# 名人识别库及头像映射 (覆盖全球顶尖 AI 领袖、核心科学家与高频发声一线工程师)
CELEBRITY_PROFILES = {
    # =========================================================================
    # 🏢 官方企业、品牌与实验室 (120+ 家独角兽与巨头，严格标记 company)
    # =========================================================================
    "openai": {"name": "OpenAI 官方", "handle": "@OpenAI", "role": "OpenAI 官方发布与模型前沿", "avatar": "https://unavatar.io/openai", "platform": "x", "entity_type": "company"},
    "openai 官方": {"name": "OpenAI 官方", "handle": "@OpenAI", "role": "OpenAI 官方发布与模型前沿", "avatar": "https://unavatar.io/openai", "platform": "x", "entity_type": "company"},
    "openaidevs": {"name": "OpenAI Developers", "handle": "@OpenAIDevs", "role": "OpenAI 开发者官方平台", "avatar": "https://unavatar.io/openai", "platform": "x", "entity_type": "company"},
    "openai developers": {"name": "OpenAI Developers", "handle": "@OpenAIDevs", "role": "OpenAI 开发者官方平台", "avatar": "https://unavatar.io/openai", "platform": "x", "entity_type": "company"},
    "anthropicai": {"name": "Anthropic 官方", "handle": "@AnthropicAI", "role": "Claude 研发官方团队", "avatar": "https://unavatar.io/anthropic", "platform": "x", "entity_type": "company"},
    "anthropic 官方": {"name": "Anthropic 官方", "handle": "@AnthropicAI", "role": "Claude 研发官方团队", "avatar": "https://unavatar.io/anthropic", "platform": "x", "entity_type": "company"},
    "claudeai": {"name": "Claude 官方", "handle": "@ClaudeAI", "role": "Anthropic Claude 官方助手", "avatar": "https://unavatar.io/anthropic", "platform": "x", "entity_type": "company"},
    "claude 官方": {"name": "Claude 官方", "handle": "@ClaudeAI", "role": "Anthropic Claude 官方助手", "avatar": "https://unavatar.io/anthropic", "platform": "x", "entity_type": "company"},
    "googleai": {"name": "Google AI", "handle": "@GoogleAI", "role": "Google AI 研发官方团队", "avatar": "https://unavatar.io/google", "platform": "x", "entity_type": "company"},
    "google ai": {"name": "Google AI", "handle": "@GoogleAI", "role": "Google AI 研发官方团队", "avatar": "https://unavatar.io/google", "platform": "x", "entity_type": "company"},
    "googledeepmind": {"name": "Google DeepMind", "handle": "@GoogleDeepMind", "role": "Google DeepMind 官方团队", "avatar": "https://unavatar.io/x/GoogleDeepMind", "platform": "x", "entity_type": "company"},
    "google deepmind": {"name": "Google DeepMind", "handle": "@GoogleDeepMind", "role": "Google DeepMind 官方团队", "avatar": "https://unavatar.io/x/GoogleDeepMind", "platform": "x", "entity_type": "company"},
    "googleaistudio": {"name": "Google AI Studio", "handle": "@GoogleAIStudio", "role": "Google AI 开发者官方平台", "avatar": "https://unavatar.io/x/GoogleAIStudio", "platform": "x", "entity_type": "company"},
    "google ai studio": {"name": "Google AI Studio", "handle": "@GoogleAIStudio", "role": "Google AI 开发者官方平台", "avatar": "https://unavatar.io/x/GoogleAIStudio", "platform": "x", "entity_type": "company"},
    "metaai": {"name": "Meta AI", "handle": "@MetaAI", "role": "Meta 开源与前沿 AI 团队", "avatar": "https://unavatar.io/meta", "platform": "x", "entity_type": "company"},
    "meta ai": {"name": "Meta AI", "handle": "@MetaAI", "role": "Meta 开源与前沿 AI 团队", "avatar": "https://unavatar.io/meta", "platform": "x", "entity_type": "company"},
    "xai": {"name": "xAI 官方", "handle": "@xai", "role": "Grok 研发官方团队", "avatar": "https://unavatar.io/x/xai", "platform": "x", "entity_type": "company"},
    "xai 官方": {"name": "xAI 官方", "handle": "@xai", "role": "Grok 研发官方团队", "avatar": "https://unavatar.io/x/xai", "platform": "x", "entity_type": "company"},
    "mistralai": {"name": "Mistral AI", "handle": "@MistralAI", "role": "欧洲前沿开源与商业模型实验室", "avatar": "https://unavatar.io/x/MistralAI", "platform": "x", "entity_type": "company"},
    "mistral ai": {"name": "Mistral AI", "handle": "@MistralAI", "role": "欧洲前沿开源与商业模型实验室", "avatar": "https://unavatar.io/x/MistralAI", "platform": "x", "entity_type": "company"},
    "cohere": {"name": "Cohere", "handle": "@Cohere", "role": "企业级前沿大语言模型实验室", "avatar": "https://unavatar.io/x/Cohere", "platform": "x", "entity_type": "company"},
    "msftresearch": {"name": "Microsoft Research", "handle": "@MSFTResearch", "role": "微软研究院官方", "avatar": "https://unavatar.io/microsoft", "platform": "x", "entity_type": "company"},
    "microsoft research": {"name": "Microsoft Research", "handle": "@MSFTResearch", "role": "微软研究院官方", "avatar": "https://unavatar.io/microsoft", "platform": "x", "entity_type": "company"},
    "microsoft": {"name": "Microsoft", "handle": "@Microsoft", "role": "微软官方技术动态", "avatar": "https://unavatar.io/microsoft", "platform": "x", "entity_type": "company"},
    "apple": {"name": "Apple Machine Learning", "handle": "@Apple", "role": "苹果机器学习与设备端 AI 研发", "avatar": "https://unavatar.io/apple", "platform": "x", "entity_type": "company"},
    "apple machine learning": {"name": "Apple Machine Learning", "handle": "@Apple", "role": "苹果机器学习与设备端 AI 研发", "avatar": "https://unavatar.io/apple", "platform": "x", "entity_type": "company"},
    "awscloud": {"name": "AWS Cloud AI", "handle": "@awscloud", "role": "亚马逊云科技生成式 AI", "avatar": "https://unavatar.io/aws", "platform": "x", "entity_type": "company"},
    "aws cloud ai": {"name": "AWS Cloud AI", "handle": "@awscloud", "role": "亚马逊云科技生成式 AI", "avatar": "https://unavatar.io/aws", "platform": "x", "entity_type": "company"},
    "ibmresearch": {"name": "IBM Research", "handle": "@IBMResearch", "role": "IBM 研究院基础模型与量子计算", "avatar": "https://unavatar.io/ibm", "platform": "x", "entity_type": "company"},
    "ibm research": {"name": "IBM Research", "handle": "@IBMResearch", "role": "IBM 研究院基础模型与量子计算", "avatar": "https://unavatar.io/ibm", "platform": "x", "entity_type": "company"},
    "intelai": {"name": "Intel AI", "handle": "@IntelAI", "role": "英特尔 AI 硬件加速与 Gaudi 计算", "avatar": "https://unavatar.io/intel", "platform": "x", "entity_type": "company"},
    "intel ai": {"name": "Intel AI", "handle": "@IntelAI", "role": "英特尔 AI 硬件加速与 Gaudi 计算", "avatar": "https://unavatar.io/intel", "platform": "x", "entity_type": "company"},
    "nvidia": {"name": "NVIDIA 官方", "handle": "@NVIDIA", "role": "NVIDIA 全球算力与 AI 基础设施", "avatar": "https://unavatar.io/nvidia", "platform": "x", "entity_type": "company"},
    "nvidia 官方": {"name": "NVIDIA 官方", "handle": "@NVIDIA", "role": "NVIDIA 全球算力与 AI 基础设施", "avatar": "https://unavatar.io/nvidia", "platform": "x", "entity_type": "company"},
    "nvidiaai": {"name": "NVIDIA AI", "handle": "@NVIDIAAI", "role": "NVIDIA AI 研究与开发者生态", "avatar": "https://unavatar.io/nvidia", "platform": "x", "entity_type": "company"},
    "nvidia ai": {"name": "NVIDIA AI", "handle": "@NVIDIAAI", "role": "NVIDIA AI 研究与开发者生态", "avatar": "https://unavatar.io/nvidia", "platform": "x", "entity_type": "company"},
    "nvidiaomniverse": {"name": "NVIDIA Omniverse", "handle": "@nvidiaomniverse", "role": "数字孪生与物理具身仿真平台", "avatar": "https://unavatar.io/nvidia", "platform": "x", "entity_type": "company"},
    "nvidia omniverse": {"name": "NVIDIA Omniverse", "handle": "@nvidiaomniverse", "role": "数字孪生与物理具身仿真平台", "avatar": "https://unavatar.io/nvidia", "platform": "x", "entity_type": "company"},
    "amd": {"name": "AMD", "handle": "@AMD", "role": "AMD 算力芯片与 ROCm 生态", "avatar": "https://unavatar.io/amd", "platform": "x", "entity_type": "company"},
    "arm": {"name": "Arm", "handle": "@Arm", "role": "全球移动与端侧边缘 AI 架构计算先锋", "avatar": "https://unavatar.io/arm", "platform": "x", "entity_type": "company"},
    "qualcomm": {"name": "Qualcomm", "handle": "@Qualcomm", "role": "高通骁龙端侧 NPU 与混合 AI 计算", "avatar": "https://unavatar.io/qualcomm", "platform": "x", "entity_type": "company"},
    "groqinc": {"name": "Groq", "handle": "@GroqInc", "role": "LPU 极速超低延迟推理芯片先锋", "avatar": "https://unavatar.io/x/GroqInc", "platform": "x", "entity_type": "company"},
    "groq": {"name": "Groq", "handle": "@GroqInc", "role": "LPU 极速超低延迟推理芯片先锋", "avatar": "https://unavatar.io/x/GroqInc", "platform": "x", "entity_type": "company"},
    "cerebrassystems": {"name": "Cerebras", "handle": "@CerebrasSystems", "role": "晶圆级超级计算晶片开创者", "avatar": "https://unavatar.io/x/CerebrasSystems", "platform": "x", "entity_type": "company"},
    "cerebras": {"name": "Cerebras", "handle": "@CerebrasSystems", "role": "晶圆级超级计算晶片开创者", "avatar": "https://unavatar.io/x/CerebrasSystems", "platform": "x", "entity_type": "company"},
    "togethercompute": {"name": "Together AI", "handle": "@togethercompute", "role": "分布式开源模型训练与推理云", "avatar": "https://unavatar.io/x/togethercompute", "platform": "x", "entity_type": "company"},
    "together ai": {"name": "Together AI", "handle": "@togethercompute", "role": "分布式开源模型训练与推理云", "avatar": "https://unavatar.io/x/togethercompute", "platform": "x", "entity_type": "company"},
    "fireworksai": {"name": "Fireworks AI", "handle": "@fireworksai", "role": "极速生成式 AI 生产级 API 云", "avatar": "https://unavatar.io/x/fireworksai", "platform": "x", "entity_type": "company"},
    "fireworks ai": {"name": "Fireworks AI", "handle": "@fireworksai", "role": "极速生成式 AI 生产级 API 云", "avatar": "https://unavatar.io/x/fireworksai", "platform": "x", "entity_type": "company"},
    "openrouter": {"name": "OpenRouter", "handle": "@openrouter", "role": "全球统一 LLM 路由与算力网关", "avatar": "https://unavatar.io/x/openrouter", "platform": "x", "entity_type": "company"},
    "lambdaapi": {"name": "Lambda Labs", "handle": "@LambdaAPI", "role": "AI 开发者深度学习 GPU 云", "avatar": "https://unavatar.io/x/LambdaAPI", "platform": "x", "entity_type": "company"},
    "lambda labs": {"name": "Lambda Labs", "handle": "@LambdaAPI", "role": "AI 开发者深度学习 GPU 云", "avatar": "https://unavatar.io/x/LambdaAPI", "platform": "x", "entity_type": "company"},
    "coreweave": {"name": "CoreWeave", "handle": "@CoreWeave", "role": "专业级大规模算力 GPU 云基础设施", "avatar": "https://unavatar.io/x/CoreWeave", "platform": "x", "entity_type": "company"},
    "runpod_io": {"name": "RunPod", "handle": "@runpod_io", "role": "全球分布式 GPU 无服务器算力平台", "avatar": "https://unavatar.io/x/runpod_io", "platform": "x", "entity_type": "company"},
    "runpod": {"name": "RunPod", "handle": "@runpod_io", "role": "全球分布式 GPU 无服务器算力平台", "avatar": "https://unavatar.io/x/runpod_io", "platform": "x", "entity_type": "company"},
    "modal_labs": {"name": "Modal", "handle": "@modal_labs", "role": "高性能云端 AI 无服务器计算平台", "avatar": "https://unavatar.io/x/modal_labs", "platform": "x", "entity_type": "company"},
    "modal": {"name": "Modal", "handle": "@modal_labs", "role": "高性能云端 AI 无服务器计算平台", "avatar": "https://unavatar.io/x/modal_labs", "platform": "x", "entity_type": "company"},
    "replicate": {"name": "Replicate", "handle": "@replicate", "role": "云端一键运行与部署机器学习模型", "avatar": "https://unavatar.io/x/replicate", "platform": "x", "entity_type": "company"},
    "anyscalecompute": {"name": "Anyscale", "handle": "@anyscalecompute", "role": "Ray 分布式架构背后的生成式 AI 平台", "avatar": "https://unavatar.io/x/anyscalecompute", "platform": "x", "entity_type": "company"},
    "anyscale": {"name": "Anyscale", "handle": "@anyscalecompute", "role": "Ray 分布式架构背后的生成式 AI 平台", "avatar": "https://unavatar.io/x/anyscalecompute", "platform": "x", "entity_type": "company"},
    "baseten": {"name": "Baseten", "handle": "@baseten", "role": "企业级极速模型部署与微调引擎", "avatar": "https://unavatar.io/x/baseten", "platform": "x", "entity_type": "company"},
    "sambanovaai": {"name": "SambaNova Systems", "handle": "@SambaNovaAI", "role": "可重构数据流完整全栈企业级芯片平台", "avatar": "https://unavatar.io/x/SambaNovaAI", "platform": "x", "entity_type": "company"},
    "sambanova systems": {"name": "SambaNova Systems", "handle": "@SambaNovaAI", "role": "可重构数据流完整全栈企业级芯片平台", "avatar": "https://unavatar.io/x/SambaNovaAI", "platform": "x", "entity_type": "company"},
    "tenstorrent": {"name": "Tenstorrent", "handle": "@tenstorrent", "role": "Jim Keller 掌舵的高性能 RISC-V 与 AI 硬件", "avatar": "https://unavatar.io/x/tenstorrent", "platform": "x", "entity_type": "company"},
    "deepseek_ai": {"name": "DeepSeek 深度求索", "handle": "@deepseek_ai", "role": "DeepSeek 官方开源模型研发团队", "avatar": "https://unavatar.io/github/deepseek-ai", "platform": "x", "entity_type": "company"},
    "deepseek 深度求索": {"name": "DeepSeek 深度求索", "handle": "@deepseek_ai", "role": "DeepSeek 官方开源模型研发团队", "avatar": "https://unavatar.io/github/deepseek-ai", "platform": "x", "entity_type": "company"},
    "alibaba_qwen": {"name": "Qwen 通义千问", "handle": "@Alibaba_Qwen", "role": "阿里巴巴通义开源模型团队", "avatar": "https://unavatar.io/x/Alibaba_Qwen", "platform": "x", "entity_type": "company"},
    "qwen 通义千问": {"name": "Qwen 通义千问", "handle": "@Alibaba_Qwen", "role": "阿里巴巴通义开源模型团队", "avatar": "https://unavatar.io/x/Alibaba_Qwen", "platform": "x", "entity_type": "company"},
    "moonshotai": {"name": "Moonshot AI 月之暗面", "handle": "@MoonshotAI", "role": "Kimi 长上下文与推理大模型官方", "avatar": "https://unavatar.io/x/MoonshotAI", "platform": "x", "entity_type": "company"},
    "moonshot ai 月之暗面": {"name": "Moonshot AI 月之暗面", "handle": "@MoonshotAI", "role": "Kimi 长上下文与推理大模型官方", "avatar": "https://unavatar.io/x/MoonshotAI", "platform": "x", "entity_type": "company"},
    "minimax_ai": {"name": "MiniMax", "handle": "@MiniMax_AI", "role": "MiniMax 文本/语音/视频原生大模型", "avatar": "https://unavatar.io/x/MiniMax_AI", "platform": "x", "entity_type": "company"},
    "minimax": {"name": "MiniMax", "handle": "@MiniMax_AI", "role": "MiniMax 文本/语音/视频原生大模型", "avatar": "https://unavatar.io/x/MiniMax_AI", "platform": "x", "entity_type": "company"},
    "zhipuai": {"name": "智谱 AI", "handle": "@ZhipuAI", "role": "GLM 系列基座大模型研发团队", "avatar": "https://unavatar.io/x/ZhipuAI", "platform": "x", "entity_type": "company"},
    "智谱 ai": {"name": "智谱 AI", "handle": "@ZhipuAI", "role": "GLM 系列基座大模型研发团队", "avatar": "https://unavatar.io/x/ZhipuAI", "platform": "x", "entity_type": "company"},
    "baichuanai": {"name": "百川智能", "handle": "@BaichuanAI", "role": "王小川领衔研发的百川基座模型", "avatar": "https://unavatar.io/x/BaichuanAI", "platform": "x", "entity_type": "company"},
    "百川智能": {"name": "百川智能", "handle": "@BaichuanAI", "role": "王小川领衔研发的百川基座模型", "avatar": "https://unavatar.io/x/BaichuanAI", "platform": "x", "entity_type": "company"},
    "stepfun_ai": {"name": "阶跃星辰", "handle": "@stepfun_ai", "role": "Step 系列通用多模态大模型", "avatar": "https://unavatar.io/x/stepfun_ai", "platform": "x", "entity_type": "company"},
    "阶跃星辰": {"name": "阶跃星辰", "handle": "@stepfun_ai", "role": "Step 系列通用多模态大模型", "avatar": "https://unavatar.io/x/stepfun_ai", "platform": "x", "entity_type": "company"},
    "sensetime_tech": {"name": "商汤科技 SenseTime", "handle": "@sensetime_tech", "role": "日日新大模型与算力集群", "avatar": "https://unavatar.io/x/sensetime_tech", "platform": "x", "entity_type": "company"},
    "商汤科技 sensetime": {"name": "商汤科技 SenseTime", "handle": "@sensetime_tech", "role": "日日新大模型与算力集群", "avatar": "https://unavatar.io/x/sensetime_tech", "platform": "x", "entity_type": "company"},
    "bytedancetalk": {"name": "字节跳动 AI", "handle": "@ByteDanceTalk", "role": "豆包 Doubao 与 Seed 系列基础模型", "avatar": "https://unavatar.io/x/ByteDanceTalk", "platform": "x", "entity_type": "company"},
    "字节跳动 ai": {"name": "字节跳动 AI", "handle": "@ByteDanceTalk", "role": "豆包 Doubao 与 Seed 系列基础模型", "avatar": "https://unavatar.io/x/ByteDanceTalk", "platform": "x", "entity_type": "company"},
    "tencentglobal": {"name": "腾讯混元", "handle": "@TencentGlobal", "role": "腾讯混元大模型与前沿实验室", "avatar": "https://unavatar.io/tencent", "platform": "x", "entity_type": "company"},
    "腾讯混元": {"name": "腾讯混元", "handle": "@TencentGlobal", "role": "腾讯混元大模型与前沿实验室", "avatar": "https://unavatar.io/tencent", "platform": "x", "entity_type": "company"},
    "baidu_inc": {"name": "百度文心", "handle": "@Baidu_Inc", "role": "文心一言 ERNIE 基础大模型", "avatar": "https://unavatar.io/baidu", "platform": "x", "entity_type": "company"},
    "百度文心": {"name": "百度文心", "handle": "@Baidu_Inc", "role": "文心一言 ERNIE 基础大模型", "avatar": "https://unavatar.io/baidu", "platform": "x", "entity_type": "company"},
    "cursor_ai": {"name": "Cursor", "handle": "@cursor_ai", "role": "AI 原生代码编辑器官方", "avatar": "https://unavatar.io/x/cursor_ai", "platform": "x", "entity_type": "company"},
    "cursor": {"name": "Cursor", "handle": "@cursor_ai", "role": "AI 原生代码编辑器官方", "avatar": "https://unavatar.io/x/cursor_ai", "platform": "x", "entity_type": "company"},
    "github": {"name": "GitHub", "handle": "@github", "role": "全球开源大本营与 Copilot 开发者生态", "avatar": "https://unavatar.io/github", "platform": "x", "entity_type": "company"},
    "replit": {"name": "Replit", "handle": "@replit", "role": "AI Agent 原生云端编程与软件创作平台", "avatar": "https://unavatar.io/x/replit", "platform": "x", "entity_type": "company"},
    "v0": {"name": "v0 by Vercel", "handle": "@v0", "role": "生成式前端 UI 交互设计利器", "avatar": "https://unavatar.io/x/v0", "platform": "x", "entity_type": "company"},
    "v0 by vercel": {"name": "v0 by Vercel", "handle": "@v0", "role": "生成式前端 UI 交互设计利器", "avatar": "https://unavatar.io/x/v0", "platform": "x", "entity_type": "company"},
    "vercel": {"name": "Vercel", "handle": "@vercel", "role": "AI Web 全栈云与 Next.js 开发者生态", "avatar": "https://unavatar.io/vercel", "platform": "x", "entity_type": "company"},
    "cognition_labs": {"name": "Cognition (Devin)", "handle": "@cognition_labs", "role": "全球首个完全自主 AI 软件工程师 Devin 创作者", "avatar": "https://unavatar.io/x/cognition_labs", "platform": "x", "entity_type": "company"},
    "cognition (devin)": {"name": "Cognition (Devin)", "handle": "@cognition_labs", "role": "全球首个完全自主 AI 软件工程师 Devin 创作者", "avatar": "https://unavatar.io/x/cognition_labs", "platform": "x", "entity_type": "company"},
    "codeiumdev": {"name": "Windsurf / Codeium", "handle": "@codeiumdev", "role": "Windsurf AI 驱动全流程开发 IDE", "avatar": "https://unavatar.io/x/codeiumdev", "platform": "x", "entity_type": "company"},
    "windsurf / codeium": {"name": "Windsurf / Codeium", "handle": "@codeiumdev", "role": "Windsurf AI 驱动全流程开发 IDE", "avatar": "https://unavatar.io/x/codeiumdev", "platform": "x", "entity_type": "company"},
    "tabnine": {"name": "Tabnine", "handle": "@tabnine", "role": "企业级隐私优先代码智能补全工具", "avatar": "https://unavatar.io/x/tabnine", "platform": "x", "entity_type": "company"},
    "supermaven_ai": {"name": "Supermaven", "handle": "@supermaven_ai", "role": "拥有 1M 上下文极速代码智能补全工具", "avatar": "https://unavatar.io/x/supermaven_ai", "platform": "x", "entity_type": "company"},
    "supermaven": {"name": "Supermaven", "handle": "@supermaven_ai", "role": "拥有 1M 上下文极速代码智能补全工具", "avatar": "https://unavatar.io/x/supermaven_ai", "platform": "x", "entity_type": "company"},
    "sourcegraph": {"name": "Sourcegraph (Cody)", "handle": "@sourcegraph", "role": "大型代码库全局感知 AI 助手 Cody", "avatar": "https://unavatar.io/x/sourcegraph", "platform": "x", "entity_type": "company"},
    "sourcegraph (cody)": {"name": "Sourcegraph (Cody)", "handle": "@sourcegraph", "role": "大型代码库全局感知 AI 助手 Cody", "avatar": "https://unavatar.io/x/sourcegraph", "platform": "x", "entity_type": "company"},
    "continuedev": {"name": "Continue", "handle": "@continuedev", "role": "开源模块化 VS Code / JetBrains 编程插件", "avatar": "https://unavatar.io/x/continuedev", "platform": "x", "entity_type": "company"},
    "continue": {"name": "Continue", "handle": "@continuedev", "role": "开源模块化 VS Code / JetBrains 编程插件", "avatar": "https://unavatar.io/x/continuedev", "platform": "x", "entity_type": "company"},
    "aider_ai": {"name": "Aider", "handle": "@aider_ai", "role": "命令行极客自主全仓 AI 配对编程框架", "avatar": "https://unavatar.io/x/aider_ai", "platform": "x", "entity_type": "company"},
    "aider": {"name": "Aider", "handle": "@aider_ai", "role": "命令行极客自主全仓 AI 配对编程框架", "avatar": "https://unavatar.io/x/aider_ai", "platform": "x", "entity_type": "company"},
    "lovable_dev": {"name": "Lovable", "handle": "@Lovable_dev", "role": "全栈自然语言一键构建完整 Web 应用", "avatar": "https://unavatar.io/x/Lovable_dev", "platform": "x", "entity_type": "company"},
    "lovable": {"name": "Lovable", "handle": "@Lovable_dev", "role": "全栈自然语言一键构建完整 Web 应用", "avatar": "https://unavatar.io/x/Lovable_dev", "platform": "x", "entity_type": "company"},
    "stackblitz": {"name": "Bolt.new / StackBlitz", "handle": "@stackblitz", "role": "WebContainer 驱动的纯前端浏览器一键全栈开发", "avatar": "https://unavatar.io/x/stackblitz", "platform": "x", "entity_type": "company"},
    "bolt.new / stackblitz": {"name": "Bolt.new / StackBlitz", "handle": "@stackblitz", "role": "WebContainer 驱动的纯前端浏览器一键全栈开发", "avatar": "https://unavatar.io/x/stackblitz", "platform": "x", "entity_type": "company"},
    "magic_dev": {"name": "Magic AI", "handle": "@magic_dev", "role": "超长上下文超级软件工程师模型研发团队", "avatar": "https://unavatar.io/x/magic_dev", "platform": "x", "entity_type": "company"},
    "magic ai": {"name": "Magic AI", "handle": "@magic_dev", "role": "超长上下文超级软件工程师模型研发团队", "avatar": "https://unavatar.io/x/magic_dev", "platform": "x", "entity_type": "company"},
    "augmentcode": {"name": "Augment Code", "handle": "@augmentcode", "role": "专为巨型企业级复杂代码库定制的 AI 编程引擎", "avatar": "https://unavatar.io/x/augmentcode", "platform": "x", "entity_type": "company"},
    "augment code": {"name": "Augment Code", "handle": "@augmentcode", "role": "专为巨型企业级复杂代码库定制的 AI 编程引擎", "avatar": "https://unavatar.io/x/augmentcode", "platform": "x", "entity_type": "company"},
    "factoryai": {"name": "Factory AI", "handle": "@FactoryAI", "role": "自动化企业级软件工程 AI Droids", "avatar": "https://unavatar.io/x/FactoryAI", "platform": "x", "entity_type": "company"},
    "factory ai": {"name": "Factory AI", "handle": "@FactoryAI", "role": "自动化企业级软件工程 AI Droids", "avatar": "https://unavatar.io/x/FactoryAI", "platform": "x", "entity_type": "company"},
    "warpdotdev": {"name": "Warp Terminal", "handle": "@warpdotdev", "role": "AI 原生智能终端与极客工作流", "avatar": "https://unavatar.io/x/warpdotdev", "platform": "x", "entity_type": "company"},
    "warp terminal": {"name": "Warp Terminal", "handle": "@warpdotdev", "role": "AI 原生智能终端与极客工作流", "avatar": "https://unavatar.io/x/warpdotdev", "platform": "x", "entity_type": "company"},
    "midjourney": {"name": "Midjourney", "handle": "@midjourney", "role": "顶级艺术级 AI 图像生成工坊", "avatar": "https://unavatar.io/x/midjourney", "platform": "x", "entity_type": "company"},
    "runwayml": {"name": "Runway", "handle": "@runwayml", "role": "Gen-3 电影级视频生成模型独角兽", "avatar": "https://unavatar.io/x/runwayml", "platform": "x", "entity_type": "company"},
    "runway": {"name": "Runway", "handle": "@runwayml", "role": "Gen-3 电影级视频生成模型独角兽", "avatar": "https://unavatar.io/x/runwayml", "platform": "x", "entity_type": "company"},
    "luma_ai": {"name": "Luma AI", "handle": "@luma_ai", "role": "Dream Machine 视频与 3D 智能体", "avatar": "https://unavatar.io/x/luma_ai", "platform": "x", "entity_type": "company"},
    "luma ai": {"name": "Luma AI", "handle": "@luma_ai", "role": "Dream Machine 视频与 3D 智能体", "avatar": "https://unavatar.io/x/luma_ai", "platform": "x", "entity_type": "company"},
    "pika_labs": {"name": "Pika", "handle": "@pika_labs", "role": "创新物理特效生成式视频先锋", "avatar": "https://unavatar.io/x/pika_labs", "platform": "x", "entity_type": "company"},
    "pika": {"name": "Pika", "handle": "@pika_labs", "role": "创新物理特效生成式视频先锋", "avatar": "https://unavatar.io/x/pika_labs", "platform": "x", "entity_type": "company"},
    "kling_ai": {"name": "Kling AI", "handle": "@Kling_ai", "role": "快手可灵多模态视频大模型官方", "avatar": "https://unavatar.io/x/Kling_ai", "platform": "x", "entity_type": "company"},
    "kling ai": {"name": "Kling AI", "handle": "@Kling_ai", "role": "快手可灵多模态视频大模型官方", "avatar": "https://unavatar.io/x/Kling_ai", "platform": "x", "entity_type": "company"},
    "hailuo_ai": {"name": "Hailuo AI 海螺", "handle": "@Hailuo_AI", "role": "MiniMax 旗下超高清影视级视频生成平台", "avatar": "https://unavatar.io/x/Hailuo_AI", "platform": "x", "entity_type": "company"},
    "hailuo ai 海螺": {"name": "Hailuo AI 海螺", "handle": "@Hailuo_AI", "role": "MiniMax 旗下超高清影视级视频生成平台", "avatar": "https://unavatar.io/x/Hailuo_AI", "platform": "x", "entity_type": "company"},
    "suno_ai_": {"name": "Suno", "handle": "@suno_ai_", "role": "广播级全能生成式 AI 音乐生成平台", "avatar": "https://unavatar.io/x/suno_ai_", "platform": "x", "entity_type": "company"},
    "suno": {"name": "Suno", "handle": "@suno_ai_", "role": "广播级全能生成式 AI 音乐生成平台", "avatar": "https://unavatar.io/x/suno_ai_", "platform": "x", "entity_type": "company"},
    "udio": {"name": "Udio", "handle": "@udio", "role": "高保真 AI 音质生成创作工坊", "avatar": "https://unavatar.io/x/udio", "platform": "x", "entity_type": "company"},
    "elevenlabsio": {"name": "ElevenLabs", "handle": "@elevenlabsio", "role": "多语种高保真语音合成与克隆独角兽", "avatar": "https://unavatar.io/x/elevenlabsio", "platform": "x", "entity_type": "company"},
    "elevenlabs": {"name": "ElevenLabs", "handle": "@elevenlabsio", "role": "多语种高保真语音合成与克隆独角兽", "avatar": "https://unavatar.io/x/elevenlabsio", "platform": "x", "entity_type": "company"},
    "cartesia_ai": {"name": "Cartesia", "handle": "@cartesia_ai", "role": "毫秒级超极速低延迟实时拟人语音模型", "avatar": "https://unavatar.io/x/cartesia_ai", "platform": "x", "entity_type": "company"},
    "cartesia": {"name": "Cartesia", "handle": "@cartesia_ai", "role": "毫秒级超极速低延迟实时拟人语音模型", "avatar": "https://unavatar.io/x/cartesia_ai", "platform": "x", "entity_type": "company"},
    "play_ht": {"name": "PlayHT", "handle": "@play_ht", "role": "专业级生成式语音与实时 Agent 通话平台", "avatar": "https://unavatar.io/x/play_ht", "platform": "x", "entity_type": "company"},
    "playht": {"name": "PlayHT", "handle": "@play_ht", "role": "专业级生成式语音与实时 Agent 通话平台", "avatar": "https://unavatar.io/x/play_ht", "platform": "x", "entity_type": "company"},
    "ideogram_ai": {"name": "Ideogram", "handle": "@ideogram_ai", "role": "精准文本排版与写实渲染图像生成工具", "avatar": "https://unavatar.io/x/ideogram_ai", "platform": "x", "entity_type": "company"},
    "ideogram": {"name": "Ideogram", "handle": "@ideogram_ai", "role": "精准文本排版与写实渲染图像生成工具", "avatar": "https://unavatar.io/x/ideogram_ai", "platform": "x", "entity_type": "company"},
    "bfl_ml": {"name": "Black Forest Labs (FLUX)", "handle": "@bfl_ml", "role": "FLUX 系列开源文生图模型原创研发团队", "avatar": "https://unavatar.io/x/bfl_ml", "platform": "x", "entity_type": "company"},
    "black forest labs (flux)": {"name": "Black Forest Labs (FLUX)", "handle": "@bfl_ml", "role": "FLUX 系列开源文生图模型原创研发团队", "avatar": "https://unavatar.io/x/bfl_ml", "platform": "x", "entity_type": "company"},
    "stabilityai": {"name": "Stability AI", "handle": "@StabilityAI", "role": "Stable Diffusion 与开源多模态基准", "avatar": "https://unavatar.io/x/StabilityAI", "platform": "x", "entity_type": "company"},
    "stability ai": {"name": "Stability AI", "handle": "@StabilityAI", "role": "Stable Diffusion 与开源多模态基准", "avatar": "https://unavatar.io/x/StabilityAI", "platform": "x", "entity_type": "company"},
    "recraftai": {"name": "Recraft", "handle": "@recraftai", "role": "无限画布无损矢量与品牌设计生成器", "avatar": "https://unavatar.io/x/recraftai", "platform": "x", "entity_type": "company"},
    "recraft": {"name": "Recraft", "handle": "@recraftai", "role": "无限画布无损矢量与品牌设计生成器", "avatar": "https://unavatar.io/x/recraftai", "platform": "x", "entity_type": "company"},
    "krea_ai": {"name": "Krea AI", "handle": "@krea_ai", "role": "实时画板生图与超分辨率画面增强神器", "avatar": "https://unavatar.io/x/krea_ai", "platform": "x", "entity_type": "company"},
    "krea ai": {"name": "Krea AI", "handle": "@krea_ai", "role": "实时画板生图与超分辨率画面增强神器", "avatar": "https://unavatar.io/x/krea_ai", "platform": "x", "entity_type": "company"},
    "magnific_ai": {"name": "Magnific AI", "handle": "@Magnific_AI", "role": "超高清幻觉细节重塑与图像放大独角兽", "avatar": "https://unavatar.io/x/Magnific_AI", "platform": "x", "entity_type": "company"},
    "magnific ai": {"name": "Magnific AI", "handle": "@Magnific_AI", "role": "超高清幻觉细节重塑与图像放大独角兽", "avatar": "https://unavatar.io/x/Magnific_AI", "platform": "x", "entity_type": "company"},
    "leonardoai_": {"name": "Leonardo.Ai", "handle": "@LeonardoAi_", "role": "游戏资产与工业级创意图像套件", "avatar": "https://unavatar.io/x/LeonardoAi_", "platform": "x", "entity_type": "company"},
    "leonardo.ai": {"name": "Leonardo.Ai", "handle": "@LeonardoAi_", "role": "游戏资产与工业级创意图像套件", "avatar": "https://unavatar.io/x/LeonardoAi_", "platform": "x", "entity_type": "company"},
    "civitai": {"name": "Civitai", "handle": "@Civitai", "role": "全球最大开源扩散模型与 LoRA 社区枢纽", "avatar": "https://unavatar.io/x/Civitai", "platform": "x", "entity_type": "company"},
    "meshyai": {"name": "Meshy 3D", "handle": "@MeshyAI", "role": "文本/图像一键生成高质量 3D 网格模型", "avatar": "https://unavatar.io/x/MeshyAI", "platform": "x", "entity_type": "company"},
    "meshy 3d": {"name": "Meshy 3D", "handle": "@MeshyAI", "role": "文本/图像一键生成高质量 3D 网格模型", "avatar": "https://unavatar.io/x/MeshyAI", "platform": "x", "entity_type": "company"},
    "tripoai": {"name": "Tripo 3D", "handle": "@TripoAI", "role": "秒级高质量 3D 几何建模生成平台", "avatar": "https://unavatar.io/x/TripoAI", "platform": "x", "entity_type": "company"},
    "tripo 3d": {"name": "Tripo 3D", "handle": "@TripoAI", "role": "秒级高质量 3D 几何建模生成平台", "avatar": "https://unavatar.io/x/TripoAI", "platform": "x", "entity_type": "company"},
    "hedra_labs": {"name": "Hedra", "handle": "@hedra_labs", "role": "高情感表达数字人视频生成平台 Character-1", "avatar": "https://unavatar.io/x/hedra_labs", "platform": "x", "entity_type": "company"},
    "hedra": {"name": "Hedra", "handle": "@hedra_labs", "role": "高情感表达数字人视频生成平台 Character-1", "avatar": "https://unavatar.io/x/hedra_labs", "platform": "x", "entity_type": "company"},
    "heygen_official": {"name": "HeyGen", "handle": "@HeyGen_Official", "role": "全球出海数字人视频营销生成独角兽", "avatar": "https://unavatar.io/x/HeyGen_Official", "platform": "x", "entity_type": "company"},
    "heygen": {"name": "HeyGen", "handle": "@HeyGen_Official", "role": "全球出海数字人视频营销生成独角兽", "avatar": "https://unavatar.io/x/HeyGen_Official", "platform": "x", "entity_type": "company"},
    "synthesiaio": {"name": "Synthesia", "handle": "@synthesiaIO", "role": "企业级虚拟演播厅与培训数字人平台", "avatar": "https://unavatar.io/x/synthesiaIO", "platform": "x", "entity_type": "company"},
    "synthesia": {"name": "Synthesia", "handle": "@synthesiaIO", "role": "企业级虚拟演播厅与培训数字人平台", "avatar": "https://unavatar.io/x/synthesiaIO", "platform": "x", "entity_type": "company"},
    "perplexity_ai": {"name": "Perplexity", "handle": "@perplexity_ai", "role": "全球下一代对话式智能搜索引擎", "avatar": "https://unavatar.io/x/perplexity_ai", "platform": "x", "entity_type": "company"},
    "perplexity": {"name": "Perplexity", "handle": "@perplexity_ai", "role": "全球下一代对话式智能搜索引擎", "avatar": "https://unavatar.io/x/perplexity_ai", "platform": "x", "entity_type": "company"},
    "character_ai": {"name": "Character.ai", "handle": "@character_ai", "role": "高互动沉浸式 AI 智能体社交平台", "avatar": "https://unavatar.io/x/character_ai", "platform": "x", "entity_type": "company"},
    "character.ai": {"name": "Character.ai", "handle": "@character_ai", "role": "高互动沉浸式 AI 智能体社交平台", "avatar": "https://unavatar.io/x/character_ai", "platform": "x", "entity_type": "company"},
    "notionhq": {"name": "Notion AI", "handle": "@NotionHQ", "role": "全功能智能工作区与企业知识库大脑", "avatar": "https://unavatar.io/notion", "platform": "x", "entity_type": "company"},
    "notion ai": {"name": "Notion AI", "handle": "@NotionHQ", "role": "全功能智能工作区与企业知识库大脑", "avatar": "https://unavatar.io/notion", "platform": "x", "entity_type": "company"},
    "poe_platform": {"name": "Poe by Quora", "handle": "@poe_platform", "role": "多模型集成对话与智能体变现平台", "avatar": "https://unavatar.io/x/poe_platform", "platform": "x", "entity_type": "company"},
    "poe by quora": {"name": "Poe by Quora", "handle": "@poe_platform", "role": "多模型集成对话与智能体变现平台", "avatar": "https://unavatar.io/x/poe_platform", "platform": "x", "entity_type": "company"},
    "genspark_ai": {"name": "Genspark", "handle": "@genspark_ai", "role": "自主智能体并行聚合深度搜索页面 Sparkpages", "avatar": "https://unavatar.io/x/genspark_ai", "platform": "x", "entity_type": "company"},
    "genspark": {"name": "Genspark", "handle": "@genspark_ai", "role": "自主智能体并行聚合深度搜索页面 Sparkpages", "avatar": "https://unavatar.io/x/genspark_ai", "platform": "x", "entity_type": "company"},
    "yousearchengine": {"name": "You.com", "handle": "@YouSearchEngine", "role": "面向科研与工程的对话式生产力搜索引擎", "avatar": "https://unavatar.io/x/YouSearchEngine", "platform": "x", "entity_type": "company"},
    "you.com": {"name": "You.com", "handle": "@YouSearchEngine", "role": "面向科研与工程的对话式生产力搜索引擎", "avatar": "https://unavatar.io/x/YouSearchEngine", "platform": "x", "entity_type": "company"},
    "gleansearch": {"name": "Glean", "handle": "@GleanSearch", "role": "企业级全仓通用工作区智能工作流搜索大脑", "avatar": "https://unavatar.io/x/GleanSearch", "platform": "x", "entity_type": "company"},
    "glean": {"name": "Glean", "handle": "@GleanSearch", "role": "企业级全仓通用工作区智能工作流搜索大脑", "avatar": "https://unavatar.io/x/GleanSearch", "platform": "x", "entity_type": "company"},
    "harvey_ai": {"name": "Harvey AI", "handle": "@harvey_ai", "role": "全球顶级法律与专业咨询行业专属大模型平台", "avatar": "https://unavatar.io/x/harvey_ai", "platform": "x", "entity_type": "company"},
    "harvey ai": {"name": "Harvey AI", "handle": "@harvey_ai", "role": "全球顶级法律与专业咨询行业专属大模型平台", "avatar": "https://unavatar.io/x/harvey_ai", "platform": "x", "entity_type": "company"},
    "sierra_ai": {"name": "Sierra", "handle": "@sierra_ai", "role": "Bret Taylor 打造的企业级自主客服 AI 智能体", "avatar": "https://unavatar.io/x/sierra_ai", "platform": "x", "entity_type": "company"},
    "sierra": {"name": "Sierra", "handle": "@sierra_ai", "role": "Bret Taylor 打造的企业级自主客服 AI 智能体", "avatar": "https://unavatar.io/x/sierra_ai", "platform": "x", "entity_type": "company"},
    "decagon_ai": {"name": "Decagon", "handle": "@decagon_ai", "role": "颠覆传统呼叫中心的自主 AI 客服智能体", "avatar": "https://unavatar.io/x/decagon_ai", "platform": "x", "entity_type": "company"},
    "decagon": {"name": "Decagon", "handle": "@decagon_ai", "role": "颠覆传统呼叫中心的自主 AI 客服智能体", "avatar": "https://unavatar.io/x/decagon_ai", "platform": "x", "entity_type": "company"},
    "clayrun": {"name": "Clay", "handle": "@clayrun", "role": "AI 驱动的销售自动化与全球企业数据智能匹配", "avatar": "https://unavatar.io/x/clayrun", "platform": "x", "entity_type": "company"},
    "clay": {"name": "Clay", "handle": "@clayrun", "role": "AI 驱动的销售自动化与全球企业数据智能匹配", "avatar": "https://unavatar.io/x/clayrun", "platform": "x", "entity_type": "company"},
    "heptabase": {"name": "Heptabase", "handle": "@heptabase", "role": "视觉化卡片白板与深度学习研究第二大脑", "avatar": "https://unavatar.io/x/heptabase", "platform": "x", "entity_type": "company"},
    "huggingface": {"name": "Hugging Face", "handle": "@huggingface", "role": "全球开源 AI 模型与数据集社区枢纽", "avatar": "https://unavatar.io/x/huggingface", "platform": "x", "entity_type": "company"},
    "hugging face": {"name": "Hugging Face", "handle": "@huggingface", "role": "全球开源 AI 模型与数据集社区枢纽", "avatar": "https://unavatar.io/x/huggingface", "platform": "x", "entity_type": "company"},
    "langchainai": {"name": "LangChain", "handle": "@LangChainAI", "role": "全球主流 AI Agent 与链式开发框架", "avatar": "https://unavatar.io/x/LangChainAI", "platform": "x", "entity_type": "company"},
    "langchain": {"name": "LangChain", "handle": "@LangChainAI", "role": "全球主流 AI Agent 与链式开发框架", "avatar": "https://unavatar.io/x/LangChainAI", "platform": "x", "entity_type": "company"},
    "llama_index": {"name": "LlamaIndex", "handle": "@llama_index", "role": "专业级 RAG 检索增强数据架构", "avatar": "https://unavatar.io/x/llama_index", "platform": "x", "entity_type": "company"},
    "llamaindex": {"name": "LlamaIndex", "handle": "@llama_index", "role": "专业级 RAG 检索增强数据架构", "avatar": "https://unavatar.io/x/llama_index", "platform": "x", "entity_type": "company"},
    "vllm_project": {"name": "vLLM Project", "handle": "@vllm_project", "role": "高通量、低内存显存极速推理架构", "avatar": "https://unavatar.io/x/vllm_project", "platform": "x", "entity_type": "company"},
    "vllm project": {"name": "vLLM Project", "handle": "@vllm_project", "role": "高通量、低内存显存极速推理架构", "avatar": "https://unavatar.io/x/vllm_project", "platform": "x", "entity_type": "company"},
    "ollama": {"name": "Ollama", "handle": "@ollama", "role": "极简本地大模型运行与管理框架", "avatar": "https://unavatar.io/x/ollama", "platform": "x", "entity_type": "company"},
    "lmstudioai": {"name": "LM Studio", "handle": "@LMStudioAI", "role": "优雅跨平台离线本地 LLM 探索与运行客户端", "avatar": "https://unavatar.io/x/LMStudioAI", "platform": "x", "entity_type": "company"},
    "lm studio": {"name": "LM Studio", "handle": "@LMStudioAI", "role": "优雅跨平台离线本地 LLM 探索与运行客户端", "avatar": "https://unavatar.io/x/LMStudioAI", "platform": "x", "entity_type": "company"},
    "jandotai": {"name": "Jan AI", "handle": "@jandotai", "role": "100% 离线隐私优先的开源 ChatGPT 替代客户端", "avatar": "https://unavatar.io/x/jandotai", "platform": "x", "entity_type": "company"},
    "jan ai": {"name": "Jan AI", "handle": "@jandotai", "role": "100% 离线隐私优先的开源 ChatGPT 替代客户端", "avatar": "https://unavatar.io/x/jandotai", "platform": "x", "entity_type": "company"},
    "sgl_project": {"name": "SGLang", "handle": "@sgl_project", "role": "多模型并发与复杂结构化推理编译引擎", "avatar": "https://unavatar.io/x/sgl_project", "platform": "x", "entity_type": "company"},
    "sglang": {"name": "SGLang", "handle": "@sgl_project", "role": "多模型并发与复杂结构化推理编译引擎", "avatar": "https://unavatar.io/x/sgl_project", "platform": "x", "entity_type": "company"},
    "unslothai": {"name": "Unsloth AI", "handle": "@UnslothAI", "role": "显存占用直降 80% 的开源大模型极速微调工具", "avatar": "https://unavatar.io/x/UnslothAI", "platform": "x", "entity_type": "company"},
    "unsloth ai": {"name": "Unsloth AI", "handle": "@UnslothAI", "role": "显存占用直降 80% 的开源大模型极速微调工具", "avatar": "https://unavatar.io/x/UnslothAI", "platform": "x", "entity_type": "company"},
    "crewaiinc": {"name": "CrewAI", "handle": "@crewAIInc", "role": "角色扮演型多智能体自动化协作团队框架", "avatar": "https://unavatar.io/x/crewAIInc", "platform": "x", "entity_type": "company"},
    "crewai": {"name": "CrewAI", "handle": "@crewAIInc", "role": "角色扮演型多智能体自动化协作团队框架", "avatar": "https://unavatar.io/x/crewAIInc", "platform": "x", "entity_type": "company"},
    "pyautogen": {"name": "AutoGen", "handle": "@pyautogen", "role": "微软多智能体复杂对话与任务编排系统", "avatar": "https://unavatar.io/x/pyautogen", "platform": "x", "entity_type": "company"},
    "autogen": {"name": "AutoGen", "handle": "@pyautogen", "role": "微软多智能体复杂对话与任务编排系统", "avatar": "https://unavatar.io/x/pyautogen", "platform": "x", "entity_type": "company"},
    "openinterpreter": {"name": "Open Interpreter", "handle": "@OpenInterpreter", "role": "允许大模型在本地电脑操作系统直接执行代码的交互工具", "avatar": "https://unavatar.io/x/OpenInterpreter", "platform": "x", "entity_type": "company"},
    "open interpreter": {"name": "Open Interpreter", "handle": "@OpenInterpreter", "role": "允许大模型在本地电脑操作系统直接执行代码的交互工具", "avatar": "https://unavatar.io/x/OpenInterpreter", "platform": "x", "entity_type": "company"},
    "dify_ai": {"name": "Dify.ai", "handle": "@dify_ai", "role": "开源下一代大模型应用与智能体工作流编排平台", "avatar": "https://unavatar.io/x/dify_ai", "platform": "x", "entity_type": "company"},
    "dify.ai": {"name": "Dify.ai", "handle": "@dify_ai", "role": "开源下一代大模型应用与智能体工作流编排平台", "avatar": "https://unavatar.io/x/dify_ai", "platform": "x", "entity_type": "company"},
    "lmsysorg": {"name": "LMSYS Org", "handle": "@lmsysorg", "role": "大语言模型盲测排行榜 Chatbot Arena 维护机构", "avatar": "https://unavatar.io/x/lmsysorg", "platform": "x", "entity_type": "company"},
    "lmsys org": {"name": "LMSYS Org", "handle": "@lmsysorg", "role": "大语言模型盲测排行榜 Chatbot Arena 维护机构", "avatar": "https://unavatar.io/x/lmsysorg", "platform": "x", "entity_type": "company"},
    "artificialanlys": {"name": "Artificial Analysis", "handle": "@ArtificialAnlys", "role": "独立第三方大模型速度、性价比与智能基准盲测", "avatar": "https://unavatar.io/x/ArtificialAnlys", "platform": "x", "entity_type": "company"},
    "artificial analysis": {"name": "Artificial Analysis", "handle": "@ArtificialAnlys", "role": "独立第三方大模型速度、性价比与智能基准盲测", "avatar": "https://unavatar.io/x/ArtificialAnlys", "platform": "x", "entity_type": "company"},
    "scale_ai": {"name": "Scale AI", "handle": "@scale_ai", "role": "前沿模型数据训练与严苛基准评测", "avatar": "https://unavatar.io/x/scale_ai", "platform": "x", "entity_type": "company"},
    "scale ai": {"name": "Scale AI", "handle": "@scale_ai", "role": "前沿模型数据训练与严苛基准评测", "avatar": "https://unavatar.io/x/scale_ai", "platform": "x", "entity_type": "company"},
    "weights_biases": {"name": "Weights & Biases", "handle": "@weights_biases", "role": "机器学习实验追踪与大模型监控平台", "avatar": "https://unavatar.io/x/weights_biases", "platform": "x", "entity_type": "company"},
    "weights & biases": {"name": "Weights & Biases", "handle": "@weights_biases", "role": "机器学习实验追踪与大模型监控平台", "avatar": "https://unavatar.io/x/weights_biases", "platform": "x", "entity_type": "company"},
    "pinecone": {"name": "Pinecone", "handle": "@pinecone", "role": "云原生高并发生产级向量数据库", "avatar": "https://unavatar.io/x/pinecone", "platform": "x", "entity_type": "company"},
    "weaviate_io": {"name": "Weaviate", "handle": "@weaviate_io", "role": "开源模块化多模态混合搜索向量数据库", "avatar": "https://unavatar.io/x/weaviate_io", "platform": "x", "entity_type": "company"},
    "weaviate": {"name": "Weaviate", "handle": "@weaviate_io", "role": "开源模块化多模态混合搜索向量数据库", "avatar": "https://unavatar.io/x/weaviate_io", "platform": "x", "entity_type": "company"},
    "qdrant_engine": {"name": "Qdrant", "handle": "@qdrant_engine", "role": "Rust 打造的高性能生产级向量搜索引擎", "avatar": "https://unavatar.io/x/qdrant_engine", "platform": "x", "entity_type": "company"},
    "qdrant": {"name": "Qdrant", "handle": "@qdrant_engine", "role": "Rust 打造的高性能生产级向量搜索引擎", "avatar": "https://unavatar.io/x/qdrant_engine", "platform": "x", "entity_type": "company"},
    "milvusio": {"name": "Milvus", "handle": "@milvusio", "role": "超十亿级规模开源分布式向量数据库", "avatar": "https://unavatar.io/x/milvusio", "platform": "x", "entity_type": "company"},
    "milvus": {"name": "Milvus", "handle": "@milvusio", "role": "超十亿级规模开源分布式向量数据库", "avatar": "https://unavatar.io/x/milvusio", "platform": "x", "entity_type": "company"},
    "trychroma": {"name": "Chroma", "handle": "@trychroma", "role": "AI 原生嵌入式极简轻量开源向量库", "avatar": "https://unavatar.io/x/trychroma", "platform": "x", "entity_type": "company"},
    "chroma": {"name": "Chroma", "handle": "@trychroma", "role": "AI 原生嵌入式极简轻量开源向量库", "avatar": "https://unavatar.io/x/trychroma", "platform": "x", "entity_type": "company"},

    # =========================================================================
    # 👤 行业领袖、顶流科学家与创始人 (100+ 位全球大V，严格标记 person)
    # =========================================================================
    "sama": {"name": "Sam Altman", "handle": "@sama", "role": "OpenAI CEO", "avatar": "https://unavatar.io/x/sama", "platform": "x", "entity_type": "person"},
    "sam altman": {"name": "Sam Altman", "handle": "@sama", "role": "OpenAI CEO", "avatar": "https://unavatar.io/x/sama", "platform": "x", "entity_type": "person"},
    "gdb": {"name": "Greg Brockman", "handle": "@gdb", "role": "OpenAI 总裁兼联合创始人", "avatar": "https://unavatar.io/x/gdb", "platform": "x", "entity_type": "person"},
    "greg brockman": {"name": "Greg Brockman", "handle": "@gdb", "role": "OpenAI 总裁兼联合创始人", "avatar": "https://unavatar.io/x/gdb", "platform": "x", "entity_type": "person"},
    "miramurati": {"name": "Mira Murati", "handle": "@miramurati", "role": "前 OpenAI CTO / 前沿实验室创始人", "avatar": "https://unavatar.io/x/miramurati", "platform": "x", "entity_type": "person"},
    "mira murati": {"name": "Mira Murati", "handle": "@miramurati", "role": "前 OpenAI CTO / 前沿实验室创始人", "avatar": "https://unavatar.io/x/miramurati", "platform": "x", "entity_type": "person"},
    "satyanadella": {"name": "Satya Nadella", "handle": "@satyanadella", "role": "微软董事长兼 CEO", "avatar": "https://unavatar.io/x/satyanadella", "platform": "x", "entity_type": "person"},
    "satya nadella": {"name": "Satya Nadella", "handle": "@satyanadella", "role": "微软董事长兼 CEO", "avatar": "https://unavatar.io/x/satyanadella", "platform": "x", "entity_type": "person"},
    "elonmusk": {"name": "Elon Musk", "handle": "@elonmusk", "role": "xAI 创始人 / 特斯拉 CEO", "avatar": "https://unavatar.io/x/elonmusk", "platform": "x", "entity_type": "person"},
    "elon musk": {"name": "Elon Musk", "handle": "@elonmusk", "role": "xAI 创始人 / 特斯拉 CEO", "avatar": "https://unavatar.io/x/elonmusk", "platform": "x", "entity_type": "person"},
    "finkd": {"name": "Mark Zuckerberg", "handle": "@finkd", "role": "Meta CEO / 开源大模型战略推手", "avatar": "https://unavatar.io/x/finkd", "platform": "x", "entity_type": "person"},
    "mark zuckerberg": {"name": "Mark Zuckerberg", "handle": "@finkd", "role": "Meta CEO / 开源大模型战略推手", "avatar": "https://unavatar.io/x/finkd", "platform": "x", "entity_type": "person"},
    "sundarpichai": {"name": "Sundar Pichai", "handle": "@sundarpichai", "role": "Alphabet 与 Google CEO", "avatar": "https://unavatar.io/x/sundarpichai", "platform": "x", "entity_type": "person"},
    "sundar pichai": {"name": "Sundar Pichai", "handle": "@sundarpichai", "role": "Alphabet 与 Google CEO", "avatar": "https://unavatar.io/x/sundarpichai", "platform": "x", "entity_type": "person"},
    "demishassabis": {"name": "Demis Hassabis", "handle": "@demishassabis", "role": "Google DeepMind CEO / 诺贝尔化学奖得主", "avatar": "https://unavatar.io/x/demishassabis", "platform": "x", "entity_type": "person"},
    "demis hassabis": {"name": "Demis Hassabis", "handle": "@demishassabis", "role": "Google DeepMind CEO / 诺贝尔化学奖得主", "avatar": "https://unavatar.io/x/demishassabis", "platform": "x", "entity_type": "person"},
    "anthropic_dario": {"name": "Dario Amodei", "handle": "@AnthropicAI", "role": "Anthropic CEO 兼联合创始人", "avatar": "https://unavatar.io/anthropic", "platform": "x", "entity_type": "person"},
    "dario amodei": {"name": "Dario Amodei", "handle": "@AnthropicAI", "role": "Anthropic CEO 兼联合创始人", "avatar": "https://unavatar.io/anthropic", "platform": "x", "entity_type": "person"},
    "danielaamodei": {"name": "Daniela Amodei", "handle": "@DanielaAmodei", "role": "Anthropic 总裁兼联合创始人", "avatar": "https://unavatar.io/x/DanielaAmodei", "platform": "x", "entity_type": "person"},
    "daniela amodei": {"name": "Daniela Amodei", "handle": "@DanielaAmodei", "role": "Anthropic 总裁兼联合创始人", "avatar": "https://unavatar.io/x/DanielaAmodei", "platform": "x", "entity_type": "person"},
    "arthurmensch": {"name": "Arthur Mensch", "handle": "@arthurmensch", "role": "Mistral AI CEO 兼联合创始人", "avatar": "https://unavatar.io/x/arthurmensch", "platform": "x", "entity_type": "person"},
    "arthur mensch": {"name": "Arthur Mensch", "handle": "@arthurmensch", "role": "Mistral AI CEO 兼联合创始人", "avatar": "https://unavatar.io/x/arthurmensch", "platform": "x", "entity_type": "person"},
    "aravsrinivas": {"name": "Aravind Srinivas", "handle": "@AravSrinivas", "role": "Perplexity AI CEO", "avatar": "https://unavatar.io/x/AravSrinivas", "platform": "x", "entity_type": "person"},
    "aravind srinivas": {"name": "Aravind Srinivas", "handle": "@AravSrinivas", "role": "Perplexity AI CEO", "avatar": "https://unavatar.io/x/AravSrinivas", "platform": "x", "entity_type": "person"},
    "alexandr_wang": {"name": "Alexandr Wang", "handle": "@alexandr_wang", "role": "Scale AI CEO 兼创始人", "avatar": "https://unavatar.io/x/alexandr_wang", "platform": "x", "entity_type": "person"},
    "alexandr wang": {"name": "Alexandr Wang", "handle": "@alexandr_wang", "role": "Scale AI CEO 兼创始人", "avatar": "https://unavatar.io/x/alexandr_wang", "platform": "x", "entity_type": "person"},
    "mustafasuleyman": {"name": "Mustafa Suleyman", "handle": "@mustafasuleyman", "role": "Microsoft AI CEO / Inflection 联合创始人", "avatar": "https://unavatar.io/x/mustafasuleyman", "platform": "x", "entity_type": "person"},
    "mustafa suleyman": {"name": "Mustafa Suleyman", "handle": "@mustafasuleyman", "role": "Microsoft AI CEO / Inflection 联合创始人", "avatar": "https://unavatar.io/x/mustafasuleyman", "platform": "x", "entity_type": "person"},
    "aidangomez": {"name": "Aidan Gomez", "handle": "@aidangomez", "role": "Cohere CEO / Transformer 架构联合作者", "avatar": "https://unavatar.io/x/aidangomez", "platform": "x", "entity_type": "person"},
    "aidan gomez": {"name": "Aidan Gomez", "handle": "@aidangomez", "role": "Cohere CEO / Transformer 架构联合作者", "avatar": "https://unavatar.io/x/aidangomez", "platform": "x", "entity_type": "person"},
    "d_luan": {"name": "David Luan", "handle": "@d_luan", "role": "Adept AI 创始人 / 前 OpenAI 研究副总", "avatar": "https://unavatar.io/x/d_luan", "platform": "x", "entity_type": "person"},
    "david luan": {"name": "David Luan", "handle": "@d_luan", "role": "Adept AI 创始人 / 前 OpenAI 研究副总", "avatar": "https://unavatar.io/x/d_luan", "platform": "x", "entity_type": "person"},
    "noamshazeer": {"name": "Noam Shazeer", "handle": "@NoamShazeer", "role": "Google 卓越副总 / Character.ai 创始人 / Transformer 奠基作者", "avatar": "https://unavatar.io/x/NoamShazeer", "platform": "x", "entity_type": "person"},
    "noam shazeer": {"name": "Noam Shazeer", "handle": "@NoamShazeer", "role": "Google 卓越副总 / Character.ai 创始人 / Transformer 奠基作者", "avatar": "https://unavatar.io/x/NoamShazeer", "platform": "x", "entity_type": "person"},
    "liangwenfeng": {"name": "梁文锋", "handle": "@deepseek_ai", "role": "DeepSeek 深度求索创始人兼 CEO", "avatar": "https://unavatar.io/github/deepseek-ai", "platform": "x", "entity_type": "person"},
    "梁文锋": {"name": "梁文锋", "handle": "@deepseek_ai", "role": "DeepSeek 深度求索创始人兼 CEO", "avatar": "https://unavatar.io/github/deepseek-ai", "platform": "x", "entity_type": "person"},
    "yangzhilin": {"name": "杨植麟", "handle": "@MoonshotAI", "role": "月之暗面 Kimi 创始人兼 CEO", "avatar": "https://unavatar.io/x/MoonshotAI", "platform": "x", "entity_type": "person"},
    "杨植麟": {"name": "杨植麟", "handle": "@MoonshotAI", "role": "月之暗面 Kimi 创始人兼 CEO", "avatar": "https://unavatar.io/x/MoonshotAI", "platform": "x", "entity_type": "person"},
    "yanjunjie": {"name": "闫俊杰", "handle": "@MiniMax_AI", "role": "MiniMax 创始人兼 CEO", "avatar": "https://unavatar.io/x/MiniMax_AI", "platform": "x", "entity_type": "person"},
    "闫俊杰": {"name": "闫俊杰", "handle": "@MiniMax_AI", "role": "MiniMax 创始人兼 CEO", "avatar": "https://unavatar.io/x/MiniMax_AI", "platform": "x", "entity_type": "person"},
    "ylecun": {"name": "Yann LeCun", "handle": "@ylecun", "role": "Meta 首席AI科学家 / 深度学习三巨头 / 图灵奖得主", "avatar": "https://unavatar.io/x/ylecun", "platform": "x", "entity_type": "person"},
    "yann lecun": {"name": "Yann LeCun", "handle": "@ylecun", "role": "Meta 首席AI科学家 / 深度学习三巨头 / 图灵奖得主", "avatar": "https://unavatar.io/x/ylecun", "platform": "x", "entity_type": "person"},
    "geoffreyhinton": {"name": "Geoffrey Hinton", "handle": "@geoffreyhinton", "role": "深度学习之父 / 诺贝尔物理学奖与图灵奖得主", "avatar": "https://unavatar.io/x/geoffreyhinton", "platform": "x", "entity_type": "person"},
    "geoffrey hinton": {"name": "Geoffrey Hinton", "handle": "@geoffreyhinton", "role": "深度学习之父 / 诺贝尔物理学奖与图灵奖得主", "avatar": "https://unavatar.io/x/geoffreyhinton", "platform": "x", "entity_type": "person"},
    "yoshuabengio": {"name": "Yoshua Bengio", "handle": "@yoshuabengio", "role": "深度学习三巨头 / 蒙特利尔大学教授 / 图灵奖得主", "avatar": "https://unavatar.io/x/yoshuabengio", "platform": "x", "entity_type": "person"},
    "yoshua bengio": {"name": "Yoshua Bengio", "handle": "@yoshuabengio", "role": "深度学习三巨头 / 蒙特利尔大学教授 / 图灵奖得主", "avatar": "https://unavatar.io/x/yoshuabengio", "platform": "x", "entity_type": "person"},
    "andrewyng": {"name": "Andrew Ng 吴恩达", "handle": "@AndrewYNg", "role": "Landing AI 创始人 / 斯坦福客座教授 / Coursera 联创", "avatar": "https://unavatar.io/x/AndrewYNg", "platform": "x", "entity_type": "person"},
    "andrew ng 吴恩达": {"name": "Andrew Ng 吴恩达", "handle": "@AndrewYNg", "role": "Landing AI 创始人 / 斯坦福客座教授 / Coursera 联创", "avatar": "https://unavatar.io/x/AndrewYNg", "platform": "x", "entity_type": "person"},
    "drfeifei": {"name": "Fei-Fei Li 李飞飞", "handle": "@drfeifei", "role": "World Labs 联合创始人 / ImageNet 之母 / 斯坦福教授", "avatar": "https://unavatar.io/x/drfeifei", "platform": "x", "entity_type": "person"},
    "fei-fei li 李飞飞": {"name": "Fei-Fei Li 李飞飞", "handle": "@drfeifei", "role": "World Labs 联合创始人 / ImageNet 之母 / 斯坦福教授", "avatar": "https://unavatar.io/x/drfeifei", "platform": "x", "entity_type": "person"},
    "richardssutton": {"name": "Richard S. Sutton", "handle": "@RichardSSutton", "role": "强化学习之父 / The Bitter Lesson 提出者", "avatar": "https://unavatar.io/x/RichardSSutton", "platform": "x", "entity_type": "person"},
    "richard s. sutton": {"name": "Richard S. Sutton", "handle": "@RichardSSutton", "role": "强化学习之父 / The Bitter Lesson 提出者", "avatar": "https://unavatar.io/x/RichardSSutton", "platform": "x", "entity_type": "person"},
    "yudapearl": {"name": "Judea Pearl", "handle": "@yudapearl", "role": "因果推理之父 / 图灵奖得主", "avatar": "https://unavatar.io/x/yudapearl", "platform": "x", "entity_type": "person"},
    "judea pearl": {"name": "Judea Pearl", "handle": "@yudapearl", "role": "因果推理之父 / 图灵奖得主", "avatar": "https://unavatar.io/x/yudapearl", "platform": "x", "entity_type": "person"},
    "drdavidbaker": {"name": "David Baker", "handle": "@drdavidbaker", "role": "计算蛋白质设计先驱 / 诺贝尔化学奖得主", "avatar": "https://unavatar.io/x/drdavidbaker", "platform": "x", "entity_type": "person"},
    "david baker": {"name": "David Baker", "handle": "@drdavidbaker", "role": "计算蛋白质设计先驱 / 诺贝尔化学奖得主", "avatar": "https://unavatar.io/x/drdavidbaker", "platform": "x", "entity_type": "person"},
    "ilyasut": {"name": "Ilya Sutskever", "handle": "@ilyasut", "role": "SSI 联合创始人 / 前 OpenAI 首席科学家", "avatar": "https://unavatar.io/x/ilyasut", "platform": "x", "entity_type": "person"},
    "ilya sutskever": {"name": "Ilya Sutskever", "handle": "@ilyasut", "role": "SSI 联合创始人 / 前 OpenAI 首席科学家", "avatar": "https://unavatar.io/x/ilyasut", "platform": "x", "entity_type": "person"},
    "karpathy": {"name": "Andrej Karpathy", "handle": "@karpathy", "role": "Eureka Labs 创始人 / 前特斯拉 AI 总监与 OpenAI 科学家", "avatar": "https://unavatar.io/x/karpathy", "platform": "x", "entity_type": "person"},
    "andrej karpathy": {"name": "Andrej Karpathy", "handle": "@karpathy", "role": "Eureka Labs 创始人 / 前特斯拉 AI 总监与 OpenAI 科学家", "avatar": "https://unavatar.io/x/karpathy", "platform": "x", "entity_type": "person"},
    "jeffdean": {"name": "Jeff Dean", "handle": "@JeffDean", "role": "Google 首席科学家 / 系统架构与分布式泰斗", "avatar": "https://unavatar.io/x/JeffDean", "platform": "x", "entity_type": "person"},
    "jeff dean": {"name": "Jeff Dean", "handle": "@JeffDean", "role": "Google 首席科学家 / 系统架构与分布式泰斗", "avatar": "https://unavatar.io/x/JeffDean", "platform": "x", "entity_type": "person"},
    "oriolvinyalsml": {"name": "Oriol Vinyals", "handle": "@OriolVinyalsML", "role": "Google DeepMind 研究副总裁 / Gemini 主架构师", "avatar": "https://unavatar.io/x/OriolVinyalsML", "platform": "x", "entity_type": "person"},
    "oriol vinyals": {"name": "Oriol Vinyals", "handle": "@OriolVinyalsML", "role": "Google DeepMind 研究副总裁 / Gemini 主架构师", "avatar": "https://unavatar.io/x/OriolVinyalsML", "platform": "x", "entity_type": "person"},
    "polynoamial": {"name": "Noam Brown", "handle": "@polynoamial", "role": "OpenAI 推理与 o1/o3/o4 核心负责人", "avatar": "https://unavatar.io/x/polynoamial", "platform": "x", "entity_type": "person"},
    "noam brown": {"name": "Noam Brown", "handle": "@polynoamial", "role": "OpenAI 推理与 o1/o3/o4 核心负责人", "avatar": "https://unavatar.io/x/polynoamial", "platform": "x", "entity_type": "person"},
    "_jasonwei": {"name": "Jason Wei", "handle": "@_jasonwei", "role": "OpenAI 核心研究员 / 思维链 (CoT) 与涌现能力提出者", "avatar": "https://unavatar.io/x/_jasonwei", "platform": "x", "entity_type": "person"},
    "jason wei": {"name": "Jason Wei", "handle": "@_jasonwei", "role": "OpenAI 核心研究员 / 思维链 (CoT) 与涌现能力提出者", "avatar": "https://unavatar.io/x/_jasonwei", "platform": "x", "entity_type": "person"},
    "markchen90": {"name": "Mark Chen", "handle": "@markchen90", "role": "OpenAI 研究高级副总裁", "avatar": "https://unavatar.io/x/markchen90", "platform": "x", "entity_type": "person"},
    "mark chen": {"name": "Mark Chen", "handle": "@markchen90", "role": "OpenAI 研究高级副总裁", "avatar": "https://unavatar.io/x/markchen90", "platform": "x", "entity_type": "person"},
    "woj_zaremba": {"name": "Wojciech Zaremba", "handle": "@woj_zaremba", "role": "OpenAI 联合创始人", "avatar": "https://unavatar.io/x/woj_zaremba", "platform": "x", "entity_type": "person"},
    "wojciech zaremba": {"name": "Wojciech Zaremba", "handle": "@woj_zaremba", "role": "OpenAI 联合创始人", "avatar": "https://unavatar.io/x/woj_zaremba", "platform": "x", "entity_type": "person"},
    "johnschulman2": {"name": "John Schulman", "handle": "@johnschulman2", "role": "PPO/RLHF 强化学习奠基人 / Anthropic 科学家", "avatar": "https://unavatar.io/x/johnschulman2", "platform": "x", "entity_type": "person"},
    "john schulman": {"name": "John Schulman", "handle": "@johnschulman2", "role": "PPO/RLHF 强化学习奠基人 / Anthropic 科学家", "avatar": "https://unavatar.io/x/johnschulman2", "platform": "x", "entity_type": "person"},
    "amandaaskell": {"name": "Amanda Askell", "handle": "@AmandaAskell", "role": "Anthropic 对齐与 AI 性格哲学负责人", "avatar": "https://unavatar.io/x/AmandaAskell", "platform": "x", "entity_type": "person"},
    "amanda askell": {"name": "Amanda Askell", "handle": "@AmandaAskell", "role": "Anthropic 对齐与 AI 性格哲学负责人", "avatar": "https://unavatar.io/x/AmandaAskell", "platform": "x", "entity_type": "person"},
    "ch402": {"name": "Chris Olah", "handle": "@ch402", "role": "Anthropic 联合创始人 / 神经网络可解释性先驱", "avatar": "https://unavatar.io/x/ch402", "platform": "x", "entity_type": "person"},
    "chris olah": {"name": "Chris Olah", "handle": "@ch402", "role": "Anthropic 联合创始人 / 神经网络可解释性先驱", "avatar": "https://unavatar.io/x/ch402", "platform": "x", "entity_type": "person"},
    "jackclarksf": {"name": "Jack Clark", "handle": "@jackclarkSF", "role": "Anthropic 联合创始人 / 前 OpenAI 通信与 AI Policy", "avatar": "https://unavatar.io/x/jackclarkSF", "platform": "x", "entity_type": "person"},
    "jack clark": {"name": "Jack Clark", "handle": "@jackclarkSF", "role": "Anthropic 联合创始人 / 前 OpenAI 通信与 AI Policy", "avatar": "https://unavatar.io/x/jackclarkSF", "platform": "x", "entity_type": "person"},
    "drjimfan": {"name": "Jim Fan 范麟熙", "handle": "@DrJimFan", "role": "NVIDIA AI Agent / 具身智能实验室负责人", "avatar": "https://unavatar.io/x/DrJimFan", "platform": "x", "entity_type": "person"},
    "jim fan 范麟熙": {"name": "Jim Fan 范麟熙", "handle": "@DrJimFan", "role": "NVIDIA AI Agent / 具身智能实验室负责人", "avatar": "https://unavatar.io/x/DrJimFan", "platform": "x", "entity_type": "person"},
    "fchollet": {"name": "François Chollet", "handle": "@fchollet", "role": "ARC-AGI 创始人 / Keras 作者", "avatar": "https://unavatar.io/x/fchollet", "platform": "x", "entity_type": "person"},
    "françois chollet": {"name": "François Chollet", "handle": "@fchollet", "role": "ARC-AGI 创始人 / Keras 作者", "avatar": "https://unavatar.io/x/fchollet", "platform": "x", "entity_type": "person"},
    "percyliang": {"name": "Percy Liang", "handle": "@percyliang", "role": "斯坦福基础模型中心主任 / HELM 评测发起人", "avatar": "https://unavatar.io/x/percyliang", "platform": "x", "entity_type": "person"},
    "percy liang": {"name": "Percy Liang", "handle": "@percyliang", "role": "斯坦福基础模型中心主任 / HELM 评测发起人", "avatar": "https://unavatar.io/x/percyliang", "platform": "x", "entity_type": "person"},
    "pabbeel": {"name": "Pieter Abbeel", "handle": "@pabbeel", "role": "UC 伯克利机器人实验室教授 / 强化学习泰斗", "avatar": "https://unavatar.io/x/pabbeel", "platform": "x", "entity_type": "person"},
    "pieter abbeel": {"name": "Pieter Abbeel", "handle": "@pabbeel", "role": "UC 伯克利机器人实验室教授 / 强化学习泰斗", "avatar": "https://unavatar.io/x/pabbeel", "platform": "x", "entity_type": "person"},
    "svlevine": {"name": "Sergey Levine", "handle": "@svlevine", "role": "UC 伯克利机器人与离线强化学习权威", "avatar": "https://unavatar.io/x/svlevine", "platform": "x", "entity_type": "person"},
    "sergey levine": {"name": "Sergey Levine", "handle": "@svlevine", "role": "UC 伯克利机器人与离线强化学习权威", "avatar": "https://unavatar.io/x/svlevine", "platform": "x", "entity_type": "person"},
    "chelseabfinn": {"name": "Chelsea Finn", "handle": "@chelseabfinn", "role": "斯坦福大学元学习与具身智能教授", "avatar": "https://unavatar.io/x/chelseabfinn", "platform": "x", "entity_type": "person"},
    "chelsea finn": {"name": "Chelsea Finn", "handle": "@chelseabfinn", "role": "斯坦福大学元学习与具身智能教授", "avatar": "https://unavatar.io/x/chelseabfinn", "platform": "x", "entity_type": "person"},
    "chrmanning": {"name": "Christopher Manning", "handle": "@chrmanning", "role": "斯坦福 NLP 泰斗 / GloVe 与句法分析奠基人", "avatar": "https://unavatar.io/x/chrmanning", "platform": "x", "entity_type": "person"},
    "christopher manning": {"name": "Christopher Manning", "handle": "@chrmanning", "role": "斯坦福 NLP 泰斗 / GloVe 与句法分析奠基人", "avatar": "https://unavatar.io/x/chrmanning", "platform": "x", "entity_type": "person"},
    "danqic": {"name": "Danqi Chen 陈丹琦", "handle": "@danqic", "role": "普林斯顿大学 NLP 教授 / Dense Retrieval 先驱", "avatar": "https://unavatar.io/x/danqic", "platform": "x", "entity_type": "person"},
    "danqi chen 陈丹琦": {"name": "Danqi Chen 陈丹琦", "handle": "@danqic", "role": "普林斯顿大学 NLP 教授 / Dense Retrieval 先驱", "avatar": "https://unavatar.io/x/danqic", "platform": "x", "entity_type": "person"},
    "officiallogank": {"name": "Logan Kilpatrick", "handle": "@OfficialLoganK", "role": "Google AI Studio 负责人 / 前 OpenAI 开发者布道主管", "avatar": "https://unavatar.io/x/OfficialLoganK", "platform": "x", "entity_type": "person"},
    "logan kilpatrick": {"name": "Logan Kilpatrick", "handle": "@OfficialLoganK", "role": "Google AI Studio 负责人 / 前 OpenAI 开发者布道主管", "avatar": "https://unavatar.io/x/OfficialLoganK", "platform": "x", "entity_type": "person"},
    "npew": {"name": "Peter Welinder", "handle": "@npew", "role": "OpenAI 产品副总裁", "avatar": "https://unavatar.io/x/npew", "platform": "x", "entity_type": "person"},
    "peter welinder": {"name": "Peter Welinder", "handle": "@npew", "role": "OpenAI 产品副总裁", "avatar": "https://unavatar.io/x/npew", "platform": "x", "entity_type": "person"},
    "danhendrycks": {"name": "Dan Hendrycks", "handle": "@DanHendrycks", "role": "CAIS AI 安全中心主任 / MMLU 基准测试发明人", "avatar": "https://unavatar.io/x/DanHendrycks", "platform": "x", "entity_type": "person"},
    "dan hendrycks": {"name": "Dan Hendrycks", "handle": "@DanHendrycks", "role": "CAIS AI 安全中心主任 / MMLU 基准测试发明人", "avatar": "https://unavatar.io/x/DanHendrycks", "platform": "x", "entity_type": "person"},
    "paul_christiano": {"name": "Paul Christiano", "handle": "@Paul_Christiano", "role": "对齐研究中心 (ARC) 创始人 / RLHF 原创发明者之一", "avatar": "https://unavatar.io/x/Paul_Christiano", "platform": "x", "entity_type": "person"},
    "paul christiano": {"name": "Paul Christiano", "handle": "@Paul_Christiano", "role": "对齐研究中心 (ARC) 创始人 / RLHF 原创发明者之一", "avatar": "https://unavatar.io/x/Paul_Christiano", "platform": "x", "entity_type": "person"},
    "janleike": {"name": "Jan Leike", "handle": "@janleike", "role": "Anthropic 对齐负责人 / 前 OpenAI 超级对齐主管", "avatar": "https://unavatar.io/x/janleike", "platform": "x", "entity_type": "person"},
    "jan leike": {"name": "Jan Leike", "handle": "@janleike", "role": "Anthropic 对齐负责人 / 前 OpenAI 超级对齐主管", "avatar": "https://unavatar.io/x/janleike", "platform": "x", "entity_type": "person"},
    "leopoldasch": {"name": "Leopold Aschenbrenner", "handle": "@leopoldasch", "role": "前 OpenAI 超级对齐研究员 / Situational Awareness 宏文作者", "avatar": "https://unavatar.io/x/leopoldasch", "platform": "x", "entity_type": "person"},
    "leopold aschenbrenner": {"name": "Leopold Aschenbrenner", "handle": "@leopoldasch", "role": "前 OpenAI 超级对齐研究员 / Situational Awareness 宏文作者", "avatar": "https://unavatar.io/x/leopoldasch", "platform": "x", "entity_type": "person"},
    "dwarkesh_sp": {"name": "Dwarkesh Patel", "handle": "@dwarkesh_sp", "role": "深度科技播客主持人 / 硅谷顶尖 AI 领袖深度访谈家", "avatar": "https://unavatar.io/x/dwarkesh_sp", "platform": "x", "entity_type": "person"},
    "dwarkesh patel": {"name": "Dwarkesh Patel", "handle": "@dwarkesh_sp", "role": "深度科技播客主持人 / 硅谷顶尖 AI 领袖深度访谈家", "avatar": "https://unavatar.io/x/dwarkesh_sp", "platform": "x", "entity_type": "person"},
    "maxtegmark": {"name": "Max Tegmark", "handle": "@tegmark", "role": "MIT 物理学家 / 意识与生命3.0作者", "avatar": "https://unavatar.io/x/tegmark", "platform": "x", "entity_type": "person"},
    "tegmark": {"name": "Max Tegmark", "handle": "@tegmark", "role": "MIT 物理学家 / 意识与生命3.0作者", "avatar": "https://unavatar.io/x/tegmark", "platform": "x", "entity_type": "person"},
    "max tegmark": {"name": "Max Tegmark", "handle": "@tegmark", "role": "MIT 物理学家 / 意识与生命3.0作者", "avatar": "https://unavatar.io/x/tegmark", "platform": "x", "entity_type": "person"},
    "esyudkowsky": {"name": "Eliezer Yudkowsky", "handle": "@ESYudkowsky", "role": "MIRI 机器智能研究所创始人 / 强人工智能对齐学者", "avatar": "https://unavatar.io/x/ESYudkowsky", "platform": "x", "entity_type": "person"},
    "eliezer yudkowsky": {"name": "Eliezer Yudkowsky", "handle": "@ESYudkowsky", "role": "MIRI 机器智能研究所创始人 / 强人工智能对齐学者", "avatar": "https://unavatar.io/x/ESYudkowsky", "platform": "x", "entity_type": "person"},
    "clementdelangue": {"name": "Clément Delangue", "handle": "@ClementDelangue", "role": "Hugging Face 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/ClementDelangue", "platform": "x", "entity_type": "person"},
    "clément delangue": {"name": "Clément Delangue", "handle": "@ClementDelangue", "role": "Hugging Face 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/ClementDelangue", "platform": "x", "entity_type": "person"},
    "julien_c": {"name": "Julien Chaumond", "handle": "@julien_c", "role": "Hugging Face 联合创始人兼 CTO", "avatar": "https://unavatar.io/x/julien_c", "platform": "x", "entity_type": "person"},
    "julien chaumond": {"name": "Julien Chaumond", "handle": "@julien_c", "role": "Hugging Face 联合创始人兼 CTO", "avatar": "https://unavatar.io/x/julien_c", "platform": "x", "entity_type": "person"},
    "thom_wolf": {"name": "Thomas Wolf", "handle": "@Thom_Wolf", "role": "Hugging Face 联合创始人兼首席科学官", "avatar": "https://unavatar.io/x/Thom_Wolf", "platform": "x", "entity_type": "person"},
    "thomas wolf": {"name": "Thomas Wolf", "handle": "@Thom_Wolf", "role": "Hugging Face 联合创始人兼首席科学官", "avatar": "https://unavatar.io/x/Thom_Wolf", "platform": "x", "entity_type": "person"},
    "hwchase17": {"name": "Harrison Chase", "handle": "@hwchase17", "role": "LangChain 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/hwchase17", "platform": "x", "entity_type": "person"},
    "harrison chase": {"name": "Harrison Chase", "handle": "@hwchase17", "role": "LangChain 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/hwchase17", "platform": "x", "entity_type": "person"},
    "jerryjliu0": {"name": "Jerry Liu", "handle": "@jerryjliu0", "role": "LlamaIndex 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/jerryjliu0", "platform": "x", "entity_type": "person"},
    "jerry liu": {"name": "Jerry Liu", "handle": "@jerryjliu0", "role": "LlamaIndex 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/jerryjliu0", "platform": "x", "entity_type": "person"},
    "rauchg": {"name": "Guillermo Rauch", "handle": "@rauchg", "role": "Vercel CEO / 前端生成式 AI 先驱", "avatar": "https://unavatar.io/x/rauchg", "platform": "x", "entity_type": "person"},
    "guillermo rauch": {"name": "Guillermo Rauch", "handle": "@rauchg", "role": "Vercel CEO / 前端生成式 AI 先驱", "avatar": "https://unavatar.io/x/rauchg", "platform": "x", "entity_type": "person"},
    "amasad": {"name": "Amjad Masad", "handle": "@amasad", "role": "Replit CEO / AI 原生编程环境开创者", "avatar": "https://unavatar.io/x/amasad", "platform": "x", "entity_type": "person"},
    "amjad masad": {"name": "Amjad Masad", "handle": "@amasad", "role": "Replit CEO / AI 原生编程环境开创者", "avatar": "https://unavatar.io/x/amasad", "platform": "x", "entity_type": "person"},
    "realgeohot": {"name": "George Hotz (geohot)", "handle": "@realgeohot", "role": "tinygrad 创始人 / 传奇极客黑客", "avatar": "https://unavatar.io/x/realgeohot", "platform": "x", "entity_type": "person"},
    "george hotz (geohot)": {"name": "George Hotz (geohot)", "handle": "@realgeohot", "role": "tinygrad 创始人 / 传奇极客黑客", "avatar": "https://unavatar.io/x/realgeohot", "platform": "x", "entity_type": "person"},
    "bindureddy": {"name": "Bindu Reddy", "handle": "@bindureddy", "role": "Abacus.ai CEO / 开源前沿大模型评测领袖", "avatar": "https://unavatar.io/x/bindureddy", "platform": "x", "entity_type": "person"},
    "bindu reddy": {"name": "Bindu Reddy", "handle": "@bindureddy", "role": "Abacus.ai CEO / 开源前沿大模型评测领袖", "avatar": "https://unavatar.io/x/bindureddy", "platform": "x", "entity_type": "person"},
    "simonw": {"name": "Simon Willison", "handle": "@simonw", "role": "独立 AI 工程师 / Prompt 注入攻防首创者", "avatar": "https://unavatar.io/x/simonw", "platform": "x", "entity_type": "person"},
    "simon willison": {"name": "Simon Willison", "handle": "@simonw", "role": "独立 AI 工程师 / Prompt 注入攻防首创者", "avatar": "https://unavatar.io/x/simonw", "platform": "x", "entity_type": "person"},
    "swyx": {"name": "Swyx (Shawn Wang)", "handle": "@swyx", "role": "AI Engineer Foundation / Latent Space 主理人", "avatar": "https://unavatar.io/x/swyx", "platform": "x", "entity_type": "person"},
    "swyx (shawn wang)": {"name": "Swyx (Shawn Wang)", "handle": "@swyx", "role": "AI Engineer Foundation / Latent Space 主理人", "avatar": "https://unavatar.io/x/swyx", "platform": "x", "entity_type": "person"},
    "natfriedman": {"name": "Nat Friedman", "handle": "@natfriedman", "role": "AI 领跑投资人 / 前 GitHub CEO", "avatar": "https://unavatar.io/x/natfriedman", "platform": "x", "entity_type": "person"},
    "nat friedman": {"name": "Nat Friedman", "handle": "@natfriedman", "role": "AI 领跑投资人 / 前 GitHub CEO", "avatar": "https://unavatar.io/x/natfriedman", "platform": "x", "entity_type": "person"},
    "danielgross": {"name": "Daniel Gross", "handle": "@danielgross", "role": "SSI 联合创始人 / 前 Apple AI 负责人", "avatar": "https://unavatar.io/x/danielgross", "platform": "x", "entity_type": "person"},
    "daniel gross": {"name": "Daniel Gross", "handle": "@danielgross", "role": "SSI 联合创始人 / 前 Apple AI 负责人", "avatar": "https://unavatar.io/x/danielgross", "platform": "x", "entity_type": "person"},
    "suhail": {"name": "Suhail Doshi", "handle": "@Suhail", "role": "Playground AI 创始人 / 前 Mixpanel 创始人", "avatar": "https://unavatar.io/x/Suhail", "platform": "x", "entity_type": "person"},
    "suhail doshi": {"name": "Suhail Doshi", "handle": "@Suhail", "role": "Playground AI 创始人 / 前 Mixpanel 创始人", "avatar": "https://unavatar.io/x/Suhail", "platform": "x", "entity_type": "person"},
    "c_valenzuelab": {"name": "Cristóbal Valenzuela", "handle": "@c_valenzuelab", "role": "Runway 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/c_valenzuelab", "platform": "x", "entity_type": "person"},
    "cristóbal valenzuela": {"name": "Cristóbal Valenzuela", "handle": "@c_valenzuelab", "role": "Runway 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/c_valenzuelab", "platform": "x", "entity_type": "person"},
    "davidsholz": {"name": "David Holz", "handle": "@DavidSHolz", "role": "Midjourney 创始人兼 CEO / 前 Leap Motion 联创", "avatar": "https://unavatar.io/x/DavidSHolz", "platform": "x", "entity_type": "person"},
    "david holz": {"name": "David Holz", "handle": "@DavidSHolz", "role": "Midjourney 创始人兼 CEO / 前 Leap Motion 联创", "avatar": "https://unavatar.io/x/DavidSHolz", "platform": "x", "entity_type": "person"},
    "mati_stanisz": {"name": "Mati Staniszewski", "handle": "@mati_stanisz", "role": "ElevenLabs 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/mati_stanisz", "platform": "x", "entity_type": "person"},
    "mati staniszewski": {"name": "Mati Staniszewski", "handle": "@mati_stanisz", "role": "ElevenLabs 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/mati_stanisz", "platform": "x", "entity_type": "person"},
    "alexgraveley": {"name": "Alex Graveley", "handle": "@alexgraveley", "role": "GitHub Copilot 首席总架构师 / Minion AI 创始人", "avatar": "https://unavatar.io/x/alexgraveley", "platform": "x", "entity_type": "person"},
    "alex graveley": {"name": "Alex Graveley", "handle": "@alexgraveley", "role": "GitHub Copilot 首席总架构师 / Minion AI 创始人", "avatar": "https://unavatar.io/x/alexgraveley", "platform": "x", "entity_type": "person"},
    "truell_michael": {"name": "Michael Truell", "handle": "@truell_michael", "role": "Cursor / Anysphere 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/truell_michael", "platform": "x", "entity_type": "person"},
    "michael truell": {"name": "Michael Truell", "handle": "@truell_michael", "role": "Cursor / Anysphere 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/truell_michael", "platform": "x", "entity_type": "person"},
    "amanrsanger": {"name": "Aman Sanger", "handle": "@amanrsanger", "role": "Cursor / Anysphere 联合创始人兼 CTO", "avatar": "https://unavatar.io/x/amanrsanger", "platform": "x", "entity_type": "person"},
    "aman sanger": {"name": "Aman Sanger", "handle": "@amanrsanger", "role": "Cursor / Anysphere 联合创始人兼 CTO", "avatar": "https://unavatar.io/x/amanrsanger", "platform": "x", "entity_type": "person"},
    "scottwu_": {"name": "Scott Wu", "handle": "@ScottWu_", "role": "Cognition 创始人兼 CEO / 自主智能体 Devin 创造者", "avatar": "https://unavatar.io/x/ScottWu_", "platform": "x", "entity_type": "person"},
    "scott wu": {"name": "Scott Wu", "handle": "@ScottWu_", "role": "Cognition 创始人兼 CEO / 自主智能体 Devin 创造者", "avatar": "https://unavatar.io/x/ScottWu_", "platform": "x", "entity_type": "person"},
    "tri_dao": {"name": "Tri Dao", "handle": "@tri_dao", "role": "FlashAttention / Mamba 架构原创发明人", "avatar": "https://unavatar.io/x/tri_dao", "platform": "x", "entity_type": "person"},
    "tri dao": {"name": "Tri Dao", "handle": "@tri_dao", "role": "FlashAttention / Mamba 架构原创发明人", "avatar": "https://unavatar.io/x/tri_dao", "platform": "x", "entity_type": "person"},
    "danielhanchen": {"name": "Daniel Han", "handle": "@danielhanchen", "role": "Unsloth AI 创始人 / 极速显存优化神手", "avatar": "https://unavatar.io/x/danielhanchen", "platform": "x", "entity_type": "person"},
    "daniel han": {"name": "Daniel Han", "handle": "@danielhanchen", "role": "Unsloth AI 创始人 / 极速显存优化神手", "avatar": "https://unavatar.io/x/danielhanchen", "platform": "x", "entity_type": "person"},
    "ajratner": {"name": "Alex Ratner", "handle": "@ajratner", "role": "Snorkel AI 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/ajratner", "platform": "x", "entity_type": "person"},
    "alex ratner": {"name": "Alex Ratner", "handle": "@ajratner", "role": "Snorkel AI 联合创始人兼 CEO", "avatar": "https://unavatar.io/x/ajratner", "platform": "x", "entity_type": "person"},
    "socherr": {"name": "Richard Socher", "handle": "@socherr", "role": "You.com 创始人兼 CEO / 斯坦福 NLP 客座教授", "avatar": "https://unavatar.io/x/socherr", "platform": "x", "entity_type": "person"},
    "richard socher": {"name": "Richard Socher", "handle": "@socherr", "role": "You.com 创始人兼 CEO / 斯坦福 NLP 客座教授", "avatar": "https://unavatar.io/x/socherr", "platform": "x", "entity_type": "person"},
    "emostaque": {"name": "Emad Mostaque", "handle": "@EMostaque", "role": "前 Stability AI 创始人 / Schelling AI 发起人", "avatar": "https://unavatar.io/x/EMostaque", "platform": "x", "entity_type": "person"},
    "emad mostaque": {"name": "Emad Mostaque", "handle": "@EMostaque", "role": "前 Stability AI 创始人 / Schelling AI 发起人", "avatar": "https://unavatar.io/x/EMostaque", "platform": "x", "entity_type": "person"},
    "soumithchintala": {"name": "Soumith Chintala", "handle": "@soumithchintala", "role": "PyTorch 创始人兼核心架构师", "avatar": "https://unavatar.io/x/soumithchintala", "platform": "x", "entity_type": "person"},
    "soumith chintala": {"name": "Soumith Chintala", "handle": "@soumithchintala", "role": "PyTorch 创始人兼核心架构师", "avatar": "https://unavatar.io/x/soumithchintala", "platform": "x", "entity_type": "person"},
    "hamelhusain": {"name": "Hamel Husain", "handle": "@HamelHusain", "role": "前 GitHub / Airbnb 机器学习顾问 / 评测专家", "avatar": "https://unavatar.io/x/HamelHusain", "platform": "x", "entity_type": "person"},
    "hamel husain": {"name": "Hamel Husain", "handle": "@HamelHusain", "role": "前 GitHub / Airbnb 机器学习顾问 / 评测专家", "avatar": "https://unavatar.io/x/HamelHusain", "platform": "x", "entity_type": "person"},
    "jxnlco": {"name": "Jason Liu", "handle": "@jxnlco", "role": "Instructor 框架作者 / 结构化输出先锋", "avatar": "https://unavatar.io/x/jxnlco", "platform": "x", "entity_type": "person"},
    "jason liu": {"name": "Jason Liu", "handle": "@jxnlco", "role": "Instructor 框架作者 / 结构化输出先锋", "avatar": "https://unavatar.io/x/jxnlco", "platform": "x", "entity_type": "person"},
    "jimkellerreal": {"name": "Jim Keller", "handle": "@jimkellerreal", "role": "芯片微架构传奇宗师 / Tenstorrent CEO", "avatar": "https://unavatar.io/x/jimkellerreal", "platform": "x", "entity_type": "person"},
    "jim keller": {"name": "Jim Keller", "handle": "@jimkellerreal", "role": "芯片微架构传奇宗师 / Tenstorrent CEO", "avatar": "https://unavatar.io/x/jimkellerreal", "platform": "x", "entity_type": "person"},
    "rowancheung": {"name": "Rowan Cheung", "handle": "@rowancheung", "role": "The Rundown AI 创始人", "avatar": "https://unavatar.io/x/rowancheung", "platform": "x", "entity_type": "person"},
    "thsottiaux": {"name": "Thibault Sottiaux (Tibo)", "handle": "@thsottiaux", "role": "OpenAI Codex 负责人 / 前沿模型产品主管", "avatar": "https://unavatar.io/x/thsottiaux", "platform": "x", "entity_type": "person"},
    "thibault sottiaux": {"name": "Thibault Sottiaux (Tibo)", "handle": "@thsottiaux", "role": "OpenAI Codex 负责人 / 前沿模型产品主管", "avatar": "https://unavatar.io/x/thsottiaux", "platform": "x", "entity_type": "person"},
    "tibo": {"name": "Thibault Sottiaux (Tibo)", "handle": "@thsottiaux", "role": "OpenAI Codex 负责人 / 前沿模型产品主管", "avatar": "https://unavatar.io/x/thsottiaux", "platform": "x", "entity_type": "person"},
    "danshipper": {"name": "Dan Shipper", "handle": "@danshipper", "role": "Every 创始人 / AI 原生工作流与 Codex 评测专家", "avatar": "https://unavatar.io/x/danshipper", "platform": "x", "entity_type": "person"},
    "dan shipper": {"name": "Dan Shipper", "handle": "@danshipper", "role": "Every 创始人 / AI 原生工作流与 Codex 评测专家", "avatar": "https://unavatar.io/x/danshipper", "platform": "x", "entity_type": "person"},
    "samyamiam": {"name": "Sam Yam", "handle": "@samyamiam", "role": "OpenAI Creator Product 负责人 / Patreon 联合创始人", "avatar": "https://unavatar.io/x/samyamiam", "platform": "x", "entity_type": "person"},
    "sam yam": {"name": "Sam Yam", "handle": "@samyamiam", "role": "OpenAI Creator Product 负责人 / Patreon 联合创始人", "avatar": "https://unavatar.io/x/samyamiam", "platform": "x", "entity_type": "person"},
    "mikeyk": {"name": "Mike Krieger", "handle": "@mikeyk", "role": "Anthropic 首席产品官 (CPO) / Instagram 联合创始人", "avatar": "https://unavatar.io/x/mikeyk", "platform": "x", "entity_type": "person"},
    "mike krieger": {"name": "Mike Krieger", "handle": "@mikeyk", "role": "Anthropic 首席产品官 (CPO) / Instagram 联合创始人", "avatar": "https://unavatar.io/x/mikeyk", "platform": "x", "entity_type": "person"},
    "kevin_t_ngo": {"name": "Kevin Ngo", "handle": "@kevin_t_ngo", "role": "Anthropic Claude 核心工程师", "avatar": "https://unavatar.io/x/kevin_t_ngo", "platform": "x", "entity_type": "person"},
    "weswinder": {"name": "Wes Winder", "handle": "@weswinder", "role": "前沿模型评测与 AI 研究者", "avatar": "https://unavatar.io/x/weswinder", "platform": "x", "entity_type": "person"},
    "claudedevs": {"name": "Claude Developers", "handle": "@ClaudeDevs", "role": "Anthropic Claude 官方开发者平台", "avatar": "https://unavatar.io/anthropic", "platform": "x", "entity_type": "company"},
    "claude developers": {"name": "Claude Developers", "handle": "@ClaudeDevs", "role": "Anthropic Claude 官方开发者平台", "avatar": "https://unavatar.io/anthropic", "platform": "x", "entity_type": "company"},
    "higgsfield_ai": {"name": "Higgsfield AI", "handle": "@higgsfield_ai", "role": "前沿 3D 与扩散视频世界模型研发平台", "avatar": "https://unavatar.io/x/higgsfield_ai", "platform": "x", "entity_type": "company"},
    "higgsfield ai": {"name": "Higgsfield AI", "handle": "@higgsfield_ai", "role": "前沿 3D 与扩散视频世界模型研发平台", "avatar": "https://unavatar.io/x/higgsfield_ai", "platform": "x", "entity_type": "company"},
    "scenario_gg": {"name": "Scenario AI", "handle": "@Scenario_gg", "role": "生成式游戏引擎与风格一致性模型平台", "avatar": "https://unavatar.io/x/Scenario_gg", "platform": "x", "entity_type": "company"},
    "lumalabsai": {"name": "Luma AI", "handle": "@LumaLabsAI", "role": "Dream Machine 视频生成与 3D 高斯神经渲染", "avatar": "https://unavatar.io/x/LumaLabsAI", "platform": "x", "entity_type": "company"},
    "luma ai": {"name": "Luma AI", "handle": "@LumaLabsAI", "role": "Dream Machine 视频生成与 3D 高斯神经渲染", "avatar": "https://unavatar.io/x/LumaLabsAI", "platform": "x", "entity_type": "company"},
    "tibo_maker": {"name": "Tibo", "handle": "@tibo_maker", "role": "独立 AI 创作者 / 极客架构观察家", "avatar": "https://unavatar.io/x/tibo_maker", "platform": "x", "entity_type": "person"},
    "matt wolfe": {"name": "Matt Wolfe", "handle": "@mreflow", "role": "FutureTools 创始人 / 顶级多模态视频博主", "avatar": "https://unavatar.io/x/mreflow", "platform": "x", "entity_type": "person"},
    "matthew_berman": {"name": "Matthew Berman", "handle": "@matthew_berman", "role": "前沿开源模型实测与本地微调先锋", "avatar": "https://unavatar.io/x/matthew_berman", "platform": "x", "entity_type": "person"},
    "matthew berman": {"name": "Matthew Berman", "handle": "@matthew_berman", "role": "前沿开源模型实测与本地微调先锋", "avatar": "https://unavatar.io/x/matthew_berman", "platform": "x", "entity_type": "person"},
    "t3dotgg": {"name": "Theo Browne", "handle": "@t3dotgg", "role": "全栈架构评测先锋 / Ping Labs 创始人", "avatar": "https://unavatar.io/x/t3dotgg", "platform": "x", "entity_type": "person"},
    "theo browne": {"name": "Theo Browne", "handle": "@t3dotgg", "role": "全栈架构评测先锋 / Ping Labs 创始人", "avatar": "https://unavatar.io/x/t3dotgg", "platform": "x", "entity_type": "person"},
    "fireship_dev": {"name": "Jeff Delaney (Fireship)", "handle": "@fireship_dev", "role": "极速代码与前沿技术实操视频之神", "avatar": "https://unavatar.io/x/fireship_dev", "platform": "x", "entity_type": "person"},
    "jeff delaney (fireship)": {"name": "Jeff Delaney (Fireship)", "handle": "@fireship_dev", "role": "极速代码与前沿技术实操视频之神", "avatar": "https://unavatar.io/x/fireship_dev", "platform": "x", "entity_type": "person"},
    "bilawalsidhu": {"name": "Bilawal Sidhu", "handle": "@bilawalsidhu", "role": "空间计算、高斯溅射与具身 AI 创作者", "avatar": "https://unavatar.io/x/bilawalsidhu", "platform": "x", "entity_type": "person"},
    "bilawal sidhu": {"name": "Bilawal Sidhu", "handle": "@bilawalsidhu", "role": "空间计算、高斯溅射与具身 AI 创作者", "avatar": "https://unavatar.io/x/bilawalsidhu", "platform": "x", "entity_type": "person"},
    "skirano": {"name": "Pietro Schirano", "handle": "@skirano", "role": "Everart AI 创始人 / 生成式设计先驱", "avatar": "https://unavatar.io/x/skirano", "platform": "x", "entity_type": "person"},
    "pietro schirano": {"name": "Pietro Schirano", "handle": "@skirano", "role": "Everart AI 创始人 / 生成式设计先驱", "avatar": "https://unavatar.io/x/skirano", "platform": "x", "entity_type": "person"},
    "linusekenstam": {"name": "Linus Ekenstam", "handle": "@LinusEkenstam", "role": "AI 生成式创意设计策展人", "avatar": "https://unavatar.io/x/LinusEkenstam", "platform": "x", "entity_type": "person"},
    "linus ekenstam": {"name": "Linus Ekenstam", "handle": "@LinusEkenstam", "role": "AI 生成式创意设计策展人", "avatar": "https://unavatar.io/x/LinusEkenstam", "platform": "x", "entity_type": "person"},
    "alliekmiller": {"name": "Allie K. Miller", "handle": "@alliekmiller", "role": "前 AWS 机器商业化主管 / 顶级 AI 商业化顾问", "avatar": "https://unavatar.io/x/alliekmiller", "platform": "x", "entity_type": "person"},
    "allie k. miller": {"name": "Allie K. Miller", "handle": "@alliekmiller", "role": "前 AWS 机器商业化主管 / 顶级 AI 商业化顾问", "avatar": "https://unavatar.io/x/alliekmiller", "platform": "x", "entity_type": "person"},
    "nathanbenaich": {"name": "Nathan Benaich", "handle": "@nathanbenaich", "role": "State of AI Report 年度白皮书作者 / Air Street Capital", "avatar": "https://unavatar.io/x/nathanbenaich", "platform": "x", "entity_type": "person"},
    "nathan benaich": {"name": "Nathan Benaich", "handle": "@nathanbenaich", "role": "State of AI Report 年度白皮书作者 / Air Street Capital", "avatar": "https://unavatar.io/x/nathanbenaich", "platform": "x", "entity_type": "person"},
    "emollick": {"name": "Ethan Mollick", "handle": "@emollick", "role": "沃顿商学院教授 / Co-Intelligence 作者 / 生成式 AI 组织行为先驱", "avatar": "https://unavatar.io/x/emollick", "platform": "x", "entity_type": "person"},
    "ethan mollick": {"name": "Ethan Mollick", "handle": "@emollick", "role": "沃顿商学院教授 / Co-Intelligence 作者 / 生成式 AI 组织行为先驱", "avatar": "https://unavatar.io/x/emollick", "platform": "x", "entity_type": "person"},
    "deedydas": {"name": "Deedy Das", "handle": "@deedydas", "role": "Menlo Ventures 合伙人 / AI 行业风向观察家", "avatar": "https://unavatar.io/x/deedydas", "platform": "x", "entity_type": "person"},
    "deedy das": {"name": "Deedy Das", "handle": "@deedydas", "role": "Menlo Ventures 合伙人 / AI 行业风向观察家", "avatar": "https://unavatar.io/x/deedydas", "platform": "x", "entity_type": "person"},
    "tunguz": {"name": "Tomasz Tunguz", "handle": "@tunguz", "role": "Theory Ventures 创始人 / 顶级企业级 AI 软件数据分析师", "avatar": "https://unavatar.io/x/tunguz", "platform": "x", "entity_type": "person"},
    "tomasz tunguz": {"name": "Tomasz Tunguz", "handle": "@tunguz", "role": "Theory Ventures 创始人 / 顶级企业级 AI 软件数据分析师", "avatar": "https://unavatar.io/x/tunguz", "platform": "x", "entity_type": "person"},
    "kantrowitz": {"name": "Alex Kantrowitz", "handle": "@Kantrowitz", "role": "Big Technology 创始人 / CNBC 撰稿人", "avatar": "https://unavatar.io/x/Kantrowitz", "platform": "x", "entity_type": "person"},
    "alex kantrowitz": {"name": "Alex Kantrowitz", "handle": "@Kantrowitz", "role": "Big Technology 创始人 / CNBC 撰稿人", "avatar": "https://unavatar.io/x/Kantrowitz", "platform": "x", "entity_type": "person"},
    "caseynewton": {"name": "Casey Newton", "handle": "@CaseyNewton", "role": "Platformer 创始人 / 硅谷科技政经分析家", "avatar": "https://unavatar.io/x/CaseyNewton", "platform": "x", "entity_type": "person"},
    "casey newton": {"name": "Casey Newton", "handle": "@CaseyNewton", "role": "Platformer 创始人 / 硅谷科技政经分析家", "avatar": "https://unavatar.io/x/CaseyNewton", "platform": "x", "entity_type": "person"},
    "khanov": {"name": "Karen Hao", "handle": "@khanov", "role": "《华尔街日报》/ 前 MIT 科技评论调查记者 / AI 权力博弈作者", "avatar": "https://unavatar.io/x/khanov", "platform": "x", "entity_type": "person"},
    "karen hao": {"name": "Karen Hao", "handle": "@khanov", "role": "《华尔街日报》/ 前 MIT 科技评论调查记者 / AI 权力博弈作者", "avatar": "https://unavatar.io/x/khanov", "platform": "x", "entity_type": "person"},
    "cademetz": {"name": "Cade Metz", "handle": "@CadeMetz", "role": "《纽约时报》记者 / 《Genius Makers》天才制造者作者", "avatar": "https://unavatar.io/x/CadeMetz", "platform": "x", "entity_type": "person"},
    "cade metz": {"name": "Cade Metz", "handle": "@CadeMetz", "role": "《纽约时报》记者 / 《Genius Makers》天才制造者作者", "avatar": "https://unavatar.io/x/CadeMetz", "platform": "x", "entity_type": "person"},
}

# 抓取源清单：严格剔除地方政务/会议水文，仅聚合全球顶尖 AI 突破与极客一线动态
SOURCES = {
    # 1. 全球一线顶级科技媒体突发 (24小时超高频全球榜 + 深度突破)
    "openai_official": {
        "name": "OpenAI 官方动态",
        "url": "https://openai.com/news/rss.xml",
        "default_category": "news",
        "type": "rss"
    },
    "x_trending_ai": {
        "name": "𝕏 实时爆款热议",
        "url": "https://news.google.com/rss/search?q=site:x.com+AI+OR+LLM+when:1d&hl=en-US&gl=US&ceid=US:en",
        "default_category": "celebrity",
        "platform": "x",
        "type": "x_trending"
    },
    "techmeme_ai": {
        "name": "Techmeme 硅谷风向",
        "url": "https://www.techmeme.com/feed.xml",
        "default_category": "news",
        "type": "rss"
    },
    "wired_ai": {
        "name": "Wired AI",
        "url": "https://www.wired.com/feed/tag/ai/latest/rss",
        "default_category": "news",
        "type": "rss"
    },
    "venturebeat_ai": {
        "name": "VentureBeat AI",
        "url": "https://venturebeat.com/category/ai/feed/",
        "default_category": "news",
        "type": "rss"
    },
    "theverge_ai": {
        "name": "The Verge AI",
        "url": "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
        "default_category": "news",
        "type": "rss"
    },
    "arstechnica_ai": {
        "name": "Ars Technica",
        "url": "https://feeds.arstechnica.com/arstechnica/technology-lab",
        "default_category": "news",
        "type": "rss"
    },
    "mit_tech_review": {
        "name": "MIT Tech Review",
        "url": "https://www.technologyreview.com/feed/",
        "default_category": "news",
        "type": "rss"
    },
    "the_decoder": {
        "name": "THE DECODER",
        "url": "https://the-decoder.com/feed/",
        "default_category": "news",
        "type": "rss"
    },
    "hacker_news": {
        "name": "Hacker News",
        "url": "https://hn.algolia.com/api/v1/search_by_date?tags=story&query=AI+OR+LLM+OR+OpenAI+OR+Claude+OR+DeepSeek&hitsPerPage=15",
        "default_category": "news",
        "type": "hn_api"
    },

    # 2. 社交平台专栏：全面聚焦 𝕏 (Twitter) 顶尖领袖与科学家独家发声，严禁匿名论坛水帖


    # 3. 场景化落地实用工具 (每日最新免安装可玩应用与高频更新开源神器)
    "github_tools": {
        "name": "GitHub AI 应用",
        "url": "https://api.github.com/search/repositories?q=topic:ai-app+OR+topic:ai-tool+OR+topic:llm-tool+stars:>30&sort=updated&order=desc&per_page=16",
        "default_category": "tools",
        "type": "github_tools"
    },
    "huggingface_spaces": {
        "name": "Hugging Face 体验应用",
        "url": "https://huggingface.co/api/spaces?sort=likes&direction=-1&limit=25",
        "default_category": "tools",
        "type": "hf_spaces"
    },
    "product_hunt": {
        "name": "Product Hunt 新品",
        "url": "https://www.producthunt.com/feed",
        "default_category": "tools",
        "type": "ph_feed"
    },

    # 4. YouTube 高热度实战技巧、经验指南与工作流（接入全球顶级 AI 极客技术源）
    "youtube_channels": [
        {"name": "Fireship", "id": "UCsBjURrPoezykLs9EqgamOA"},
        {"name": "Theo - t3.gg", "id": "UCbRP3c757lWg9M-U7TyEkXA"},
        {"name": "AI Explained", "id": "UCNJ1Ymd5yFuUPtn21xtRbbw"},
        {"name": "Two Minute Papers", "id": "UCbfYPyITQ-7l4upoX8nvctg"},
        {"name": "Matthew Berman", "id": "UCawZsQWqfGSbCI5yjkdVkTA"},
        {"name": "Andrej Karpathy", "id": "UCXUPKJO5MZQN11PqgIvyuvQ"},
        {"name": "3Blue1Brown", "id": "UCYO_jab_esuFRV4b17AJtAw"},
        {"name": "Matt Wolfe", "id": "UChpleBmo18P08aKCIgti38g"},
        {"name": "Yannic Kilcher", "id": "UCZHmQk67mN31gbHey6BVyNw"},
        {"name": "NetworkChuck", "id": "UCOuGATIAbd2DvzJmUgXn2IQ"}
    ]
}

# 顶流 AI 创作者矩阵元数据（前端博主直达栏与多样性展示使用）
AI_CREATORS = [
    {
        "id": "fireship",
        "name": "Fireship",
        "channel_id": "UCsBjURrPoezykLs9EqgamOA",
        "handle": "@fireship",
        "avatar": "https://unavatar.io/youtube/UCsBjURrPoezykLs9EqgamOA",
        "category": "⚡ 极速全栈实战",
        "subscribers": "3.4M+",
        "desc": "极速技术拆解与前沿模型实操"
    },
    {
        "id": "theo",
        "name": "Theo - t3.gg",
        "channel_id": "UCbRP3c757lWg9M-U7TyEkXA",
        "handle": "@t3dotgg",
        "avatar": "https://unavatar.io/x/t3dotgg",
        "category": "🛠️ 全栈工程与架构辩论",
        "subscribers": "360K+",
        "desc": "一线技术选型与模型落地深度评测"
    },
    {
        "id": "aiexplained",
        "name": "AI Explained",
        "channel_id": "UCNJ1Ymd5yFuUPtn21xtRbbw",
        "handle": "@aiexplained-official",
        "avatar": "https://unavatar.io/youtube/UCNJ1Ymd5yFuUPtn21xtRbbw",
        "category": "🔥 深度评测与基准盲测",
        "subscribers": "450K+",
        "desc": "严谨的大模型思考链与测试期计算极限盲测"
    },
    {
        "id": "twominutepapers",
        "name": "Two Minute Papers",
        "channel_id": "UCbfYPyITQ-7l4upoX8nvctg",
        "handle": "@TwoMinutePapers",
        "avatar": "https://unavatar.io/youtube/UCbfYPyITQ-7l4upoX8nvctg",
        "category": "🎓 论文精讲与学术突破",
        "subscribers": "1.7M+",
        "desc": "通俗震撼的前沿 AI 论文与图形学突破精讲"
    },
    {
        "id": "karpathy",
        "name": "Andrej Karpathy",
        "channel_id": "UCXUPKJO5MZQN11PqgIvyuvQ",
        "handle": "@karpathy",
        "avatar": "https://unavatar.io/x/karpathy",
        "category": "🎓 泰斗从零手写原理",
        "subscribers": "1.1M+",
        "desc": "OpenAI 联创手写微积分链式法则与神经网络"
    },
    {
        "id": "3blue1brown",
        "name": "3Blue1Brown",
        "channel_id": "UCYO_jab_esuFRV4b17AJtAw",
        "handle": "@3blue1brown",
        "avatar": "https://unavatar.io/youtube/UCYO_jab_esuFRV4b17AJtAw",
        "category": "🎓 几何直觉与可视化",
        "subscribers": "6.8M+",
        "desc": "Transformer 几何空间与注意力权重无死角拆解"
    },
    {
        "id": "matthew_berman",
        "name": "Matthew Berman",
        "channel_id": "UCawZsQWqfGSbCI5yjkdVkTA",
        "handle": "@matthew_berman",
        "avatar": "https://unavatar.io/youtube/UCawZsQWqfGSbCI5yjkdVkTA",
        "category": "🤖 开源模型与本地实测",
        "subscribers": "680K+",
        "desc": "开源模型微调、极速推理与私有化实测"
    },
    {
        "id": "matt_wolfe",
        "name": "Matt Wolfe",
        "channel_id": "UChpleBmo18P08aKCIgti38g",
        "handle": "@mreflow",
        "avatar": "https://unavatar.io/x/mreflow",
        "category": "🎨 AI 工具与多模态",
        "subscribers": "620K+",
        "desc": "最新 AI 实用工具盘点与多模态工作流"
    },
    {
        "id": "yannic_kilcher",
        "name": "Yannic Kilcher",
        "channel_id": "UCZHmQk67mN31gbHey6BVyNw",
        "handle": "@YannicKilcher",
        "avatar": "https://unavatar.io/youtube/UCZHmQk67mN31gbHey6BVyNw",
        "category": "🎓 硬核论文逐行细读",
        "subscribers": "260K+",
        "desc": "强化学习与大模型底层数学架构精读"
    },
    {
        "id": "networkchuck",
        "name": "NetworkChuck",
        "channel_id": "UCOuGATIAbd2DvzJmUgXn2IQ",
        "handle": "@NetworkChuck",
        "avatar": "https://unavatar.io/youtube/UCOuGATIAbd2DvzJmUgXn2IQ",
        "category": "⚡ 极客网络与硬件本地化",
        "subscribers": "4.2M+",
        "desc": "5分钟在普通笔记本部署本地私密 AI"
    }
]

# 创作者防霸屏与多样性门禁规则 (Author Diversity Gate)
YOUTUBE_DIVERSITY_RULES = {
    "max_viral_per_author": 1,  # 近期爆点专栏中，单个作者最多出现 1 条
    "max_total_per_author": 2,  # 全站视频库中，单个作者最多出现 2 条
}

