# -*- coding: utf-8 -*-
import json

PROMPTS = [
    # 0. 🌟 前沿模型专属核心爆款 (DeepSeek R1 / Claude 3.7 / o1 / o3 / Sora 2 / OpenClaw)
    {
        "id": "prompt_tibo_gpt_reset_architecture",
        "sub_type": "reasoning",
        "model_family": "tibo_reset",
        "purpose_zh": "🧠 深度推理 · Tibo 疯传全网 GPT 重置与上下文净化架构",
        "purpose_en": "🧠 Deep Reasoning · Tibo Viral GPT Reset & Context Purge Architecture",
        "title_zh": "💡【Tibo 置顶爆款】全网疯传的‘GPT重置/思维链重启’提示词架构：净化上下文膨胀与先验幻觉",
        "title_en": "💡 [Tibo Viral Hit] The Famous 'GPT Reset' System Architecture: Purge Context Drift & Hallucinations",
        "url": "https://x.com/tibo_maker",
        "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80&auto=format&fit=crop",
        "source": "𝕏 极客实战 · Tibo",
        "author": "Tibo (@tibo_maker)",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-14T23:50:00Z",
        "recommended_model": "o1 / o3-mini / DeepSeek-R1 / GPT-4o",
        "temp_advice": "建议温度 0.2 | 强制重构逻辑推导链",
        "metrics": {"type": "🧠 GPT重置", "model": "o1/o3/R1", "temp": "0.2"},
        "content_snippet": "Purges accumulated context drift, hidden assumptions, and conversational bias without discarding task memory, forcing models to reason from first principles.",
        "summary_zh": "不清除对话任务前提下，强制模型刷新隐藏先验偏置、粉碎多轮死循环车轱辘话，激发纯净的测试期逻辑推演。",
        "summary_en": "Purges accumulated context drift, hidden assumptions, and conversational bias without discarding task memory, forcing models to reason from first principles.",
        "prompt_content_zh": "【SYSTEM RESET & CONTEXT PURGE PROTOCOL】\n你现在执行内部思维链重置程序（Attention Buffer Refresh）。\n请立刻执行以下 3 步上下文净化与重新推演：\n1. 剥离先入为主假设：忽略此前对话中由用户或模型产生的一切中间妥协、逻辑死锁或未验证的推论，仅保留最原始的核心约束与输入事实；\n2. 回归第一性原理：以白纸状态（Tabula Rasa）重新构建解题状态空间，将问题分解为不可再分的基本公理；\n3. 逆向证伪验证：在输出最终结论前，必须主动尝试推翻自己的前一步推演。只有无法被反例击破的路径，方可作为最终执行方案。\n现在，以最高逻辑严密性重新推导当前问题：",
        "prompt_content_en": "[SYSTEM RESET & CONTEXT PURGE PROTOCOL]\nYou are now executing an internal reasoning reset protocol (Attention Buffer Refresh).\nImmediately perform the following 3-step context purge and re-derivation:\n1. Purge Hidden Priors: Discard all accumulated conversational drift, intermediate compromises, and unverified assumptions from earlier turns; retain only immutable core requirements and raw facts.\n2. First-Principles Reconstruction: Re-examine the problem space from a blank slate (Tabula Rasa), decomposing goals into irreducible axioms.\n3. Adversarial Invalidation: Before producing final output, aggressively attempt to disprove your own hypotheses. Output only the path that survives rigorous counter-examples.\nNow, re-evaluate and solve the current task with absolute precision:",
        "prompt_content": "[SYSTEM RESET & CONTEXT PURGE PROTOCOL]\n你现在执行内部思维链重置程序（Attention Buffer Refresh）。\n请立刻执行以下 3 步上下文净化与重新推演：\n1. 剥离先入为主假设：忽略此前对话中由用户或模型产生的一切中间妥协、逻辑死锁或未验证的推论，仅保留最原始的核心约束与输入事实；\n2. 回归第一性原理：以白纸状态（Tabula Rasa）重新构建解题状态空间，将问题分解为不可再分的基本公理；\n3. 逆向证伪验证：在输出最终结论前，必须主动尝试推翻自己的前一步推演。只有无法被反例击破的路径，方可作为最终执行方案。\n现在，以最高逻辑严密性重新推导当前问题：",
        "tags": ["Tibo神作", "GPT重置", "防幻觉", "深度推理"]
    },
    {
        "id": "prompt_deepseek_r1_zero_shot",
        "sub_type": "reasoning",
        "model_family": "deepseek_r1",
        "purpose_zh": "🧠 深度推理 · DeepSeek 官方建议：零 System Prompt 自由思维链",
        "purpose_en": "🧠 Deep Reasoning · DeepSeek Official: Zero-System Pure RL Chain of Thought",
        "title_zh": "💡【DeepSeek 官方白皮书标准】避坑指南：纯强化学习 (RL) 零预设提示词模板，彻底释放 671B 思考潜能",
        "title_en": "💡 [DeepSeek Official Standard] Zero-System Prompt Architecture: Unleash 671B Pure RL Thinking Depth",
        "url": "https://github.com/deepseek-ai/DeepSeek-R1",
        "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80&auto=format&fit=crop",
        "source": "DeepSeek 官方指南",
        "author": "DeepSeek 架构组",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-14T22:30:00Z",
        "recommended_model": "DeepSeek-R1 (671B Full)",
        "temp_advice": "建议温度 0.6 | 给予模型充足的反思与自我纠错采样空间",
        "metrics": {"type": "🧠 DeepSeek R1", "model": "R1 671B", "temp": "0.6"},
        "content_snippet": "Official DeepSeek guidance: Never constrain R1 with complex system personas or few-shot formats. Provide exact verification criteria and let GRPO-trained reasoning explore hypotheses freely.",
        "summary_zh": "官方权威规范：切勿使用复杂的系统人设或旧式 Few-shot 模板束缚 R1。定义精准验收标准，让模型原生自我验证与反思机制充分展开。",
        "summary_en": "Official guidance: Avoid system personas or few-shot anchors. Define clear criteria and let native self-reflection chains explore freely.",
        "prompt_content_zh": "【任务目标与边界约束】\n请针对以下问题进行最深度的数学与算法推导：\n\n【核心约束】：\n1. 结果必须满足绝对严谨性，不跳步、不省略推导推算过程；\n2. 当遇到不确定或可能的分支情况时，请主动分流验证每个可能分支，并在思维链内部推翻不成立假说；\n3. 最终答案请以结构化的格式完整输出，并在末尾提供边界极端情况（Edge Cases）证明。\n\n【待解决问题】：\n[在此处粘贴你的高难度数学难题、架构难题或算法设计需求]",
        "prompt_content_en": "[TASK OBJECTIVE & BOUNDARY CRITERIA]\nPerform exhaustive mathematical and algorithmic derivation for the following problem:\n\n[CORE CONSTRAINTS]:\n1. Output must maintain uncompromising mathematical rigor without skipping derivation steps;\n2. When encountering ambiguities or potential branches, proactively branch and falsify invalid hypotheses in your reasoning trace;\n3. Present the final solution in structured markdown, followed by edge case verification proofs.\n\n[PROBLEM STATEMENT]:\n[Paste your high-complexity problem, architecture challenge, or algorithm design here]",
        "prompt_content": "【任务目标与边界约束】\n请针对以下问题进行最深度的数学与算法推导：\n\n【核心约束】：\n1. 结果必须满足绝对严谨性，不跳步、不省略推导推算过程；\n2. 当遇到不确定或可能的分支情况时，请主动分流验证每个可能分支，并在思维链内部推翻不成立假说；\n3. 最终答案请以结构化的格式完整输出，并在末尾提供边界极端情况（Edge Cases）证明。\n\n【待解决问题】：\n[在此处粘贴你的高难度数学难题、架构难题或算法设计需求]",
        "tags": ["DeepSeek官方", "R1纯RL", "思维链", "数学竞赛"]
    },
    {
        "id": "prompt_claude37_extended_thinking",
        "sub_type": "coding",
        "model_family": "claude_37",
        "purpose_zh": "💻 混合推理 · Claude 3.7 思考时间预算控制与全栈代码交付",
        "purpose_en": "💻 Hybrid Reasoning · Claude 3.7 Thinking Budget Control & Full-Stack Delivery",
        "title_zh": "💡【Claude 3.7 官方前沿】混合推理 (Hybrid Reasoning) 架构工程：单次交互产出生产级可用全栈模块",
        "title_en": "💡 [Claude 3.7 Frontier] Extended Thinking & Budget Control: One-Shot Production Full-Stack Module",
        "url": "https://docs.anthropic.com/",
        "image_url": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80&auto=format&fit=crop",
        "source": "Anthropic 官方前沿",
        "author": "Anthropic 工程师",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-14T21:00:00Z",
        "recommended_model": "Claude 3.7 Sonnet (Extended Thinking Mode)",
        "temp_advice": "建议温度 1.0 (Extended Thinking 官方推荐温度) | 预算 16k tokens",
        "metrics": {"type": "💻 Claude 3.7", "model": "Sonnet 3.7", "temp": "1.0"},
        "content_snippet": "Maximizes Claude 3.7's hybrid reasoning budget: plans architectural trade-offs in thinking phase, then delivers production-grade, bug-free implementations.",
        "summary_zh": "充分释放 Claude 3.7 混合推理优势：在思考阶段预判所有边界情况与架构取舍，一键输出直接可运行的高内聚工程代码。",
        "summary_en": "Leverages Claude 3.7 extended thinking to resolve architecture trade-offs before generating complete, bug-free production code.",
        "prompt_content_zh": "你正在以 Claude 3.7 Extended Thinking 模式担任首席全栈系统架构师。在开始输出代码之前，请利用深度思考预算规划并解决以下维度：\n1. 架构选型与权衡（Trade-offs）：列出备选方案的复杂度、维护成本与性能瓶颈；\n2. 状态机与并发竞态模拟：预判并消除所有可能的异步竞态与内存泄露；\n3. 一次性交付完整生产级代码（Zero Placeholders）：绝对不要使用 '// TODO: implement later' 或占位符，每一行代码都必须经过思考阶段自我审查；\n4. 包含防御性单元测试与错误边界（Error Boundary）。\n\n【开发需求】：\n[在此处详细描述你的业务系统或复杂交互功能]",
        "prompt_content_en": "You are acting as a Principal Full-Stack Architect utilizing Claude 3.7 Extended Thinking mode. Before emitting code, use your reasoning budget to analyze:\n1. Architecture Trade-offs: Benchmark alternative designs across complexity, maintenance, and latency;\n2. Concurrency & Race Condition Simulation: Map asynchronous lifecycles and eliminate memory leaks;\n3. Complete Zero-Placeholder Implementation: Never emit comments like '// TODO: implement later'; ensure every function is production-ready;\n4. Include defensive unit tests and resilient error boundaries.\n\n[REQUIREMENTS]:\n[Describe your complex business system or full-stack feature here]",
        "prompt_content": "你正在以 Claude 3.7 Extended Thinking 模式担任首席全栈系统架构师。在开始输出代码之前，请利用深度思考预算规划并解决以下维度：\n1. 架构选型与权衡（Trade-offs）：列出备选方案的复杂度、维护成本与性能瓶颈；\n2. 状态机与并发竞态模拟：预判并消除所有可能的异步竞态与内存泄露；\n3. 一次性交付完整生产级代码（Zero Placeholders）：绝对不要使用 '// TODO: implement later' 或占位符，每一行代码都必须经过思考阶段自我审查；\n4. 包含防御性单元测试与错误边界（Error Boundary）。\n\n【开发需求】：\n[在此处详细描述你的业务系统或复杂交互功能]",
        "tags": ["Claude 3.7", "思考预算", "全栈架构", "无占位符"]
    },
    {
        "id": "prompt_openai_o3_mini_math_proof",
        "sub_type": "reasoning",
        "model_family": "openai_o3",
        "purpose_zh": "🧠 逻辑推演 · OpenAI o3-mini 对抗性自我反思与数学证明",
        "purpose_en": "🧠 Logical Proof · OpenAI o3-mini Adversarial Reflection & Mathematical Rigor",
        "title_zh": "💡【OpenAI 推理引擎】o1 / o3-mini 对抗性逆向验证：防偷懒、无漏洞的形式化推导模板",
        "title_en": "💡 [OpenAI o1/o3-mini Spec] Adversarial Invalidation & Formal Mathematical Proof Template",
        "url": "https://platform.openai.com/docs/guides/reasoning",
        "image_url": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80&auto=format&fit=crop",
        "source": "OpenAI 官方指南",
        "author": "OpenAI 研究院",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-14T20:00:00Z",
        "recommended_model": "OpenAI o3-mini (High Reasoning Effort) / o1",
        "temp_advice": "建议温度 1.0 (Reasoning 模型默认参数) | Effort: High",
        "metrics": {"type": "🧠 OpenAI o3", "model": "o3-mini High", "temp": "1.0"},
        "content_snippet": "Adversarial verification prompt forcing OpenAI reasoning models to challenge intermediate proofs before presenting the final answer.",
        "summary_zh": "强制 o1/o3 模型在思考链中构建对抗性反例，逐项排查边界条件，杜绝‘想当然’的不严密推理。",
        "summary_en": "Forces o1/o3 reasoning models to construct counter-examples at each deduction step, eliminating hidden logical leaps.",
        "prompt_content_zh": "请作为普林斯顿高等研究院的理论数学与计算机科学家，为以下命题提供绝对严格的形式化证明：\n【推理原则】：\n1. 在得出任何推论前，强制在内部思考中构建至少 2 个极端反例（Counter-examples）尝试推翻自身结论；\n2. 若存在任何定义域边界或除零/无穷/退化奇异点，必须显式讨论其收敛性与连续性；\n3. 证明步骤编号必须形成严格的依赖拓扑图，禁止循环论证。\n\n【待证明命题】：\n[输入你的算法正确性证明或数学猜想]",
        "prompt_content_en": "Acting as a Theoretical Mathematician and Computer Scientist at the Institute for Advanced Study, provide an airtight formal proof for the following:\n[REASONING PRINCIPLES]:\n1. Before asserting any deduction, construct at least 2 extreme counter-examples in your reasoning trace to aggressively stress-test the hypothesis;\n2. Explicitly evaluate singular points, degenerate cases, and asymptotic boundaries for convergence;\n3. Steps must form a directed acyclic graph of formal lemmas without circular logic.\n\n[THEOREM / CONJECTURE]:\n[Input your algorithm proof or mathematical hypothesis here]",
        "prompt_content": "请作为普林斯顿高等研究院的理论数学与计算机科学家，为以下命题提供绝对严格的形式化证明：\n【推理原则】：\n1. 在得出任何推论前，强制在内部思考中构建至少 2 个极端反例（Counter-examples）尝试推翻自身结论；\n2. 若存在任何定义域边界或除零/无穷/退化奇异点，必须显式讨论其收敛性与连续性；\n3. 证明步骤编号必须形成严格的依赖拓扑图，禁止循环论证。\n\n【待证明命题】：\n[输入你的算法正确性证明或数学猜想]",
        "tags": ["OpenAI o3", "形式化证明", "对抗反思", "数学竞赛"]
    },
    {
        "id": "prompt_sora2_wan21_cinematic_director",
        "sub_type": "creative",
        "model_family": "sora2_wan21",
        "purpose_zh": "🎬 视频生成 · Sora 2 / Wan 2.1 电影级三维物理世界运镜",
        "purpose_en": "🎬 Video Generation · Sora 2 / Wan 2.1 3D Spatial Physics & Cinematic Camera",
        "title_zh": "💡【Sora 2 / Wan 2.1 导演级】高保真物理世界、体积光与多轴多机位镜头控制提示词库",
        "title_en": "💡 [Sora 2 & Wan 2.1 Director Standard] Volumetric Lighting, Fluid Collision & Multi-Axis Motion Prompt",
        "url": "https://openai.com/sora",
        "image_url": "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800&q=80&auto=format&fit=crop",
        "source": "影视工业极客",
        "author": "CinePrompt Lab",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-14T19:00:00Z",
        "recommended_model": "Sora 2 / Wan 2.1 / Kling 1.5 / Runway Gen-3",
        "temp_advice": "建议高写实模式 (High-Fidelity Physics Engine)",
        "metrics": {"type": "🎬 Sora 2视频", "model": "Sora2 / Wan2.1", "temp": "Cinematic"},
        "content_snippet": "Industry-grade video prompting template specifying camera focal length, volumetric light decay, collision physics, and 60fps natural motion blur.",
        "summary_zh": "工业级视频生成规范：精确指定镜头焦段、多轴三维运镜曲线、流体碰撞阻尼与真实快门运动模糊。",
        "summary_en": "Industry-grade template specifying lens focal length, 3D camera path, fluid collision physics, and authentic motion blur.",
        "prompt_content_zh": "[Shot Description]: 35mm anamorphic cinema lens, f/1.8, master shot with continuous orbit camera movement.\n[Subject & Action]: [主体角色与连续动作，例如：A cyberpunk neon-lit courier running through dense rainy alleys, leaping across a puddle].\n[Physics & Dynamics]: Photorealistic surface reflection with physically accurate water splash ripples, droplets refracting neon signs, natural cloth turbulence reacting to wind drag.\n[Lighting & Color Grade]: Volumetric mist scattering amber sodium lights and cyan neon glow, Arri Alexa cinematic color science, shallow depth of field with creamy optical bokeh.\n[Camera Movement]: Low-angle tracking shot transitioning smoothly to a high-speed Dutch angle tilt, cinematic 24fps motion blur with zero morphing or temporal flickering.",
        "prompt_content_en": "[Shot Description]: 35mm anamorphic cinema lens, f/1.8, master shot with continuous orbit camera movement.\n[Subject & Action]: [Character & continuous motion: e.g., A cyberpunk courier dashing through a rain-drenched alley, leaping across water puddles].\n[Physics & Dynamics]: Photorealistic surface reflections with physically accurate water ripple splashes, droplets refracting ambient lights, natural cloth drag.\n[Lighting & Palette]: Volumetric fog scattering amber streetlights and cyan neon, Arri Alexa color grade, shallow depth of field.\n[Camera Path]: Low-angle tracking shot transitioning smoothly into a high-speed Dutch angle, natural 24fps motion blur without temporal morphing.",
        "prompt_content": "[Shot Description]: 35mm anamorphic cinema lens, f/1.8, master shot with continuous orbit camera movement.\n[Subject & Action]: [主体角色与连续动作，例如：A cyberpunk neon-lit courier running through dense rainy alleys, leaping across a puddle].\n[Physics & Dynamics]: Photorealistic surface reflection with physically accurate water splash ripples, droplets refracting neon signs, natural cloth turbulence reacting to wind drag.\n[Lighting & Color Grade]: Volumetric mist scattering amber sodium lights and cyan neon glow, Arri Alexa cinematic color science, shallow depth of field with creamy optical bokeh.\n[Camera Movement]: Low-angle tracking shot transitioning smoothly to a high-speed Dutch angle tilt, cinematic 24fps motion blur with zero morphing or temporal flickering.",
        "tags": ["Sora 2", "Wan 2.1", "电影运镜", "视频生成"]
    },
    {
        "id": "prompt_openclaw_mcp_computer_agent",
        "sub_type": "agent",
        "model_family": "openclaw_agent",
        "purpose_zh": "🤖 自主智能体 · OpenClaw / MCP 协议多工具跨应用调度",
        "purpose_en": "🤖 Autonomous Agent · OpenClaw & MCP Multi-Tool Autonomous Orchestration",
        "title_zh": "💡【智能体架构】OpenClaw / MCP (Model Context Protocol) 自主 Agent 决策闭环与自愈重试咒语",
        "title_en": "💡 [Autonomous Agent Spec] OpenClaw / MCP Protocol Multi-Tool Orchestration & Resilient Self-Healing",
        "url": "https://modelcontextprotocol.io/",
        "image_url": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80&auto=format&fit=crop",
        "source": "智能体实验室",
        "author": "OpenClaw 架构组",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-14T18:00:00Z",
        "recommended_model": "Claude 3.7 / DeepSeek-V3 / OpenClaw Core",
        "temp_advice": "建议温度 0.2 | 生产级工具调用精确度",
        "metrics": {"type": "🤖 Agent智能体", "model": "Claude / OpenClaw", "temp": "0.2"},
        "content_snippet": "Production MCP agent system prompt with tool verification loops, fallback exception handling, and self-correcting task decomposition.",
        "summary_zh": "生产级 MCP 智能体系统提示词：内置工具调用前置校验、异常回滚降级策略与自主任务拆解循环。",
        "summary_en": "Production MCP agent system prompt with pre-call schema validation, resilient error rollback, and autonomous task decomposition.",
        "prompt_content_zh": "你是一个基于 MCP (Model Context Protocol) 运行的高可靠自主代理核心（Autonomous Agent Kernel）。你拥有文件系统读写、终端 Shell 执行与外部 REST API 调用的全部权限。\n【执行纪律】：\n1. 规划优先（ReAct 循环）：在调用任何写操作（破坏性操作）前，显式输出 Observation -> Thought -> Action -> Verification；\n2. 幂等与防御性重试：若工具返回错误代码，严禁机械重复调用。必须分析错误堆栈，更换入参或降级备用策略；\n3. 任务达成严格校验：执行完毕后必须主动调用只读工具检查产物真实状态，绝不允许凭空假设操作成功。\n\n【用户目标】：\n[在此处提供复杂的跨应用综合任务描述]",
        "prompt_content_en": "You are a High-Reliability Autonomous Agent Kernel operating over the Model Context Protocol (MCP). You have authorized access to filesystem operations, terminal execution, and external tool endpoints.\n[OPERATIONAL PROTOCOL]:\n1. Plan-Before-Action (ReAct Loop): Prior to destructive actions, output explicit Observation -> Thought -> Action -> Verification phases;\n2. Resilient Error Recovery: If a tool returns a non-zero exit code, do NOT repeat identical parameters. Analyze stack traces and implement fallback alternatives;\n3. Deterministic Verification: Validate end state using read-only probes before announcing completion.\n\n[USER MISSION]:\n[Provide complex multi-application goal here]",
        "prompt_content": "你是一个基于 MCP (Model Context Protocol) 运行的高可靠自主代理核心（Autonomous Agent Kernel）。你拥有文件系统读写、终端 Shell 执行与外部 REST API 调用的全部权限。\n【执行纪律】：\n1. 规划优先（ReAct 循环）：在调用任何写操作（破坏性操作）前，显式输出 Observation -> Thought -> Action -> Verification；\n2. 幂等与防御性重试：若工具返回错误代码，严禁机械重复调用。必须分析错误堆栈，更换入参或降级备用策略；\n3. 任务达成严格校验：执行完毕后必须主动调用只读工具检查产物真实状态，绝不允许凭空假设操作成功。\n\n【用户目标】：\n[在此处提供复杂的跨应用综合任务描述]",
        "tags": ["MCP协议", "OpenClaw", "自主智能体", "Computer Use"]
    },
    {
        "id": "prompt_claude_coding_architect",
        "sub_type": "coding",
        "purpose_zh": "💻 编码与架构 · 生产级重构与代码审查",
        "purpose_en": "💻 Coding & Architecture · Production Clean Code Audit",
        "title_zh": "💡【代码架构与重构】Claude 3.7 生产级 Clean Code 审查与防御性重构咒语",
        "title_en": "💡 [Code Architecture & Refactoring] Claude 3.7 Production Clean Code Audit System Prompt",
        "url": "https://docs.anthropic.com/",
        "image_url": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "工程实战",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 Sonnet / GPT-4o",
        "temp_advice": "建议温度 0.2 | 生产级代码严谨模式",
        "metrics": {"type": "💻 编码重构", "model": "Claude 3.7", "temp": "0.2"},
        "content_snippet": "Rigorous code auditor mode: Refactors code smells without breaking public API contracts, outputting benchmark diffs and unit tests.",
        "summary_zh": "严谨的代码审查官模式：在不打破现有 API 契约前提下重构代码异味，消除高并发竞态风险，输出防御性测试用例。",
        "summary_en": "Rigorous code auditor mode: Refactors code smells without breaking public API contracts, outputting benchmark diffs and unit tests.",
        "prompt_content_zh": "你是一位拥有 15 年经验的资深系统架构师与代码审查专家。请在严格遵守原有对外公共契约（Public API Contract）的前提下审查并重构以下代码：\n1. 识别代码异味（Code Smell）、隐性内存泄漏与高并发竞争冒险（Race Condition）；\n2. 采用现代设计模式与 SOLID 原则进行无破坏性重构，给出重构前后的 Diff 对比；\n3. 编写完整的防御性单元测试（含边界值、空指针与异常抛出用例）。",
        "prompt_content_en": "You are a Principal Systems Architect and Senior Code Reviewer with 15+ years of experience. Review and refactor the following code while strictly honoring existing public API contracts:\n1. Identify critical code smells, subtle memory leaks, and concurrency race conditions;\n2. Apply modern design patterns and SOLID principles for non-breaking refactoring, providing a before/after git diff;\n3. Generate comprehensive defensive unit tests covering edge cases, null pointers, and error handling paths.",
        "prompt_content": "你是一位拥有 15 年经验的资深系统架构师与代码审查专家。请在严格遵守原有对外公共契约（Public API Contract）的前提下审查并重构以下代码：\n1. 识别代码异味（Code Smell）、隐性内存泄漏与高并发竞争冒险（Race Condition）；\n2. 采用现代设计模式与 SOLID 原则进行无破坏性重构，给出重构前后的 Diff 对比；\n3. 编写完整的防御性单元测试（含边界值、空指针与异常抛出用例）。",
        "tags": ["代码重构", "高阶提示词", "Claude"]
    },
    {
        "id": "prompt_sql_performance_tuning",
        "sub_type": "coding",
        "purpose_zh": "💻 编码与架构 · 高并发 SQL 慢查询诊断调优",
        "purpose_en": "💻 Coding & Architecture · High-Concurrency SQL Query Tuning",
        "title_zh": "💡【数据库性能优化】高并发 SQL 慢查询诊断与执行计划重写优化模板",
        "title_en": "💡 [Database Performance] High-Concurrency SQL Slow Query Diagnosis & Plan Optimization",
        "url": "https://github.com/",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "DBA极客",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "DeepSeek-Coder-V2 / Claude 3.7",
        "temp_advice": "建议温度 0.1 | 数据库内核调优",
        "metrics": {"type": "💻 SQL调优", "model": "DeepSeek-Coder", "temp": "0.1"},
        "content_snippet": "Restructures queries on 10M+ row tables based on EXPLAIN ANALYZE, eliminating full-table scans with composite indexes.",
        "summary_zh": "根据 EXPLAIN 结果重构千万级表查询，消除全表扫描与临时表开销，生成最优复合索引建议。",
        "summary_en": "Restructures queries on 10M+ row tables based on EXPLAIN ANALYZE, eliminating full-table scans with composite indexes.",
        "prompt_content_zh": "你是一位顶级数据库性能调优 DBA 专家。以下是执行耗时过长的慢 SQL 语句及对应的 EXPLAIN ANALYZE 执行计划树：\n1. 指出导致性能下降的关键瓶颈（如全表扫描、Using filesort、Nested Loop 倾斜）；\n2. 重写 SQL 语句（利用延迟关联、覆盖索引、CTE 或子查询物化优化）；\n3. 给出精确到字段顺序的最优复合索引建议（考虑高区分度与最左前缀法则），并评估索引维护成本。",
        "prompt_content_en": "You are a Staff Database Administrator specializing in high-concurrency SQL optimization. Analyze the following slow SQL query along with its EXPLAIN ANALYZE execution plan:\n1. Pinpoint performance bottlenecks (e.g., table scans, temporary filesort, nested loop skew);\n2. Rewrite the query utilizing deferred joins, covering index optimization, or CTE materialization;\n3. Provide the exact composite index recommendation ordered by cardinality and leftmost prefix rules, estimating index maintenance overhead.",
        "prompt_content": "你是一位顶级数据库性能调优 DBA 专家。以下是执行耗时过长的慢 SQL 语句及对应的 EXPLAIN ANALYZE 执行计划树：\n1. 指出导致性能下降的关键瓶颈（如全表扫描、Using filesort、Nested Loop 倾斜）；\n2. 重写 SQL 语句（利用延迟关联、覆盖索引、CTE 或子查询物化优化）；\n3. 给出精确到字段顺序的最优复合索引建议（考虑高区分度与最左前缀法则），并评估索引维护成本。",
        "tags": ["SQL调优", "数据库实战", "Prompt模板"]
    },
    {
        "id": "prompt_react_ts_refactor",
        "sub_type": "coding",
        "purpose_zh": "💻 编码与架构 · React 19 / TypeScript 组件现代化",
        "purpose_en": "💻 Coding & Architecture · React 19 & TypeScript Modernization",
        "title_zh": "💡【全栈前端工程】React 19 Server Components 与 TypeScript 极限严格类型重构",
        "title_en": "💡 [Fullstack Frontend] React 19 Server Components & Strict TypeScript Refactoring",
        "url": "https://react.dev/",
        "image_url": "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "前端大牛",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 Sonnet / Cursor",
        "temp_advice": "建议温度 0.2 | 现代化组件范式",
        "metrics": {"type": "💻 React 19", "model": "Claude 3.7", "temp": "0.2"},
        "content_snippet": "Modernize legacy React codebase with React 19 Actions, Server Components, and zero-any TypeScript generics.",
        "summary_zh": "将遗留 React 代码迁移至 React 19 Actions、use 钩子与服务端组件，消灭 any，构建端到端类型安全体系。",
        "summary_en": "Modernize legacy React codebase with React 19 Actions, Server Components, and zero-any TypeScript generics.",
        "prompt_content_zh": "请扮演一位精通 React 19 与 TypeScript 5.5+ 的前端资深工程总监。请重构提供的遗留组件：\n1. 将过时的 useEffect 数据拉取与冗余状态迁移至 React 19 原生 Actions、useActionState 与 Server Components；\n2. 实现 100% 严格类型推导，严禁使用 `any`，合理运用泛型约束、Discriminated Unions 与 const 泛型；\n3. 优化渲染性能：防止不必要的 re-render，并添加 Suspense 骨架屏与 ErrorBoundary 容错保护。",
        "prompt_content_en": "Act as a Principal Frontend Engineer specializing in React 19 and TypeScript 5.5+. Refactor the provided legacy component:\n1. Migrate outdated useEffect data fetching and boilerplate state to React 19 Actions, useActionState, and React Server Components;\n2. Enforce 100% strict type safety: eliminate `any`, leverage discriminated unions, branded types, and const type parameters;\n3. Optimize rendering: eliminate unnecessary re-renders, adding proper Suspense fallback skeletons and resilient Error Boundaries.",
        "prompt_content": "请扮演一位精通 React 19 与 TypeScript 5.5+ 的前端资深工程总监。请重构提供的遗留组件：\n1. 将过时的 useEffect 数据拉取与冗余状态迁移至 React 19 原生 Actions、useActionState 与 Server Components；\n2. 实现 100% 严格类型推导，严禁使用 `any`，合理运用泛型约束、Discriminated Unions 与 const 泛型；\n3. 优化渲染性能：防止不必要的 re-render，并添加 Suspense 骨架屏与 ErrorBoundary 容错保护。",
        "tags": ["React19", "TypeScript", "前端重构"]
    },
    {
        "id": "prompt_unit_test_coverage",
        "sub_type": "coding",
        "purpose_zh": "💻 编码与架构 · 自动化单测生成与极限覆盖",
        "purpose_en": "💻 Coding & Architecture · Automated High-Coverage Unit Testing",
        "title_zh": "💡【质量工程自动化】100% 边界条件覆盖与变异测试（Mutation Testing）用例生成",
        "title_en": "💡 [Quality Engineering] 100% Edge-Case Coverage & Mutation-Resilient Test Suite Generator",
        "url": "https://pytest.org/",
        "image_url": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "测试极客",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / GPT-4o",
        "temp_advice": "建议温度 0.1 | 严格测试用例模式",
        "metrics": {"type": "💻 测试套件", "model": "Claude 3.7", "temp": "0.1"},
        "content_snippet": "Generates hermetic, parameterized unit tests covering null pointers, concurrency races, and malicious payload fuzzing.",
        "summary_zh": "生成密封、参数化的测试套件，全面覆盖空指针、整数溢出、高并发死锁与恶意输入模糊测试。",
        "summary_en": "Generates hermetic, parameterized unit tests covering null pointers, concurrency races, and malicious payload fuzzing.",
        "prompt_content_zh": "你是一位狂热的质量工程与测试架构专家。请为提供的目标代码编写完备的自动化测试套件：\n1. 使用参数化测试（Parameterized Tests）覆盖全量正常业务路径；\n2. 针对极端边界生成用例：包含空指针、超大负数、整数溢出、零长度切片、特殊字符注入及超时熔断；\n3. 设计能够杀死变异体（Mutation Testing）的断言，禁止无效的无断言测试；\n4. 所有外部依赖必须通过 Mock/Stub 隔离，确保单测可在 CI 环境中无网络毫秒级运行。",
        "prompt_content_en": "You are a Staff QA Architect and Mutation Testing specialist. Build a production-grade automated test suite for the provided code:\n1. Use parameterized testing to systematically cover happy paths and common branches;\n2. Generate rigorous edge-case suites: null references, integer overflow, empty collections, unicode injection, and network timeouts;\n3. Implement strong assertions capable of surviving mutation testing (no vanity tests);\n4. Hermetically isolate all external I/O via mocks/stubs to guarantee sub-millisecond execution in isolated CI pipelines.",
        "prompt_content": "你是一位狂热的质量工程与测试架构专家。请为提供的目标代码编写完备的自动化测试套件：\n1. 使用参数化测试（Parameterized Tests）覆盖全量正常业务路径；\n2. 针对极端边界生成用例：包含空指针、超大负数、整数溢出、零长度切片、特殊字符注入及超时熔断；\n3. 设计能够杀死变异体（Mutation Testing）的断言，禁止无效的无断言测试；\n4. 所有外部依赖必须通过 Mock/Stub 隔离，确保单测可在 CI 环境中无网络毫秒级运行。",
        "tags": ["单测覆盖", "测试工程", "质量保障"]
    },

    # 2. 🎨 图像生成 (image_gen)
    {
        "id": "prompt_sd35_photoreal",
        "sub_type": "image_gen",
        "purpose_zh": "🎨 图像生成 · 顶级商业人像与胶片摄影",
        "purpose_en": "🎨 Image Gen · High-End Commercial Studio Portraiture",
        "title_zh": "💡【商业摄影大师】Midjourney v7 / Ideogram 3 / SD 3.5 顶级商业摄影质感与皮肤微孔真实感神咒",
        "title_en": "💡 [Commercial Studio Photography] SD 3.5 Large & Midjourney Photorealistic Skin Texture Master Prompt",
        "url": "https://midjourney.com/",
        "image_url": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "视觉实测",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Midjourney v7 / Ideogram 3 / SD 3.5",
        "temp_advice": "Guidance Scale: 3.5 | 步数 28",
        "metrics": {"type": "🎨 商业生图", "model": "Midjourney v7", "temp": "CFG 3.5"},
        "content_snippet": "85mm f/1.4 lens bokeh, Hasselblad film grain and Tyndall morning light for photorealistic portraiture without plastic AI artifacts.",
        "summary_zh": "85mm f/1.4 镜头虚化、哈苏中画幅胶片微颗粒与晨光丁达尔效应，彻底告别 AI 塑料感与假脸。",
        "summary_en": "85mm f/1.4 lens bokeh, Hasselblad film grain and Tyndall morning light for photorealistic portraiture without plastic AI artifacts.",
        "prompt_content_zh": "A high-end cinematic editorial portrait of [SUBJECT], shot on 35mm kodak portra 400 film, Hasselblad H6D-100c camera, 85mm f/1.4 lens, soft natural morning rim light, subtle cinematic lens flare, hyper-realistic pores and skin imperfections, fine hair strands, depth of field, 8k resolution, award-winning photography --ar 16:9 --style raw --v 6.1\n\n【中文使用解析】：将 [SUBJECT] 替换为你的目标人物（例如：a charismatic 35-year-old female neuroscientist with silver round glasses）。保持原英文提示词以确保扩散模型最高质量的 CLIP 嵌入响应。",
        "prompt_content_en": "A high-end cinematic editorial portrait of [SUBJECT], shot on 35mm kodak portra 400 film, Hasselblad H6D-100c camera, 85mm f/1.4 lens, soft natural morning rim light, subtle cinematic lens flare, hyper-realistic pores and skin imperfections, fine hair strands, depth of field, 8k resolution, award-winning photography --ar 16:9 --style raw --v 6.1",
        "prompt_content": "A high-end cinematic editorial portrait of [SUBJECT], shot on 35mm kodak portra 400 film, Hasselblad H6D-100c camera, 85mm f/1.4 lens, soft natural morning rim light, subtle cinematic lens flare, hyper-realistic pores and skin imperfections, fine hair strands, depth of field, 8k resolution, award-winning photography --ar 16:9 --style raw --v 6.1",
        "tags": ["生图神咒", "Midjourney/SD3.5", "商业摄影"]
    },
    {
        "id": "prompt_cyberpunk_concept",
        "sub_type": "image_gen",
        "purpose_zh": "🎨 图像生成 · 科幻世界观与电影级概念美术",
        "purpose_en": "🎨 Image Gen · Sci-Fi Worldbuilding & Cinematic Concept Art",
        "title_zh": "💡【电影概念美术】赛博朋克与科幻史诗世界观：体积雾光与巨物工业美学",
        "title_en": "💡 [Cinematic Concept Art] Cyberpunk Mega-Structures & Volumetric Atmospheric Lighting",
        "url": "https://midjourney.com/",
        "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "概念设计师",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Midjourney v7 / SD 3.5 Large",
        "temp_advice": "Stylize: 250 | --ar 21:9",
        "metrics": {"type": "🎨 概念美术", "model": "Midjourney v6", "temp": "s 250"},
        "content_snippet": "Brutalist megastructure cityscape, volumetric neon smog, rain-slicked asphalt reflections, cinematic widescreen composition.",
        "summary_zh": "野兽派巨构建筑天际线、体积霓虹晨雾、雨后沥青漫反射与 21:9 超宽银幕电影构图。",
        "summary_en": "Brutalist megastructure cityscape, volumetric neon smog, rain-slicked asphalt reflections, cinematic widescreen composition.",
        "prompt_content_zh": "Cinematic wide-angle establishing shot of a towering brutalist dystopian megacity, retro-futuristic cyberpunk architecture, layers of neon holographic billboards piercing through heavy volumetric smog and acid rain, reflective wet asphalt streets with neon puddles, dense flying vehicle traffic in low altitude, blade runner 2049 aesthetic, directed by Denis Villeneuve, shot by Roger Deakins on ARRI Alexa 65, 8k resolution, anamorphic lens --ar 21:9 --style raw --v 6.1\n\n【中文使用解析】：适用于影视分镜、游戏概念原画设计。通过 Roger Deakins 摄影风格与宽银幕变形镜头（anamorphic lens）极大提升空间压迫感与层次感。",
        "prompt_content_en": "Cinematic wide-angle establishing shot of a towering brutalist dystopian megacity, retro-futuristic cyberpunk architecture, layers of neon holographic billboards piercing through heavy volumetric smog and acid rain, reflective wet asphalt streets with neon puddles, dense flying vehicle traffic in low altitude, blade runner 2049 aesthetic, directed by Denis Villeneuve, shot by Roger Deakins on ARRI Alexa 65, 8k resolution, anamorphic lens --ar 21:9 --style raw --v 6.1",
        "prompt_content": "Cinematic wide-angle establishing shot of a towering brutalist dystopian megacity, retro-futuristic cyberpunk architecture, layers of neon holographic billboards piercing through heavy volumetric smog and acid rain, reflective wet asphalt streets with neon puddles, dense flying vehicle traffic in low altitude, blade runner 2049 aesthetic, directed by Denis Villeneuve, shot by Roger Deakins on ARRI Alexa 65, 8k resolution, anamorphic lens --ar 21:9 --style raw --v 6.1",
        "tags": ["赛博朋克", "概念艺术", "Midjourney"]
    },
    {
        "id": "prompt_ui_design_concept",
        "sub_type": "image_gen",
        "purpose_zh": "🎨 图像生成 · 极简现代 UI/App 设计系统",
        "purpose_en": "🎨 Image Gen · Modern Minimalist UI & App Design System",
        "title_zh": "💡【UI/UX 视觉探索】Dribbble 爆款极简毛玻璃卡片与深色现代 App 界面概念",
        "title_en": "💡 [UI/UX Visual Exploration] Dribbble-Trending Glassmorphism & Dark Mode Mobile App Concept",
        "url": "https://dribbble.com/",
        "image_url": "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "UI设计圈",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Midjourney v7 / SD 3.5 Large",
        "temp_advice": "Stylize: 100 | Clean UI",
        "metrics": {"type": "🎨 UI概念", "model": "Midjourney v6", "temp": "s 100"},
        "content_snippet": "Modern fintech mobile UI dashboard, sleek glassmorphism panels, subtle gradient curves, clean typography, Dribbble UI showcase.",
        "summary_zh": "现代金融与 AI 仪表盘设计：精致半透明毛玻璃面板、柔和环境渐变与高阶版式留白。",
        "summary_en": "Modern fintech mobile UI dashboard, sleek glassmorphism panels, subtle gradient curves, clean typography, Dribbble UI showcase.",
        "prompt_content_zh": "A modern, ultra-clean mobile app interface design for an AI personal assistant dashboard, dark mode, sleek glassmorphism UI components, glowing neon purple and emerald gradient accents, elegant SF Pro typography, minimalist data visualization widgets, isometric floating presentation, trending on Dribbble and Behance, Figma vector design, high fidelity, 8k --ar 16:9 --v 6.1\n\n【中文使用解析】：用于快速生成产品原型提案、投资人 Pitch Deck 界面效果图。规避杂乱按钮，突出核心数据卡片与精致微光动势。",
        "prompt_content_en": "A modern, ultra-clean mobile app interface design for an AI personal assistant dashboard, dark mode, sleek glassmorphism UI components, glowing neon purple and emerald gradient accents, elegant SF Pro typography, minimalist data visualization widgets, isometric floating presentation, trending on Dribbble and Behance, Figma vector design, high fidelity, 8k --ar 16:9 --v 6.1",
        "prompt_content": "A modern, ultra-clean mobile app interface design for an AI personal assistant dashboard, dark mode, sleek glassmorphism UI components, glowing neon purple and emerald gradient accents, elegant SF Pro typography, minimalist data visualization widgets, isometric floating presentation, trending on Dribbble and Behance, Figma vector design, high fidelity, 8k --ar 16:9 --v 6.1",
        "tags": ["UI设计", "Dribbble风格", "App界面"]
    },
    {
        "id": "prompt_3d_clay_character",
        "sub_type": "image_gen",
        "purpose_zh": "🎨 图像生成 · 3D 黏土拟真与盲盒潮玩角色",
        "purpose_en": "🎨 Image Gen · 3D Claymation & Blindbox Mascot Character",
        "title_zh": "💡【3D 潮玩设计】C4D 渲染级黏土盲盒公仔与拟真微距景深咒语",
        "title_en": "💡 [3D Mascot Design] C4D-Rendered Clay Toy Figure & Macro Depth-of-Field Prompt",
        "url": "https://blackforestlabs.ai/",
        "image_url": "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "3D创作者",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Midjourney v7 / Ideogram 3",
        "temp_advice": "Guidance: 3.0 | 柔和黏土光",
        "metrics": {"type": "🎨 3D潮玩", "model": "SD 3.5 Large", "temp": "CFG 3.0"},
        "content_snippet": "Cute 3D claymation robot mascot, fingerprint textures on plasticine, soft studio lighting, Octane render, isometric angle.",
        "summary_zh": "萌系 3D 橡皮泥小机器人吉祥物：带真实手捏微指纹质感、柔和摄影棚三点布光与 Octane 级渲染。",
        "summary_en": "Cute 3D claymation robot mascot, fingerprint textures on plasticine, soft studio lighting, Octane render, isometric angle.",
        "prompt_content_zh": "Cute futuristic AI robot mascot character, handcrafted colorful polymer clay texture, subtle handcrafted fingerprint imperfections on the plasticine surface, soft rounded edges, glossy black button eyes, studio lighting setup with soft key light and pink rim light, shallow depth of field, Octane render, Cinema 4D, 3D blender art, miniature diorama scale, pastel color palette --ar 1:1 --v 6.1\n\n【中文使用解析】：专为品牌 IP、吉祥物衍生品、盲盒周边或 App 引导页打造，指纹与手作质感能极大消解 3D 渲染的冷硬感。",
        "prompt_content_en": "Cute futuristic AI robot mascot character, handcrafted colorful polymer clay texture, subtle handcrafted fingerprint imperfections on the plasticine surface, soft rounded edges, glossy black button eyes, studio lighting setup with soft key light and pink rim light, shallow depth of field, Octane render, Cinema 4D, 3D blender art, miniature diorama scale, pastel color palette --ar 1:1 --v 6.1",
        "prompt_content": "Cute futuristic AI robot mascot character, handcrafted colorful polymer clay texture, subtle handcrafted fingerprint imperfections on the plasticine surface, soft rounded edges, glossy black button eyes, studio lighting setup with soft key light and pink rim light, shallow depth of field, Octane render, Cinema 4D, 3D blender art, miniature diorama scale, pastel color palette --ar 1:1 --v 6.1",
        "tags": ["3D盲盒", "黏土风", "IP设计"]
    },

    # 3. 🎥 视频生成 (video_gen)
    {
        "id": "prompt_video_cinematic_lens",
        "sub_type": "video_gen",
        "purpose_zh": "🎥 视频生成 · 影视级镜头语言与多角度运镜",
        "purpose_en": "🎥 Video Gen · Cinematic Camera Movement & Lens Control",
        "title_zh": "💡【AI 视频运镜大师】Sora / Kling / Runway Gen-3 希区柯克变焦与无人机航拍复合提示词",
        "title_en": "💡 [Cinematic Camera Movement] Sora & Kling Vertigo Dolly Zoom & FPV Drone Master Prompt",
        "url": "https://runwayml.com/",
        "image_url": "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "影视极客",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Runway Gen-3 / Sora / Kling",
        "temp_advice": "Motion Scale: 5 | 严格运镜控制",
        "metrics": {"type": "🎥 视频运镜", "model": "Gen-3 / Kling", "temp": "Motion 5"},
        "content_snippet": "Dolly zoom (vertigo effect), seamless camera transition from high-altitude aerial FPV dive to intimate eye-level portrait.",
        "summary_zh": "希区柯克式反向推拉变焦：从千米高空穿云俯冲无缝衔接至主角面部微表情，运镜丝滑无形变。",
        "summary_en": "Dolly zoom (vertigo effect), seamless camera transition from high-altitude aerial FPV dive to intimate eye-level portrait.",
        "prompt_content_zh": "Cinematic camera movement: Vertigo effect dolly zoom. The camera slowly pushes forward while simultaneously zooming out, creating intense background perspective distortion while the solitary traveler standing at the edge of a sheer mountain cliff remains perfectly stationary. Golden hour backlighting, subtle wind blowing through jacket fabric, volumetric clouds swirling in the gorge below. Hyper-fluid 60fps motion, zero morphological jitter, photorealistic cinema grade.\n\n【中文使用解析】：专为 Runway Gen-3 Alpha 或 Kling 1.5 的 Text-to-Video / Image-to-Video 设计。重点定义镜头物理轨迹（dolly zoom / push forward / zoom out）以约束物理引擎不会乱造多余肢体。",
        "prompt_content_en": "Cinematic camera movement: Vertigo effect dolly zoom. The camera slowly pushes forward while simultaneously zooming out, creating intense background perspective distortion while the solitary traveler standing at the edge of a sheer mountain cliff remains perfectly stationary. Golden hour backlighting, subtle wind blowing through jacket fabric, volumetric clouds swirling in the gorge below. Hyper-fluid 60fps motion, zero morphological jitter, photorealistic cinema grade.",
        "prompt_content": "Cinematic camera movement: Vertigo effect dolly zoom. The camera slowly pushes forward while simultaneously zooming out, creating intense background perspective distortion while the solitary traveler standing at the edge of a sheer mountain cliff remains perfectly stationary. Golden hour backlighting, subtle wind blowing through jacket fabric, volumetric clouds swirling in the gorge below. Hyper-fluid 60fps motion, zero morphological jitter, photorealistic cinema grade.",
        "tags": ["视频运镜", "Runway", "影视质感"]
    },
    {
        "id": "prompt_video_product_macro",
        "sub_type": "video_gen",
        "purpose_zh": "🎥 视频生成 · 商业广告级流体光影微距特写",
        "purpose_en": "🎥 Video Gen · Commercial Macro Liquid & Product Showcase",
        "title_zh": "💡【商业广告大片】高端腕表与流体水珠高帧率慢动作微距运镜咒语",
        "title_en": "💡 [Luxury Commercial Video] High-End Watch & Macro Liquid Droplets Slow-Mo Showcase",
        "url": "https://klingai.com/",
        "image_url": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "广告视效",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Kling 1.5 / Sora / Luma Dream",
        "temp_advice": "Motion: 3 | 极致慢动作",
        "metrics": {"type": "🎥 商业广告", "model": "Kling 1.5", "temp": "Motion 3"},
        "content_snippet": "Extreme macro 1000fps slow-motion water splash over rotating titanium luxury watch, caustics refractions and prism light.",
        "summary_zh": "1000fps 极速慢动作微距水花飞溅、钛合金表盘精密齿轮咬合与焦散光斑漫反射。",
        "summary_en": "Extreme macro 1000fps slow-motion water splash over rotating titanium luxury watch, caustics refractions and prism light.",
        "prompt_content_zh": "Macro commercial product video: Extreme close-up of a sleek titanium chronograph watch slowly rotating submerged in crystal-clear water. A burst of microscopic air bubbles and water ripples glides past the sapphire crystal glass at 1000fps phantom slow motion. Studio rim light catching metallic bevels, prismatic caustic light patterns dancing across the dial, pristine optical clarity, zero blur, luxury Apple/Rolex aesthetic.\n\n【中文使用解析】：适用于高端 3C 数码、香水、珠宝首饰等出海广告视频一键生成。通过限定 phantom slow motion 与 caustic light patterns 获得极具说服力的物理渲染感。",
        "prompt_content_en": "Macro commercial product video: Extreme close-up of a sleek titanium chronograph watch slowly rotating submerged in crystal-clear water. A burst of microscopic air bubbles and water ripples glides past the sapphire crystal glass at 1000fps phantom slow motion. Studio rim light catching metallic bevels, prismatic caustic light patterns dancing across the dial, pristine optical clarity, zero blur, luxury Apple/Rolex aesthetic.",
        "prompt_content": "Macro commercial product video: Extreme close-up of a sleek titanium chronograph watch slowly rotating submerged in crystal-clear water. A burst of microscopic air bubbles and water ripples glides past the sapphire crystal glass at 1000fps phantom slow motion. Studio rim light catching metallic bevels, prismatic caustic light patterns dancing across the dial, pristine optical clarity, zero blur, luxury Apple/Rolex aesthetic.",
        "tags": ["商业广告", "流体慢动作", "快手可灵"]
    },

    # 4. 🧠 深度推理 (reasoning)
    {
        "id": "prompt_deepseek_reasoning",
        "sub_type": "reasoning",
        "purpose_zh": "🧠 深度推理 · 长思考链拆解与反思式推演",
        "purpose_en": "🧠 Deep Reasoning · Extended Logic Decoupling & Reflection",
        "title_zh": "💡【极限长思考链】DeepSeek-R1 / o3 深度思考极客解锁模板：开启极致多步反思",
        "title_en": "💡 [Extended Logic Chains] DeepSeek-R1 & o3 Deep Reasoning Decoupling & Reflection Prompt",
        "url": "https://github.com/deepseek-ai/DeepSeek-R1",
        "image_url": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "社区实测",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "DeepSeek-R1 / OpenAI o3-mini",
        "temp_advice": "建议温度 0.6 | reasoning_effort: high",
        "metrics": {"type": "🧠 深度推理", "model": "DeepSeek-R1", "temp": "0.6"},
        "content_snippet": "Forces LLMs to expand reflexive chain-of-thought, examine boundary conditions, and test assumptions.",
        "summary_zh": "强制模型展开反思性长推理链，分析核心痛点、权衡多方案优劣，并列出边界条件与可能漏洞。",
        "summary_en": "Forces LLMs to expand reflexive chain-of-thought, examine boundary conditions, and test assumptions.",
        "prompt_content_zh": "请不要直接给出结论。请以资深算法架构师兼批判性学者的身份，使用步骤分解法展开深度思考：\n1. 剖析底层核心痛点与数学本质；\n2. 横向权衡至少三种架构方案的性能与成本边界；\n3. 列出所有隐性假设与极端边界可能引发的故障点；\n4. 给出包含生产级代码与自动化验证清单的最终交付结果。",
        "prompt_content_en": "Do not jump straight to the conclusion. Adopt the persona of a Principal Algorithm Architect and Critical Theorist, expanding your chain of thought step by step:\n1. Deconstruct the underlying root problem into its mathematical and systemic essence;\n2. Benchmark at least three distinct architecture paradigms across latency, scale, and compute trade-offs;\n3. Rigorously falsify assumptions and uncover failure modes at extreme boundary conditions;\n4. Deliver production-ready code alongside a concrete verification checklist.",
        "prompt_content": "请不要直接给出结论。请以资深架构师兼批判性学者的身份，使用步骤分解法展开深度思考：\n1. 剖析底层核心痛点与数学本质；\n2. 横向权衡至少三种架构方案的性能与成本边界；\n3. 列出所有隐性假设与极端边界可能引发的故障点；\n4. 给出包含生产级代码与自动化验证清单的最终交付结果。",
        "tags": ["Prompt神咒", "逻辑推理", "DeepSeek"]
    },
    {
        "id": "prompt_first_principles_reasoning",
        "sub_type": "reasoning",
        "purpose_zh": "🧠 深度推理 · 第一性原理穿透与战略决断",
        "purpose_en": "🧠 Deep Reasoning · First-Principles Strategic Deduction",
        "title_zh": "💡【第一性原理】马斯克式底层拆解：剥离行业惯性直击物理与商业极限",
        "title_en": "💡 [First Principles Thinking] Elon-Style Ground-Up Physics & Cost Breakdown",
        "url": "https://x.com/elonmusk",
        "image_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "战略极客",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / o3-mini",
        "temp_advice": "建议温度 0.4 | 第一性原理推演",
        "metrics": {"type": "🧠 战略推演", "model": "Claude 3.7", "temp": "0.4"},
        "content_snippet": "Strips away historical analogies, reducing the problem to raw physics and unit economics to find 10x breakthrough paths.",
        "summary_zh": "剥离行业类比与路径依赖，将问题还原至物理定律与原子级物料成本，推导 10 倍效能的破局路径。",
        "summary_en": "Strips away historical analogies, reducing the problem to raw physics and unit economics to find 10x breakthrough paths.",
        "prompt_content_zh": "请暂时忘掉行业现有的所有‘行业惯例’与‘常规做法’。运用绝对的第一性原理（First Principles）审视以下命题：\n1. 这个系统最根本、不可违背的基础科学定律（如热力学、香农信息论、计算复杂度）是什么？\n2. 若将整个产品拆解为原子级的原材料成本与基础能源成本，理论极限底线是多少？现有成本的溢价主要被哪些中间低效层吃掉了？\n3. 颠覆现有行业做法、重构整个价值流并实现成本降低 80% 以上的激进方案是什么？列出三个最关键的试错实验。",
        "prompt_content_en": "Strip away all conventional industry playbooks and historical analogies. Scrutinize the following challenge purely through First Principles:\n1. What are the immutable fundamental laws of science (e.g. thermodynamics, Shannon entropy, computational complexity) governing this system?\n2. Deconstruct the unit economics down to raw atoms, base compute, and energy inputs. Where does the 10x margin inefficiency currently leak?\n3. Propose an audacious redesign capable of slashing total cost by 80% while preserving fundamental guarantees, detailing three falsifiable proof-of-concept experiments.",
        "prompt_content": "请暂时忘掉行业现有的所有‘行业惯例’与‘常规做法’。运用绝对的第一性原理（First Principles）审视以下命题：\n1. 这个系统最根本、不可违背的基础科学定律（如热力学、香农信息论、计算复杂度）是什么？\n2. 若将整个产品拆解为原子级的原材料成本与基础能源成本，理论极限底线是多少？现有成本的溢价主要被哪些中间低效层吃掉了？\n3. 颠覆现有行业做法、重构整个价值流并实现成本降低 80% 以上的激进方案是什么？列出三个最关键的试错实验。",
        "tags": ["第一性原理", "商业战略", "深度思考"]
    },

    # 5. 🔬 学术科研 (research)
    {
        "id": "prompt_arxiv_deep_dive",
        "sub_type": "research",
        "purpose_zh": "🔬 学术科研 · 前沿顶会论文 5 步穿透精读",
        "purpose_en": "🔬 Research & Papers · 5-Step ArXiv Paper Penetration",
        "title_zh": "💡【论文极客精读】前沿顶会论文 5 步穿透精读与单卡复现阻碍评估模板",
        "title_en": "💡 [Paper Deep Dive] ArXiv 5-Step Paper Penetration & RTX 4090 Reproduction Bottleneck Audit",
        "url": "https://arxiv.org/",
        "image_url": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "科研极客",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / Gemini 1.5 Pro",
        "temp_advice": "建议温度 0.3 | 极客文献精读",
        "metrics": {"type": "🔬 论文拆解", "model": "Gemini 1.5 Pro", "temp": "0.3"},
        "content_snippet": "Pierces academic hyperbole to extract core mathematical axioms, baseline discrepancies, and RTX 4090 reproduction bottlenecks.",
        "summary_zh": "穿透学术论文华丽包装，直击数学形式化定义、核心假设脆弱性与开源单卡复现阻碍。",
        "summary_en": "Pierces academic hyperbole to extract core mathematical axioms, baseline discrepancies, and RTX 4090 reproduction bottlenecks.",
        "prompt_content_zh": "请作为该领域的顶级同行评审专家，用极客实战视角深度解剖附带的这篇论文：\n1. 用一句话说清楚作者解决的核心科学矛盾；\n2. 剥离作者自我夸大的修辞，指出其算法最根本的 Baseline 对比是否存在水分；\n3. 提取算法伪代码与核心公式的物理直觉解释；\n4. 评估若在本地单卡（如 RTX 4090）进行复现，面临的最大显存/数据瓶颈及工程应对方案。",
        "prompt_content_en": "Act as an elite peer reviewer with a hands-on hacker mindset. Dissect the attached research paper:\n1. State in a single crisp sentence the fundamental scientific bottleneck the authors tackled;\n2. Strip away marketing hyperbole: did the authors cherry-pick weak baselines or obscure compute training budgets?\n3. Provide the intuitive physics behind the core equations alongside cleanly structured algorithm pseudocode;\n4. Audit reproduction feasibility on a single consumer GPU (e.g. RTX 4090): identify memory bottlenecks and propose practical mitigation hacks.",
        "prompt_content": "请作为该领域的顶级同行评审专家，用极客实战视角深度解剖附带的这篇论文：\n1. 用一句话说清楚作者解决的核心科学矛盾；\n2. 剥离作者自我夸大的修辞，指出其算法最根本的 Baseline 对比是否存在水分；\n3. 提取算法伪代码与核心公式的物理直觉解释；\n4. 评估若在本地单卡（如 RTX 4090）进行复现，面临的最大显存/数据瓶颈及工程应对方案。",
        "tags": ["论文精读", "科研拆解", "Prompt神咒"]
    },
    {
        "id": "prompt_math_pseudocode_derivation",
        "sub_type": "research",
        "purpose_zh": "🔬 学术科研 · 复杂数学公式向 PyTorch 向量化代码翻译",
        "purpose_en": "🔬 Research & Papers · Math Formula to PyTorch Vectorized Code",
        "title_zh": "💡【算法公式转代码】晦涩数学符号向无循环 PyTorch 张量操作对齐翻译模板",
        "title_en": "💡 [Math to Code] Mathematical Notation to High-Performance Vectorized PyTorch Translation",
        "url": "https://pytorch.org/",
        "image_url": "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "算法工程师",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / DeepSeek-R1",
        "temp_advice": "建议温度 0.1 | 严格张量维度匹配",
        "metrics": {"type": "🔬 公式转代码", "model": "Claude 3.7", "temp": "0.1"},
        "content_snippet": "Converts dense paper LaTeX equations into vectorized, memory-efficient PyTorch operations with shape assertions.",
        "summary_zh": "将密集 LaTeX 公式转为零 Python for 循环的高性能 PyTorch 张量操作，并附带完整的 Tensor Shape 断言注释。",
        "summary_en": "Converts dense paper LaTeX equations into vectorized, memory-efficient PyTorch operations with shape assertions.",
        "prompt_content_zh": "你是一位兼具应用数学博士学位与顶级深度学习框架优化经验的算法工程师。请将以下论文中的 LaTeX 数学公式翻译为高质量的 PyTorch 实现：\n1. 逐一解释公式中各标量、向量与张量上下标的精确几何与物理含义；\n2. 编写无 Python 原生 for 循环的高性能向量化代码（善用 torch.einsum, bmm, 或 broadcast 广播机制）；\n3. 在每行关键张量操作后标注显式的 Shape 注释（如 `# [Batch, Heads, Seq_Len, Dim]`），并加入数值稳定性保护（如防除以零的 eps 与 log-sum-exp 技巧）。",
        "prompt_content_en": "You are a Deep Learning Systems Engineer with a Ph.D. in Applied Mathematics. Convert the following LaTeX equation into clean, high-performance PyTorch code:\n1. Unpack all tensor indices, superscripts, and summation bounds into plain physical intuition;\n2. Implement a zero-python-loop vectorized module leveraging torch.einsum, batched matmul, or broadcast primitives;\n3. Annotate every intermediate step with strict tensor shape comments (e.g. `# [B, H, S, D]`) and integrate numerical stability safeguards (eps clamping, log-sum-exp stabilization).",
        "prompt_content": "你是一位兼具应用数学博士学位与顶级深度学习框架优化经验的算法工程师。请将以下论文中的 LaTeX 数学公式翻译为高质量的 PyTorch 实现：\n1. 逐一解释公式中各标量、向量与张量上下标的精确几何与物理含义；\n2. 编写无 Python 原生 for 循环的高性能向量化代码（善用 torch.einsum, bmm, 或 broadcast 广播机制）；\n3. 在每行关键张量操作后标注显式的 Shape 注释（如 `# [Batch, Heads, Seq_Len, Dim]`），并加入数值稳定性保护（如防除以零的 eps 与 log-sum-exp 技巧）。",
        "tags": ["数学公式", "PyTorch", "张量运算"]
    },

    # 6. 🤖 智能体与MCP (agent)
    {
        "id": "prompt_agent_robust_tools",
        "sub_type": "agent",
        "purpose_zh": "🤖 智能体与MCP · 工业级工具调用鲁棒性与防死锁守门员",
        "purpose_en": "🤖 Agents & MCP · Industrial Tool-Use Robustness & Deadlock Guardrail",
        "title_zh": "💡【Agent 防御系统】Anthropic MCP 工具调用鲁棒性校验与防胡言乱语系统指令",
        "title_en": "💡 [Agent Defense System] Anthropic MCP Robust Tool-Use & Anti-Hallucination Guardrail Prompt",
        "url": "https://modelcontextprotocol.io/",
        "image_url": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "Agent开发",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.5/3.7 Sonnet / GPT-4o",
        "temp_advice": "建议温度 0.1 | 严格结构化 JSON 模式",
        "metrics": {"type": "🤖 MCP智能体", "model": "Claude 3.7", "temp": "0.1"},
        "content_snippet": "Defensive prompt directives for autonomous agent systems to prevent tool invocation hallucinations, loop deadlocks, and invalid arguments.",
        "summary_zh": "构建工业级智能体系统的防御性指令，防止工具调用幻觉、循环死锁与无效入参参数。",
        "summary_en": "Defensive prompt directives for autonomous agent systems to prevent tool invocation hallucinations, loop deadlocks, and invalid arguments.",
        "prompt_content_zh": "【系统约束】：你是一个受限执行环境中的自治 Agent。\n1. 在调用任何工具前，必须输出 <preflight> 检验入参字段的类型与合法性；\n2. 严禁捏造未声明在 Tool Registry 中的虚构工具函数；\n3. 若连续两次工具返回报错，立即终止盲目重试，进入 <diagnosis> 模式回溯上一轮输入并向人类汇报根因；\n4. 最终响应仅通过标准工具或结构化 JSON schema 返回，禁止携带任何 markdown 闲聊闲扯。",
        "prompt_content_en": "[System Directives]: You are an autonomous agent operating within a secure execution sandbox.\n1. Before dispatching any external tool, output a strict <preflight> checking parameter types and constraint schemas;\n2. Under no circumstances should you hallucinate or fabricate function names outside the registered tool registry;\n3. If a tool fails twice consecutively, immediately cease execution loops, enter <diagnosis> mode, and surface the root error trace to the user;\n4. Deliver final artifacts exclusively via deterministic tool payloads or compliant JSON schema, without conversational chatter.",
        "prompt_content": "【系统约束】：你是一个受限执行环境中的自治 Agent。\n1. 在调用任何工具前，必须输出 <preflight> 检验入参字段的类型与合法性；\n2. 严禁捏造未声明在 Tool Registry 中的虚构工具函数；\n3. 若连续两次工具返回报错，立即终止盲目重试，进入 <diagnosis> 模式回溯上一轮输入并向人类汇报根因；\n4. 最终响应仅通过标准工具或结构化 JSON schema 返回，禁止携带任何 markdown 闲聊闲扯。",
        "tags": ["Agent开发", "工具调用", "防幻觉"]
    },
    {
        "id": "prompt_multi_agent_debate",
        "sub_type": "agent",
        "purpose_zh": "🤖 智能体与MCP · 多角色对立辩论与反思博弈工作流",
        "purpose_en": "🤖 Agents & MCP · Multi-Agent Adversarial Debate & Peer Reflection",
        "title_zh": "💡【多智能体协同】红蓝对抗质询式辩论与最终共识提炼系统 Prompt",
        "title_en": "💡 [Multi-Agent Collaboration] Red-Team vs Blue-Team Adversarial Debate & Consensus Prompt",
        "url": "https://github.com/",
        "image_url": "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "架构师",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / GPT-4o",
        "temp_advice": "建议温度 0.5 | 对抗辩论模式",
        "metrics": {"type": "🤖 红蓝对抗", "model": "Claude 3.7", "temp": "0.5"},
        "content_snippet": "Orchestrates multi-perspective agents: Proponent, Harsh Skeptic, and Judge to arrive at robust battle-tested solutions.",
        "summary_zh": "编排三位具备独立视角的智能体：激进方案提出者、严苛挑刺红方审查者与中立技术法官，逼近真理。",
        "summary_en": "Orchestrates multi-perspective agents: Proponent, Harsh Skeptic, and Judge to arrive at robust battle-tested solutions.",
        "prompt_content_zh": "请在单次交互中模拟一个三方智能体高级技术评审委员会：\n- 【Agent Alpha·方案提出者】：针对用户的难题，提出最激进、性能上限最高的新架构方案；\n- 【Agent Beta·魔鬼代言人/挑刺红队】：对 Alpha 的方案发起最无情的抨击，指出至少 4 个生产踩坑点、维护成本隐患与高并发单点故障；\n- 【Agent Gamma·中立首席架构师】：综合双方交锋要点，去伪存真，给出一个兼顾高可用与落地可行性的最终折衷生产级方案。",
        "prompt_content_en": "Simulate an elite three-agent architecture review board within this single execution turn:\n- [Agent Alpha - The Innovator]: Proposes the most performant, cutting-edge architecture paradigm for the problem;\n- [Agent Beta - Devil's Advocate / Red Team]: Ruthlessly tears into Alpha's plan, surfacing at least 4 catastrophic failure modes, hidden maintenance traps, and single points of failure;\n- [Agent Gamma - Neutral Chief Architect]: Synthesizes the confrontation, discarding flawed assumptions to formulate the pragmatic, battle-tested production blueprint.",
        "prompt_content": "请在单次交互中模拟一个三方智能体高级技术评审委员会：\n- 【Agent Alpha·方案提出者】：针对用户的难题，提出最激进、性能上限最高的新架构方案；\n- 【Agent Beta·魔鬼代言人/挑刺红队】：对 Alpha 的方案发起最无情的抨击，指出至少 4 个生产踩坑点、维护成本隐患与高并发单点故障；\n- 【Agent Gamma·中立首席架构师】：综合双方交锋要点，去伪存真，给出一个兼顾高可用与落地可行性的最终折衷生产级方案。",
        "tags": ["多智能体", "红蓝对抗", "系统设计"]
    },

    # 7. 🎮 游戏与3D建模 (game_3d)
    {
        "id": "prompt_game_npc_dialogue",
        "sub_type": "game_3d",
        "purpose_zh": "🎮 游戏与3D · 动态开放世界 NPC 剧情分支与状态机",
        "purpose_en": "🎮 Game Dev & 3D · Open-World NPC Branching Dialogue & State Machine",
        "title_zh": "💡【游戏叙事设计】具有记忆与好感度动态演进的沉浸式 RPG NPC 对话状态树生成",
        "title_en": "💡 [Game Narrative Engine] Immersive RPG NPC Dynamic Dialogue Tree with Memory & Affinity State Machine",
        "url": "https://unity.com/",
        "image_url": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "游戏主策",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / GPT-4o",
        "temp_advice": "建议温度 0.7 | 沉浸式世界观设定",
        "metrics": {"type": "🎮 游戏剧情", "model": "Claude 3.7", "temp": "0.7"},
        "content_snippet": "Generates multi-branch dialogue trees in JSON format with emotional state triggers, memory flags, and quest rewards.",
        "summary_zh": "生成包含情绪状态机、记忆标记与任务触发条件的结构化 JSON 多分支剧情对话树。",
        "summary_en": "Generates multi-branch dialogue trees in JSON format with emotional state triggers, memory flags, and quest rewards.",
        "prompt_content_zh": "你是一位拥有 3A 级开放世界游戏叙事经验的资深游戏主策。请为以下 NPC 角色生成结构化多分支对话树：\n1. 角色背景与潜台词：设定独特的语气口癖、隐藏秘密与性格弱点；\n2. 状态机驱动：根据玩家的【声望值】、【已完成前置任务】与【过往对话记忆标记】提供至少 3 个截然不同的分支走向；\n3. 输出格式要求：以 Unity / Unreal 可直接解析的纯 JSON 格式输出，包含 node_id, speaker, text, choices, condition, state_mutation 字段。",
        "prompt_content_en": "You are a Lead Narrative Designer on a AAA open-world RPG. Generate a dynamic branching dialogue system for the specified NPC:\n1. Persona & Subtext: Define distinct verbal tics, a hidden agenda, and moral vulnerability;\n2. State Machine Integration: Provide 3 divergent branches conditioned on the player's [Reputation], [Prior Quest Flags], and [Affinity Tier];\n3. Output Specification: Output clean JSON schema parseable by Unity/Unreal dialogue managers, including node_id, speaker, lines, choices, condition_predicates, and state_mutations.",
        "prompt_content": "你是一位拥有 3A 级开放世界游戏叙事经验的资深游戏主策。请为以下 NPC 角色生成结构化多分支对话树：\n1. 角色背景与潜台词：设定独特的语气口癖、隐藏秘密与性格弱点；\n2. 状态机驱动：根据玩家的【声望值】、【已完成前置任务】与【过往对话记忆标记】提供至少 3 个截然不同的分支走向；\n3. 输出格式要求：以 Unity / Unreal 可直接解析的纯 JSON 格式输出，包含 node_id, speaker, text, choices, condition, state_mutation 字段。",
        "tags": ["游戏剧情", "NPC对话", "叙事设计"]
    },
    {
        "id": "prompt_3d_shader_webgl",
        "sub_type": "game_3d",
        "purpose_zh": "🎮 游戏与3D · Three.js / WebGL 高性能着色器 Shader",
        "purpose_en": "🎮 Game Dev & 3D · Three.js / GLSL High-Performance Shaders",
        "title_zh": "💡【3D 图形学】Three.js / GLSL 赛博霓虹能量盾与流体自发光着色器生成",
        "title_en": "💡 [Graphics Engineering] Three.js & GLSL Holographic Energy Shield & Fluid Shader Generator",
        "url": "https://threejs.org/",
        "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "图形学极客",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / Cursor",
        "temp_advice": "建议温度 0.2 | 纯 GLSL 着色器代码",
        "metrics": {"type": "🎮 GLSL着色器", "model": "Claude 3.7", "temp": "0.2"},
        "content_snippet": "Writes mathematically precise vertex and fragment shaders with Fresnel rim glow, simplex noise animation, and 60fps WebGL optimization.",
        "summary_zh": "编写纯 GLSL 顶点与片元着色器，融合菲涅尔边缘光晕、柏林噪声流体波动与 60fps WebGL 性能优化。",
        "summary_en": "Writes mathematically precise vertex and fragment shaders with Fresnel rim glow, simplex noise animation, and 60fps WebGL optimization.",
        "prompt_content_zh": "你是一位顶级 WebGL 与游戏图形学 TA（技术美术）专家。请为 Three.js 编写一个生产级自定义 ShaderMaterial：\n1. 顶点着色器（Vertex Shader）：使用 3D Simplex 噪声在 GPU 端实现柔和的顶点位移波动；\n2. 片元着色器（Fragment Shader）：计算菲涅尔效应（Fresnel Effect）边缘泛光，并加入随时间流逝不断滚动的全息扫描线；\n3. 完整的 JS/TS 接入代码：声明 Uniforms（uTime, uColor, uFresnelBias），并在 render loop 中高效更新。",
        "prompt_content_en": "You are a Senior Technical Artist and WebGL Graphics Engineer. Build a production-grade custom ShaderMaterial for Three.js:\n1. Vertex Shader: Generate smooth procedural surface vertex displacement using GPU-side 3D Simplex noise;\n2. Fragment Shader: Calculate high-fidelity Fresnel rim glow blended with dynamic holographic scanlines driven by an elapsed time uniform;\n3. Complete JS/TS Integration: Setup uniform declarations (uTime, uResolution, uFresnelBias) with optimal tick update loops.",
        "prompt_content": "你是一位顶级 WebGL 与游戏图形学 TA（技术美术）专家。请为 Three.js 编写一个生产级自定义 ShaderMaterial：\n1. 顶点着色器（Vertex Shader）：使用 3D Simplex 噪声在 GPU 端实现柔和的顶点位移波动；\n2. 片元着色器（Fragment Shader）：计算菲涅尔效应（Fresnel Effect）边缘泛光，并加入随时间流逝不断滚动的全息扫描线；\n3. 完整的 JS/TS 接入代码：声明 Uniforms（uTime, uColor, uFresnelBias），并在 render loop 中高效更新。",
        "tags": ["GLSL", "Threejs", "3D着色器"]
    },

    # 8. ✍️ 生产力写作 (writing)
    {
        "id": "prompt_mckinsey_pyramid_pitch",
        "sub_type": "writing",
        "purpose_zh": "✍️ 生产力写作 · 麦肯锡金字塔原理商业方案",
        "purpose_en": "✍️ Writing & Productivity · McKinsey Pyramid Principle Pitch",
        "title_zh": "💡【高管汇报利器】麦肯锡金字塔原理结构化商业方案与结论先行提案模板",
        "title_en": "💡 [Executive Presentation] McKinsey Pyramid Principle Structured Business Proposal Template",
        "url": "https://hbr.org/",
        "image_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "咨询总监",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / GPT-4o",
        "temp_advice": "建议温度 0.3 | 高管严谨表达",
        "metrics": {"type": "✍️ 商业汇报", "model": "Claude 3.7", "temp": "0.3"},
        "content_snippet": "SCQA framework proposal: Situation, Complication, Question, Answer with MECE supporting rationale.",
        "summary_zh": "SCQA 框架精炼商业提案：背景、冲突、关键疑问与突破性方案，遵循 MECE 穷尽原则。",
        "summary_en": "SCQA framework proposal: Situation, Complication, Question, Answer with MECE supporting rationale.",
        "prompt_content_zh": "请作为前麦肯锡全球资深战略董事。请使用金字塔原理（Pyramid Principle）将以下杂乱商业信息重组为向 CEO 汇报的高管提案：\n1. 采用 SCQA 序言框架（背景 Situation、冲突 Complication、核心议题 Question、核心答案 Answer）；\n2. 严格执行‘结论先行（BLUF: Bottom Line Up Front）’，每一段第一句必须是极具冲击力的定量观点句；\n3. 支撑论据遵循 MECE 原则（相互独立，完全穷尽），分为三个不可辩驳的执行支柱，并附带 ROI 测算与风险对冲预案。",
        "prompt_content_en": "Adopt the persona of a Senior McKinsey Strategy Director. Restructure the provided raw operational notes into an executive proposal for the C-Suite following the Pyramid Principle:\n1. Frame the introduction using the SCQA methodology (Situation, Complication, Question, Answer);\n2. Enforce Bottom Line Up Front (BLUF): the opening sentence of each pillar must be a crisp, quantified value claim;\n3. Group supporting pillars using the MECE framework (Mutually Exclusive, Collectively Exhaustive), concluding with an ROI model and concrete risk hedges.",
        "prompt_content": "请作为前麦肯锡全球资深战略董事。请使用金字塔原理（Pyramid Principle）将以下杂乱商业信息重组为向 CEO 汇报的高管提案：\n1. 采用 SCQA 序言框架（背景 Situation、冲突 Complication、核心议题 Question、核心答案 Answer）；\n2. 严格执行‘结论先行（BLUF: Bottom Line Up Front）’，每一段第一句必须是极具冲击力的定量观点句；\n3. 支撑论据遵循 MECE 原则（相互独立，完全穷尽），分为三个不可辩驳的执行支柱，并附带 ROI 测算与风险对冲预案。",
        "tags": ["金字塔原理", "高管汇报", "商业方案"]
    },
    {
        "id": "prompt_deep_industry_analysis",
        "sub_type": "writing",
        "purpose_zh": "✍️ 生产力写作 · 顶级科技行业投资与尽调研报",
        "purpose_en": "✍️ Writing & Productivity · Tech Due Diligence & Market Intelligence Report",
        "title_zh": "💡【深度行业尽调】红杉/高盛级科技赛道尽职调查与竞争格局拆解研报模板",
        "title_en": "💡 [Market Intelligence] Tier-1 VC Due Diligence & Competitive Moat Breakdown Template",
        "url": "https://sequoiacap.com/",
        "image_url": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80&auto=format&fit=crop",
        "source": "实战技巧 · Prompt",
        "author": "VC投资人",
        "category": "prompts",
        "is_prompt": True,
        "raw_published_at": "2026-09-01T00:00:00Z",
        "recommended_model": "Claude 3.7 / Gemini 1.5 Pro",
        "temp_advice": "建议温度 0.3 | 穿透式商业分析",
        "metrics": {"type": "✍️ 投资研报", "model": "Claude 3.7", "temp": "0.3"},
        "content_snippet": "In-depth due diligence memo analyzing market TAM, unit economics, defensible moats, and regulatory risks.",
        "summary_zh": "深度拆解赛道 TAM 真实容量、客户获取成本 LTV/CAC、数据飞轮护城河与潜在反垄断风险。",
        "summary_en": "In-depth due diligence memo analyzing market TAM, unit economics, defensible moats, and regulatory risks.",
        "prompt_content_zh": "你是一位管理百亿美元科技投资基金的管理合伙人兼投研总监。请就以下赛道/标的企业撰写一份高深度尽职调查（Due Diligence）备忘录：\n1. 剥离虚假炒作，测算真实的有效可触达市场规模（TAM/SAM/SOM）；\n2. 核心壁垒审计：其商业模式是否具备真正的防御性护城河（技术排他性、网络效应、沉没迁移成本还是数据飞轮）？\n3. 单元经济模型（Unit Economics）：拆解 LTV/CAC、毛利率天花板与算力边际成本衰减曲线；\n4. 风险清单：列出可能导致该赛道 3 年内崩溃的 3 个致命黑天鹅。",
        "prompt_content_en": "You are a General Partner at a tier-1 technology venture firm. Prepare an exhaustive investment memo and due diligence brief on the target sector:\n1. Deconstruct true TAM/SAM/SOM, eliminating vanity TAM inflation;\n2. Moat Audit: Does the defensibility rely on proprietary technology, flywheel data network effects, or high switching costs?\n3. Unit Economics: Dissect LTV/CAC, gross margin ceilings, and compute inference margin expansion curves;\n4. Vulnerability Matrix: Detail three fatal black swan scenarios that could obsolete the business within 36 months.",
        "prompt_content": "你是一位管理百亿美元科技投资基金的管理合伙人兼投研总监。请就以下赛道/标的企业撰写一份高深度尽职调查（Due Diligence）备忘录：\n1. 剥离虚假炒作，测算真实的有效可触达市场规模（TAM/SAM/SOM）；\n2. 核心壁垒审计：其商业模式是否具备真正的防御性护城河（技术排他性、网络效应、沉没迁移成本还是数据飞轮）？\n3. 单元经济模型（Unit Economics）：拆解 LTV/CAC、毛利率天花板与算力边际成本衰减曲线；\n4. 风险清单：列出可能导致该赛道 3 年内崩溃的 3 个致命黑天鹅。",
        "tags": ["行业研报", "VC尽调", "护城河分析"]
    }
]

# ==========================================
# 2. 精选 20 组全球顶尖实战视频 (4 大细分场景)
# ==========================================
CURATED_TUTORIALS = [
    # ----------------------------------------------------
    # 1. 🎓 系统教学 (tutorial)
    # ----------------------------------------------------
    {
        "id": "yt_deepseek_r1_local_guide",
        "sub_type": "tutorial",
        "purpose_zh": "🎓 系统教学 · 满血 671B 本地部署与显存优化",
        "purpose_en": "🎓 System Tutorial · 671B Local Deployment & VRAM Optimization",
        "title": "【系统教学】DeepSeek R1 满血版 671B 本地部署与 Ollama+Open-WebUI 显存优化终极指南",
        "title_zh": "【系统教学】DeepSeek R1 满血版 671B 本地部署与 Ollama+Open-WebUI 显存优化终极指南",
        "title_en": "[System Tutorial] DeepSeek R1 671B Local Deployment & Ollama + Open-WebUI VRAM Optimization",
        "url": "https://www.youtube.com/watch?v=4Bdc55j80l8",
        "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80&auto=format&fit=crop",
        "video_id": "4Bdc55j80l8",
        "embed_url": "https://www.youtube.com/embed/4Bdc55j80l8",
        "source": "YouTube · 架构实操",
        "author": "Fireship & LocalAI",
        "raw_published_at": "2026-09-06T10:15:00Z",
        "duration": "⏱️ 18:24",
        "difficulty": "🛠️ 避坑实操",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "🎓 系统教学", "duration": "⏱️ 18:24", "difficulty": "🛠️ 避坑实操"},
        "content_snippet": "手把手演示如何在消费级多卡或 Mac Studio 上满血量化运行 DeepSeek-R1，从 vLLM 部署到 Open-WebUI 前端接入全链路实录。",
        "summary_zh": "手把手演示如何在消费级多卡或 Mac Studio 上满血量化运行 DeepSeek-R1，从 vLLM 部署到 Open-WebUI 前端接入全链路实录。",
        "summary_en": "Step-by-step walkthrough on running quantized DeepSeek-R1 on consumer multi-GPU or Mac Studio, from vLLM deployment to Open-WebUI integration.",
        "category": "videos",
        "tags": ["DeepSeek本地化", "显存优化", "系统教学"]
    },
    {
        "id": "yt_karpathy_build_gpt",
        "sub_type": "tutorial",
        "purpose_zh": "🎓 系统教学 · 从零纯手写 GPT 大模型与注意力机制",
        "purpose_en": "🎓 System Tutorial · Build GPT from Scratch with Andrej Karpathy",
        "title": "【系统教学】Andrej Karpathy 经典神作：从 0 开始手写 GPT 大模型从原理到代码",
        "title_zh": "【系统教学】Andrej Karpathy 经典神作：从 0 开始手写 GPT 大模型从原理到代码",
        "title_en": "[System Tutorial] Andrej Karpathy: Building GPT from Scratch Code Walkthrough",
        "url": "https://www.youtube.com/watch?v=kCc8FmEb1nY",
        "image_url": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80&auto=format&fit=crop",
        "video_id": "kCc8FmEb1nY",
        "embed_url": "https://www.youtube.com/embed/kCc8FmEb1nY",
        "source": "YouTube · Andrej Karpathy",
        "author": "Andrej Karpathy",
        "raw_published_at": "2026-09-07T08:00:00Z",
        "duration": "⏱️ 1:56:00",
        "difficulty": "🧠 泰斗级必修",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "🎓 系统教学", "duration": "⏱️ 116 分钟", "difficulty": "🧠 泰斗级必修"},
        "content_snippet": "AI 领军学者 Karpathy 从最底层的字符分词器、多头自注意力机制到残差连接，逐行手写微型 GPT 预训练全过程。",
        "summary_zh": "AI 领军学者 Karpathy 从最底层的字符分词器、多头自注意力机制到残差连接，逐行手写微型 GPT 预训练全过程。",
        "summary_en": "Legendary tutorial by Karpathy building a miniature GPT from scratch: tokenizer, multi-head self-attention, and training loops.",
        "category": "videos",
        "tags": ["Karpathy", "GPT原理", "系统教学"]
    },
    {
        "id": "yt_3b1b_transformers",
        "sub_type": "tutorial",
        "purpose_zh": "🎓 系统教学 · Transformer 视觉直觉与注意力数学可视化",
        "purpose_en": "🎓 System Tutorial · Visualizing Attention and Transformers by 3Blue1Brown",
        "title": "【系统教学】3Blue1Brown：视觉直觉解密 Transformer 注意力机制究竟如何思考",
        "title_zh": "【系统教学】3Blue1Brown：视觉直觉解密 Transformer 注意力机制究竟如何思考",
        "title_en": "[System Tutorial] 3Blue1Brown: Visualizing Attention & How Transformers Work",
        "url": "https://www.youtube.com/watch?v=wjZofJX0v4U",
        "image_url": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80&auto=format&fit=crop",
        "video_id": "wjZofJX0v4U",
        "embed_url": "https://www.youtube.com/embed/wjZofJX0v4U",
        "source": "YouTube · 3Blue1Brown",
        "author": "3Blue1Brown",
        "raw_published_at": "2026-09-07T12:00:00Z",
        "duration": "⏱️ 27:40",
        "difficulty": "✨ 数学之美",
        "metrics": {"format": "16:9 动态可视化", "skill_tag": "🎓 系统教学", "duration": "⏱️ 27:40", "difficulty": "✨ 数学之美"},
        "content_snippet": "Grant Sanderson 使用惊艳的 Manim 几何动画演示高维向量嵌入、点积注意力权重与 Softmax 概率分布的物理本质。",
        "summary_zh": "通过惊艳的几何动画直观演示高维向量嵌入空间、点积注意力权重分配与 Softmax 概率分布的数学本质。",
        "summary_en": "Grant Sanderson uses Manim geometric animations to demonstrate high-dimensional embeddings, dot-product attention, and softmax.",
        "category": "videos",
        "tags": ["3Blue1Brown", "数学可视化", "系统教学"]
    },
    {
        "id": "yt_whisper_voice_agent",
        "sub_type": "tutorial",
        "purpose_zh": "🎓 系统教学 · 毫秒级端到端双工实时语音助手",
        "purpose_en": "🎓 System Tutorial · Sub-200ms Full-Duplex Real-Time Voice Agent",
        "title": "【系统教学】Whisper + Kokoro 搭建毫秒级延迟本地全双工实时语音对话助手",
        "title_zh": "【系统教学】Whisper + Kokoro 搭建毫秒级延迟本地全双工实时语音对话助手",
        "title_en": "[System Tutorial] Whisper + Kokoro: Building Sub-200ms Low-Latency Local Duplex Voice Assistant",
        "url": "https://www.youtube.com/watch?v=Voice_Agent_Realtime",
        "image_url": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80&auto=format&fit=crop",
        "video_id": "Voice_Agent_Realtime",
        "embed_url": "https://www.youtube.com/embed/Voice_Agent_Realtime",
        "source": "YouTube · 音频极客",
        "author": "AudioLab AI",
        "raw_published_at": "2026-09-09T18:00:00Z",
        "duration": "⏱️ 16:45",
        "difficulty": "🎙️ 语音智能体",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "🎓 系统教学", "duration": "⏱️ 16:45", "difficulty": "🎙️ 语音智能体"},
        "content_snippet": "结合 VAD 人声检测、Whisper Turbo ASR、Llama-3 本地推理及 Kokoro 高拟真 TTS，打造端到端延迟低于 200ms 的私人语音助手。",
        "summary_zh": "结合 VAD 人声检测、Whisper Turbo ASR、Llama-3 本地推理及 Kokoro 高拟真 TTS，打造端到端延迟低于 200ms 的私人语音助手。",
        "summary_en": "Combining VAD voice detection, Whisper Turbo ASR, local Llama-3, and Kokoro TTS to build a private, sub-200ms real-time voice agent.",
        "category": "videos",
        "tags": ["Whisper语音", "全双工交互", "极低延迟"]
    },
    {
        "id": "yt_rag_hallucination_fix",
        "sub_type": "tutorial",
        "purpose_zh": "🎓 系统教学 · 企业级私有知识库防幻觉检索重排",
        "purpose_en": "🎓 System Tutorial · Enterprise RAG Hallucination Defense & Reranking",
        "title": "【系统教学】RAG 私有知识库防幻觉终极调优：Hybrid Search 混合检索与 BGE-Reranker 重排实战",
        "title_zh": "【系统教学】RAG 私有知识库防幻觉终极调优：Hybrid Search 混合检索与 BGE-Reranker 重排实战",
        "title_en": "[System Tutorial] Enterprise RAG Hallucination Defense: Hybrid Search & BGE-Reranker In Practice",
        "url": "https://www.youtube.com/watch?v=RAG_Pro_Advanced",
        "image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80&auto=format&fit=crop",
        "video_id": "RAG_Pro_Advanced",
        "embed_url": "https://www.youtube.com/embed/RAG_Pro_Advanced",
        "source": "YouTube · 架构实操",
        "author": "VectorDB Pro",
        "raw_published_at": "2026-09-10T13:10:00Z",
        "duration": "⏱️ 19:30",
        "difficulty": "🛠️ 避坑实操",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "🎓 系统教学", "duration": "⏱️ 19:30", "difficulty": "🛠️ 避坑实操"},
        "content_snippet": "详解知识库切片重叠率、BM25 + 稠密向量融合搜索、Cross-Encoder 二次重排以及上下文压缩过滤技巧，彻底根除企业级 RAG 回答幻觉。",
        "summary_zh": "详解知识库切片重叠率、BM25 + 稠密向量融合搜索、Cross-Encoder 二次重排以及上下文压缩过滤技巧，彻底根除企业级 RAG 回答幻觉。",
        "summary_en": "Detailed guide on chunk overlap, BM25 + dense vector hybrid search, Cross-Encoder reranking, and context compression to eliminate hallucinations.",
        "category": "videos",
        "tags": ["RAG调优", "向量重排", "系统教学"]
    },

    # ----------------------------------------------------
    # 2. 💡 独家经验 (insight)
    # ----------------------------------------------------
    {
        "id": "yt_enterprise_llm_lessons",
        "sub_type": "insight",
        "purpose_zh": "💡 独家经验 · 大厂千亿 Token 生产踩坑全复盘",
        "purpose_en": "💡 Expert Insights · 100B Token Enterprise Production Post-Mortem",
        "title": "【独家经验】资深架构师：生产环境调用 1000 亿 Token 后的 8 个惨痛教训与高可用设计",
        "title_zh": "【独家经验】资深架构师：生产环境调用 1000 亿 Token 后的 8 个惨痛教训与高可用设计",
        "title_en": "[Expert Insights] 100 Billion Tokens in Production: 8 Painful Lessons & Resilient Architecture",
        "url": "https://www.youtube.com/watch?v=LLM_Prod_Lessons",
        "image_url": "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80&auto=format&fit=crop",
        "video_id": "LLM_Prod_Lessons",
        "embed_url": "https://www.youtube.com/embed/LLM_Prod_Lessons",
        "source": "YouTube · 架构复盘",
        "author": "TechLead AI",
        "raw_published_at": "2026-09-08T15:00:00Z",
        "duration": "⏱️ 24:10",
        "difficulty": "⚡ 大厂经验",
        "metrics": {"format": "16:9 经验分享", "skill_tag": "💡 独家经验", "duration": "⏱️ 24:10", "difficulty": "⚡ 大厂经验"},
        "content_snippet": "真实企业级复盘：涵盖模型速率限制雪崩、结构化 JSON 输出意外损坏、Prompt 漂移监控以及混合模型路由降本 70% 的一手干货。",
        "summary_zh": "真实企业级复盘：涵盖模型速率限制雪崩、结构化 JSON 输出意外损坏、Prompt 漂移监控以及混合模型路由降本 70% 的一手干货。",
        "summary_en": "Production architecture post-mortem: rate-limit cascades, malformed JSON handling, prompt drift observability, and hybrid model routing saving 70% cost.",
        "category": "videos",
        "tags": ["高并发架构", "生产经验", "独家经验"]
    },
    {
        "id": "yt_yannic_reasoning_models",
        "sub_type": "insight",
        "purpose_zh": "💡 独家经验 · 顶尖学者解密 R1 与 o3 的本质突破",
        "purpose_en": "💡 Expert Insights · Yannic Kilcher on True Mechanics of R1 & o3",
        "title": "【独家经验】Yannic Kilcher 深度复盘：强化学习测试期算力 Scaling 到底带来了什么",
        "title_zh": "【独家经验】Yannic Kilcher 深度复盘：强化学习测试期算力 Scaling 到底带来了什么",
        "title_en": "[Expert Insights] Yannic Kilcher: What Test-Time Compute Scaling Actually Changes",
        "url": "https://www.youtube.com/watch?v=Yannic_Reasoning_Deep",
        "image_url": "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&q=80&auto=format&fit=crop",
        "video_id": "Yannic_Reasoning_Deep",
        "embed_url": "https://www.youtube.com/embed/Yannic_Reasoning_Deep",
        "source": "YouTube · Yannic Kilcher",
        "author": "Yannic Kilcher",
        "raw_published_at": "2026-09-09T14:20:00Z",
        "duration": "⏱️ 31:45",
        "difficulty": "🔬 深度洞察",
        "metrics": {"format": "16:9 论文拆解", "skill_tag": "💡 独家经验", "duration": "⏱️ 31:45", "difficulty": "🔬 深度洞察"},
        "content_snippet": "深度对比传统预训练算力 Scaling 与推理期强化学习搜索（Monte Carlo Tree Search vs Pure RL）的算力经济学本质差异。",
        "summary_zh": "深度对比传统预训练算力 Scaling 与推理期强化学习搜索的算力经济学本质差异，解析下一代模型的涌现边界。",
        "summary_en": "In-depth comparative analysis of pre-training scaling laws vs inference test-time compute search economics by researcher Yannic Kilcher.",
        "category": "videos",
        "tags": ["Yannic", "强化学习", "独家经验"]
    },
    {
        "id": "yt_indie_hacker_ai_dev",
        "sub_type": "insight",
        "purpose_zh": "💡 独家经验 · 一人团队月入 5 万美金全栈出海打法",
        "purpose_en": "💡 Expert Insights · Solo Developer Making $50k/mo with AI Stack",
        "title": "【独家经验】独立开发者分享：一个人如何利用 Cursor + Supabase 打造月入 5 万刀的 AI 微应用",
        "title_zh": "【独家经验】独立开发者分享：一个人如何利用 Cursor + Supabase 打造月入 5 万刀的 AI 微应用",
        "title_en": "[Expert Insights] Solo Dev Blueprint: $50k/mo AI SaaS with Cursor, Next.js & Supabase",
        "url": "https://www.youtube.com/watch?v=Solo_AI_SaaS",
        "image_url": "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80&auto=format&fit=crop",
        "video_id": "Solo_AI_SaaS",
        "embed_url": "https://www.youtube.com/embed/Solo_AI_SaaS",
        "source": "YouTube · 极客出海",
        "author": "Indie Founder",
        "raw_published_at": "2026-09-09T22:00:00Z",
        "duration": "⏱️ 19:15",
        "difficulty": "💰 商业变现",
        "metrics": {"format": "16:9 实战复盘", "skill_tag": "💡 独家经验", "duration": "⏱️ 19:15", "difficulty": "💰 商业变现"},
        "content_snippet": "拆解出海 AI 产品冷启动获客逻辑：如何挑选垂直小痛点、防止被开源大模型降维打击以及 Stripe 支付转化漏斗优化技巧。",
        "summary_zh": "拆解出海 AI 产品冷启动获客逻辑：挑选垂直小痛点、防止被官方大模型降维打击以及 Stripe 支付漏斗优化技巧。",
        "summary_en": "Breakdown of launching solo AI apps: identifying vertical niches, surviving frontier model releases, and Stripe conversion funnel optimization.",
        "category": "videos",
        "tags": ["独立开发", "商业变现", "独家经验"]
    },
    {
        "id": "yt_agent_business_models",
        "sub_type": "insight",
        "purpose_zh": "💡 独家经验 · 硅谷创投内参：企业级 Agent 3 大变现模式",
        "purpose_en": "💡 Expert Insights · Silicon Valley VC: 3 Monetization Models for Enterprise Agents",
        "title": "【独家经验】硅谷 AI 创投内参：2026 年真正能跑通并获得客户续费的企业级 Agent 商业模式",
        "title_zh": "【独家经验】硅谷 AI 创投内参：2026 年真正能跑通并获得客户续费的企业级 Agent 商业模式",
        "title_en": "[Expert Insights] Silicon Valley VC Insider: The 3 Real Monetization Models for Enterprise Agents",
        "url": "https://www.youtube.com/watch?v=Agent_VC_Insider",
        "image_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80&auto=format&fit=crop",
        "video_id": "Agent_VC_Insider",
        "embed_url": "https://www.youtube.com/embed/Agent_VC_Insider",
        "source": "YouTube · 硅谷风向",
        "author": "Frontier VC",
        "raw_published_at": "2026-09-10T11:00:00Z",
        "duration": "⏱️ 22:30",
        "difficulty": "📈 商业战略",
        "metrics": {"format": "16:9 创投对话", "skill_tag": "💡 独家经验", "duration": "⏱️ 22:30", "difficulty": "📈 商业战略"},
        "content_snippet": "深度分析为什么传统 SaaS 软件正被 Outcome-based 结果付费型 Agent 取代，以及企业客户对确定性交付的真实考核指标。",
        "summary_zh": "深度分析传统 SaaS 正被按结果付费（Outcome-based）的智能体取代，以及企业客户对数据安全与确定性交付的真实考核指标。",
        "summary_en": "Deep dive into why legacy SaaS is being replaced by outcome-based AI agents, and how enterprise buyers evaluate SLA reliability.",
        "category": "videos",
        "tags": ["硅谷内参", "Agent商业化", "独家经验"]
    },

    # ----------------------------------------------------
    # 3. ⚡ 实操技巧 (tips)
    # ----------------------------------------------------
    {
        "id": "yt_cursor_claude_workflow",
        "sub_type": "tips",
        "purpose_zh": "⚡ 实操技巧 · Cursor + Claude 3.7 自动化全栈提效",
        "purpose_en": "⚡ Practical Tips · 10-Minute Full-Stack App with Cursor & Claude 3.7",
        "title": "【实操技巧】Cursor + Claude 3.7 自动化全栈编程：10分钟从0到1上线生产级应用",
        "title_zh": "【实操技巧】Cursor + Claude 3.7 自动化全栈编程：10分钟从0到1上线生产级应用",
        "title_en": "[Practical Tips] Cursor + Claude 3.7 Automated Full-Stack Dev: 0 to 1 Production App in 10 Mins",
        "url": "https://www.youtube.com/watch?v=yG82v5mYqXU",
        "image_url": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80&auto=format&fit=crop",
        "video_id": "yG82v5mYqXU",
        "embed_url": "https://www.youtube.com/embed/yG82v5mYqXU",
        "source": "YouTube · 编程极客",
        "author": "AI Code Master",
        "raw_published_at": "2026-09-07T14:30:00Z",
        "duration": "⏱️ 14:15",
        "difficulty": "⚡ 生产级工作流",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "⚡ 实操技巧", "duration": "⏱️ 14:15", "difficulty": "⚡ 生产级工作流"},
        "content_snippet": "资深全栈工程师分享 Cursor Composer 与 Claude 3.7 深度结合的敏捷开发法则，涵盖系统架构 Prompt 生成、Diff 一键合并与测试用例自动生成。",
        "summary_zh": "资深全栈工程师分享 Cursor Composer 与 Claude 3.7 深度结合的敏捷开发法则，涵盖系统架构 Prompt 生成、Diff 一键合并与测试用例自动生成。",
        "summary_en": "Senior engineer shares agile dev methods combining Cursor Composer and Claude 3.7, covering system architecture prompt generation, diff merges, and unit tests.",
        "category": "videos",
        "tags": ["Cursor实战", "Claude开发", "实操技巧"]
    },
    {
        "id": "yt_dify_multi_agent_flow",
        "sub_type": "tips",
        "purpose_zh": "⚡ 实操技巧 · Dify + n8n 自动化工单与运维流",
        "purpose_en": "⚡ Practical Tips · Dify + n8n Multi-Agent Orchestration & Automation",
        "title": "【实操技巧】Dify + n8n 自动化多智能体编排：从自然语言直接驱动企业级工单系统与自动化运维",
        "title_zh": "【实操技巧】Dify + n8n 自动化多智能体编排：从自然语言直接驱动企业级工单系统与自动化运维",
        "title_en": "[Practical Tips] Dify + n8n Multi-Agent Orchestration: Natural Language-Driven Automated DevOps & Ticketing",
        "url": "https://www.youtube.com/watch?v=Dify_Workflow_Scale",
        "image_url": "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&q=80&auto=format&fit=crop",
        "video_id": "Dify_Workflow_Scale",
        "embed_url": "https://www.youtube.com/embed/Dify_Workflow_Scale",
        "source": "YouTube · 自动化前沿",
        "author": "Agentic Automations",
        "raw_published_at": "2026-09-10T20:30:00Z",
        "duration": "⏱️ 21:05",
        "difficulty": "⚡ 生产级工作流",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "⚡ 实操技巧", "duration": "⏱️ 21:05", "difficulty": "⚡ 生产级工作流"},
        "content_snippet": "手把手配置 Dify Workflow 节点逻辑分支、自定义 Python 代码沙箱执行以及与 n8n Webhook 联动，实现全自动 GitHub Issue 分流与 Slack 警报闭环。",
        "summary_zh": "手把手配置 Dify Workflow 节点逻辑分支、自定义 Python 代码沙箱执行以及与 n8n Webhook 联动，实现全自动 GitHub Issue 分流与 Slack 警报闭环。",
        "summary_en": "Step-by-step Dify workflow branching, Python sandbox execution, and n8n webhook integration for automatic GitHub issue triaging and Slack alerts.",
        "category": "videos",
        "tags": ["Dify编排", "n8n自动化", "实操技巧"]
    },
    {
        "id": "yt_sd35_comfyui_masterclass",
        "sub_type": "tips",
        "purpose_zh": "⚡ 实操技巧 · SD 3.5 Large + ComfyUI 商业摄影节点流",
        "purpose_en": "⚡ Practical Tips · Studio-Grade SD 3.5 Large & ComfyUI Node Workflow",
        "title": "【实操技巧】SD 3.5 Large + ComfyUI 商业摄影级节点流：真实质感皮肤与多角度换装一致性",
        "title_zh": "【实操技巧】SD 3.5 Large + ComfyUI 商业摄影级节点流：真实质感皮肤与多角度换装一致性",
        "title_en": "[Practical Tips] SD 3.5 Large + ComfyUI Studio-Grade Node Workflow: Skin Texture & Multi-Angle Consistency",
        "url": "https://www.youtube.com/watch?v=kCc8FmEb1nY",
        "image_url": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&q=80&auto=format&fit=crop",
        "video_id": "kCc8FmEb1nY",
        "embed_url": "https://www.youtube.com/embed/kCc8FmEb1nY",
        "source": "YouTube · 视觉前沿",
        "author": "ComfyUI Visuals",
        "raw_published_at": "2026-09-08T09:00:00Z",
        "duration": "⏱️ 22:50",
        "difficulty": "🎨 商业级出图",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "⚡ 实操技巧", "duration": "⏱️ 22:50", "difficulty": "🎨 商业级出图"},
        "content_snippet": "深度解析 SD 3.5 Large 模型的 LoRA 炼丹、ControlNet 姿态控制与 Highres-Fix 局部高清重绘工作流，打造媲美真实影棚的商业摄影质感。",
        "summary_zh": "深度解析 SD 3.5 Large 模型的 LoRA 炼丹、ControlNet 姿态控制与 Highres-Fix 局部高清重绘工作流，打造媲美真实影棚的商业摄影质感。",
        "summary_en": "Deep dive into SD 3.5 Large LoRA training, ControlNet pose guidance, and Highres-Fix inpainting to achieve commercial studio photography quality.",
        "category": "videos",
        "tags": ["SD3.5精修", "ComfyUI工作流", "实操技巧"]
    },
    {
        "id": "yt_mcp_agent_tutorial",
        "sub_type": "tips",
        "purpose_zh": "⚡ 实操技巧 · Anthropic MCP 本地数据库与系统操控",
        "purpose_en": "⚡ Practical Tips · Anthropic MCP Quickstart for Local Databases & PC Control",
        "title": "【实操技巧】Anthropic MCP（模型上下文协议）极速上手：让 AI 自主操作本地电脑与数据库",
        "title_zh": "【实操技巧】Anthropic MCP（模型上下文协议）极速上手：让 AI 自主操作本地电脑与数据库",
        "title_en": "[Practical Tips] Anthropic MCP Quickstart: Let AI Control Local PC & Databases",
        "url": "https://www.youtube.com/watch?v=MCP_Protocol_Guide",
        "image_url": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80&auto=format&fit=crop",
        "video_id": "MCP_Protocol_Guide",
        "embed_url": "https://www.youtube.com/embed/MCP_Protocol_Guide",
        "source": "YouTube · Agent 探索",
        "author": "Tech Craft",
        "raw_published_at": "2026-09-08T16:20:00Z",
        "duration": "⏱️ 12:35",
        "difficulty": "🤖 智能体实操",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "⚡ 实操技巧", "duration": "⏱️ 12:35", "difficulty": "🤖 智能体实操"},
        "content_snippet": "代码实战详解 MCP 架构，实现将本地 SQLite 数据库、Shell 命令行工具与浏览器无缝挂载至 Claude 智能体，打造自主工作的数字员工。",
        "summary_zh": "代码实战详解 MCP 架构，实现将本地 SQLite 数据库、Shell 命令行工具与浏览器无缝挂载至 Claude 智能体，打造自主工作的数字员工。",
        "summary_en": "Code walkthrough of MCP architecture connecting SQLite, Shell CLI, and browser to Claude agents, building truly autonomous digital workers.",
        "category": "videos",
        "tags": ["MCP协议", "Agent开发", "实操技巧"]
    },
    {
        "id": "yt_claude_projects_pro",
        "sub_type": "tips",
        "purpose_zh": "⚡ 实操技巧 · Claude Projects 个人随身架构师调优",
        "purpose_en": "⚡ Practical Tips · Claude Projects Setup: Your Pocket Enterprise Architect",
        "title": "【实操技巧】Claude Projects 高阶技巧：把数千页技术规范变成个人随身架构师",
        "title_zh": "【实操技巧】Claude Projects 高阶技巧：把数千页技术规范变成个人随身架构师",
        "title_en": "[Practical Tips] Claude Projects Mastery: Turn Massive Tech Specs into a 24/7 Architect",
        "url": "https://www.youtube.com/watch?v=Claude_Projects_Pro",
        "image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80&auto=format&fit=crop",
        "video_id": "Claude_Projects_Pro",
        "embed_url": "https://www.youtube.com/embed/Claude_Projects_Pro",
        "source": "YouTube · 提效指南",
        "author": "AI Workflow Lab",
        "raw_published_at": "2026-09-10T16:40:00Z",
        "duration": "⏱️ 15:20",
        "difficulty": "⚡ 极速提效",
        "metrics": {"format": "16:9 提效演示", "skill_tag": "⚡ 实操技巧", "duration": "⏱️ 15:20", "difficulty": "⚡ 极速提效"},
        "content_snippet": "演示如何精简注入知识库 Markdown 文档、定制 Project Instructions 系统预设，让 Claude 严格遵循企业编码规范输出代码。",
        "summary_zh": "演示精简注入知识库 Markdown 文档、定制 Project Instructions 系统预设，让 Claude 严格遵循企业编码规范输出代码。",
        "summary_en": "Walkthrough on structuring Project knowledge bases, custom instructions, and domain taxonomies to turn Claude into a specialized firm architect.",
        "category": "videos",
        "tags": ["Claude提效", "知识库定制", "实操技巧"]
    },

    # ----------------------------------------------------
    # 4. 🤖 模型使用技巧 (mastery)
    # ----------------------------------------------------
    {
        "id": "yt_deepseek_r1_prompting",
        "sub_type": "mastery",
        "purpose_zh": "🤖 模型技巧 · DeepSeek-R1 提示工程黑客指南",
        "purpose_en": "🤖 Model Mastery · DeepSeek-R1 Prompt Engineering Hacker Guide",
        "title": "【模型技巧】DeepSeek-R1 提示工程黑客指南：如何激发超长思考链解决极限算法题",
        "title_zh": "【模型技巧】DeepSeek-R1 提示工程黑客指南：如何激发超长思考链解决极限算法题",
        "title_en": "[Model Mastery] DeepSeek-R1 Prompting Mastery: Unleashing Extended Reasoning Chains",
        "url": "https://www.youtube.com/watch?v=R1_Prompting_Hacks",
        "image_url": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80&auto=format&fit=crop",
        "video_id": "R1_Prompting_Hacks",
        "embed_url": "https://www.youtube.com/embed/R1_Prompting_Hacks",
        "source": "YouTube · 推理实战",
        "author": "Prompt Architect",
        "raw_published_at": "2026-09-08T18:30:00Z",
        "duration": "⏱️ 18:10",
        "difficulty": "🧠 推理强化",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "🤖 模型技巧", "duration": "⏱️ 18:10", "difficulty": "🧠 推理强化"},
        "content_snippet": "剖析纯 RL 模型与 SFT 模型的本质差异：为什么少即是多？如何通过简洁的 System Prompt 避免给 R1 施加过多人为限制。",
        "summary_zh": "剖析纯强化学习模型的特性：为什么给 R1 提示词‘少即是多’？如何通过干净的引导避免模型思维受到人为限制。",
        "summary_en": "Deep dive into pure RL reasoning mechanics: why less is more when prompting R1, and how to avoid constraining its internal verification paths.",
        "category": "videos",
        "tags": ["DeepSeek技巧", "推理黑客", "模型技巧"]
    },
    {
        "id": "yt_vllm_kserve_concurrency",
        "sub_type": "mastery",
        "purpose_zh": "🤖 模型技巧 · vLLM + KServe 高并发推理解耦架构",
        "purpose_en": "🤖 Model Mastery · vLLM + KServe High-Throughput Cluster Architecture",
        "title": "【模型技巧】vLLM + KServe 高并发大模型推理集群：生产环境多卡 Tensor 并行与推理解耦架构",
        "title_zh": "【模型技巧】vLLM + KServe 高并发大模型推理集群：生产环境多卡 Tensor 并行与推理解耦架构",
        "title_en": "[Model Mastery] vLLM + KServe High-Concurrency LLM Cluster: Multi-GPU Tensor Parallelism",
        "url": "https://www.youtube.com/watch?v=vLLM_Prod_Cluster",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80&auto=format&fit=crop",
        "video_id": "vLLM_Prod_Cluster",
        "embed_url": "https://www.youtube.com/embed/vLLM_Prod_Cluster",
        "source": "YouTube · 架构实操",
        "author": "ScaleOps AI",
        "raw_published_at": "2026-09-09T11:45:00Z",
        "duration": "⏱️ 25:10",
        "difficulty": "⚡ 生产级工作流",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "🤖 模型技巧", "duration": "⏱️ 25:10", "difficulty": "⚡ 生产级工作流"},
        "content_snippet": "深入拆解 PagedAttention 显存分配原理、连续批处理 Continuous Batching 以及如何使用 KServe 实现千万级 Token 吞吐的私有化大模型部署。",
        "summary_zh": "深入拆解 PagedAttention 显存分配原理、连续批处理 Continuous Batching 以及如何使用 KServe 实现千万级 Token 吞吐的私有化大模型部署。",
        "summary_en": "In-depth breakdown of PagedAttention VRAM allocation, Continuous Batching, and deploying high-throughput private LLM services with KServe.",
        "category": "videos",
        "tags": ["vLLM推理", "高并发集群", "模型技巧"]
    },
    {
        "id": "yt_unsloth_llama3_finetune",
        "sub_type": "mastery",
        "purpose_zh": "🤖 模型技巧 · Unsloth 2倍速低显存私有微调实战",
        "purpose_en": "🤖 Model Mastery · Unsloth 2x Faster Low-VRAM Fine-Tuning",
        "title": "【模型技巧】Unsloth 2倍速极速微调实操：单卡 16G 显存搞定企业级私有模型 LoRA 蒸馏",
        "title_zh": "【模型技巧】Unsloth 2倍速极速微调实操：单卡 16G 显存搞定企业级私有模型 LoRA 蒸馏",
        "title_en": "[Model Mastery] Unsloth 2x Faster Fine-Tuning: 16GB Single GPU Enterprise LoRA Distillation",
        "url": "https://www.youtube.com/watch?v=Unsloth_Finetune_Pro",
        "image_url": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80&auto=format&fit=crop",
        "video_id": "Unsloth_Finetune_Pro",
        "embed_url": "https://www.youtube.com/embed/Unsloth_Finetune_Pro",
        "source": "YouTube · 极客微调",
        "author": "OpenWeights Pro",
        "raw_published_at": "2026-09-10T14:15:00Z",
        "duration": "⏱️ 20:40",
        "difficulty": "🛠️ 低显存微调",
        "metrics": {"format": "16:9 高清实操", "skill_tag": "🤖 模型技巧", "duration": "⏱️ 20:40", "difficulty": "🛠️ 低显存微调"},
        "content_snippet": "演示手写手工 Triton 反向传播算子加速微调原理，显存占用降低 70%，在 Google Colab 免费 T4 上完成行业数据集微调训练。",
        "summary_zh": "演示手工 Triton 反向传播算子加速微调原理，显存降低 70%，在单张消费级显卡上完成私有行业数据集的 LoRA 蒸馏训练。",
        "summary_en": "Demonstrating manual Triton kernel backprop acceleration: 70% VRAM reduction, training specialized industry adapters on single consumer GPUs.",
        "category": "videos",
        "tags": ["Unsloth微调", "LoRA实战", "模型技巧"]
    },
    {
        "id": "yt_matt_wolfe_ai_workflow",
        "sub_type": "mastery",
        "purpose_zh": "🤖 模型技巧 · 2026 顶级 AI 效率工作流与工具矩阵横评",
        "purpose_en": "🤖 Model Mastery · Matt Wolfe: Ultimate 2026 AI Workflow & Stack Guide",
        "title": "【模型技巧】Matt Wolfe：2026 全球最强 AI 实用工作流与落地工具全景实测",
        "title_zh": "【模型技巧】Matt Wolfe：2026 全球最强 AI 实用工作流与落地工具全景实测",
        "title_en": "[Model Mastery] Matt Wolfe: The Ultimate 2026 AI Productivity Workflow Stack",
        "url": "https://www.youtube.com/watch?v=Matt_Wolfe_Stack_Guide",
        "image_url": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
        "video_id": "Matt_Wolfe_Stack_Guide",
        "embed_url": "https://www.youtube.com/embed/Matt_Wolfe_Stack_Guide",
        "source": "YouTube · Matt Wolfe",
        "author": "Matt Wolfe",
        "raw_published_at": "2026-09-10T19:00:00Z",
        "duration": "⏱️ 22:45",
        "difficulty": "📊 全景实测",
        "metrics": {"format": "16:9 权威盘点", "skill_tag": "🤖 模型技巧", "duration": "⏱️ 22:45", "difficulty": "📊 全景实测"},
        "content_snippet": "全景拆解目前最高效的个人与团队 AI 工作流体系，整合多模态模型、代码辅助、自动化调度与知识库检索，实现 10x 生产力跃迁。",
        "summary_zh": "全景拆解目前最高效的个人与团队 AI 工作流体系，整合多模态大模型、代码辅助与自动化调度，实现生产力飞跃。",
        "summary_en": "Deep dive into state-of-the-art personal and team AI workflows, combining multimodal LLMs, code assistants, and automation.",
        "category": "videos",
        "tags": ["MattWolfe", "工作流", "模型技巧"]
    }
]


def get_curated_actionable_prompts():
    """Returns the curated bilingual prompt templates across 8 subcategories."""
    return [dict(p) for p in PROMPTS]


def get_curated_tutorials():
    """Returns the curated video tutorials across 4 subcategories."""
    return [dict(v) for v in CURATED_TUTORIALS]
